LunarVim/LunarVim

- keys/which-key.vim
Wintype type 'popup' is probably deprecated and no longer exists in Floaterm according to docs here:
https://github.com/voldikss/vim-floaterm/blob/master/doc/floaterm.txt
> fix not-existing Floaterm wintype option

- README.md
The package 'neovim-git' pulls in the latest source of neovim instead
of the 'neovim-nightly-git' package in the AUR. This will make sure there is no error
related to neovim version on the startup
> READ.md : Update the package name for Arch Linux

- vim-plug/plugins.vim
**Error**: `master branch doesn't exist`  
Fix update remote branch `release/remote`, 
according to the **fzf-preview** [Readme](https://github.com/yuki-yano/fzf-preview.vim/commit/985aaf0aec028f3469805ef17f7a3104905eff79#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
> Fix fzf-preview remote update

- init.lua
- lua/lsp/clangd.lua
I'm using this as my daily driver for C/C++ LSP.
It expects to find a compile-commands.json file in your root project folder.
It also picks up extra project specific settings from a .clangd file as described by the clangd docs.
> [LSP] clangd - Add support for C/C++ with clangd.

- lua/lsp/clangd.lua
No that LspInstall have landed the clangd support, they have improved it to support future versions of clangd automatically.
> [LSP] clangd - Support LspInstall upstream path.

- lua/nv-telescope/init.lua
Desired way to configure extensions is
to put it at the same level as 'defaults' property inside the 'setup' call.
> Refactor telescope extension config

- vimscript/nv-whichkey/init.vim
Key for ' '(<Space>) is displayed on the panel as 'SPC' by default.
However, it is displayed as blank instead of 'SPC'
when assigning 'which_key_display_names' variable without specifiying it.
> Add display name for key ' '(<Space>) in whichkey

- README.md
there is a lot of people in discord that can't get the build to work and with this, the Arch users can get neovim install super easy
> add Arch neovim installing script

- lua/settings.lua
This allows `:s///` or `:%s///` or `:'<,'>s///` commands to work in realtime.
How it works (video is not mine): [video](https://www.youtube.com/watch?v=dY9dME3l-iQ)
The bottom split can be ommited by passing `nosplit` instead of `split`.
> Add inccommand=split to settings

- lua/nv-globals.lua
Latest change to clang didn't initialize the clang global vars.
> Fix clang global vars nil value

- lua/lsp/js-ts-ls.lua
This patch allows tsserver to activate on standalone files, by adding `.`, as a `root_dir` marker.
This shouldn't break working inside projects, becouse now tsserver will behave like vscode's integrated server.
> Make tsserver work on standalone files

- lua/nv-autocommands/init.lua
Previously the tabline wouldn't show up after opening `Settings` from dashboard.
> Fix opening settings from dashboard

- lua/nv-dashboard/init.lua
Only small thing, but it looks nicer and less cluttered.
Before:
After:
> Add more space between icon and description in dashboard

- lua/nv-autocommands/init.lua
I added bindings for `dashboard`, `lspinfo`, and `floaterm` to quickly quit out of them with `q` key.
The `<buffer>` thing scopes keybind to buffer of given filetype only.
This is inspired by `startify` plugin becouse these plugins doesn't have way to set bindings like that.
In floaterm you have to first hit `<Esc>` then `q`.
> Add bindings to quickly quit certain buffers

- vimscript/nv-whichkey/init.vim
1. renamed the `+fold` to `+mark`
2. changed the `'no highlight'` to capital `H` and now the `h -> 'split below'` shows up on the which key menu.
> Fixing a couple of typos in which key config

- utils/installer/install.sh
I also mentioned adding `sudo` to `npm i -g`, but you actually would not want to do this. The reason I was getting the error is because I had installed nvm, but hadn't set it up on my fresh install yet.
> minor-installer-fix: remove install argument from pacman

- init.lua
- lua/plugins.lua
example of loading specific plugin configs via packer
cleans up init.lua
allows for disabling plugin and its config by commenting out one line
> load plugin configs via packer

- lua/nv-telescope/init.lua
This option was marked as TODO in the telescope-nvim readme. This may be a suitable replacement in the meantime.
> Change vimgrep_arguments to find_command

- lua/keymappings.lua
Adds a vim-vinegar style mapping ('-' in normal mode) for accessing ranger.
> Add vim-vinegar style mapping for Ranger

- lua/lsp/efm-general-ls.lua
`--stdin-filename` doesn't look to be a valid option for black (anymore?), so I removed it and added the requisite `-`.
While I was in there, I also added support for [lua-fmt](https://github.com/trixnz/lua-fmt).
> fix(emf-general-ls): fix black, add lua-fmt

- lua/lsp/go-ls.lua
Fixed the issue of gopls unable to start unless current directory was git repo or contains a go.mod file.
Also added init_options that are kind of useful
> Gopls fixed. Root dir was causing problem

- lua/lv-autopairs/init.lua
In the latest pull of LunarVim, the autopairs plugin doesn't work. (Issue #313)
Looks like it had a few rules missing.
Added them in this PR.
> Fix Autopairs Not working issue

- utils/vscode_config/settings.json
Fixing possible typo on the `oneDarkPro` theme name. The theme name might have been changed from the creation of the file
> Fixed possible typo on settings.json

- lua/lsp/python-ls.lua
- lua/lv-globals.lua
- lv-settings.lua
Options to better **python analysis** lsp configuration with global options. Can be changes by the user on `lv-settings.lua`
```lua
O.python.analysis.type_checking = "off"
O.python.analysis.auto_search_paths = true
O.python.analysis.use_library_code_types = false
```
> ✨  Python analysis options (pyright)

- lua/lv-telescope/init.lua
- lua/plugins.lua
I think this is worth adding as a default. It will significantly speed up telescope
References
https://github.com/nvim-telescope/telescope-fzy-native.nvim
which uses
https://github.com/romgrk/fzy-lua-native
The main highlight is
```
Lines: 100000
Native:
-> Total: 34130
-> Time:  69.418 ms
Original:
-> Total: 34130
-> Time:  835.683 ms
```
> Implement fzy native to speed up telescope

- lua/plugins.lua
In the current version, autopairs filetype specific rules don't work.   
```lua
npairs.add_rules({
-- This rule doesn't work
Rule("(", ")",{"tex", "latex"})
-- don't add a pair if  the previous character is xxx
:with_pair(cond.not_before_regex_check("xxx", 3))
},
-- This rule works
Rule("(", "")
-- don't add a pair if  the previous character is xxx
:with_pair(cond.not_before_regex_check("xxx", 3))
)
```
The gif shows the way the current code is broken.  Rules only work if you don't add a filetype.  
Changing the way LunarVim installs the two together in packer fixes the problem.  
I changed 
```bash
use "kyazdani42/nvim-tree.lua"
``` 
to
```bash
use {"kyazdani42/nvim-tree.lua", opt = true }
```
This is the longest I've ever spent adding two words to a codebase.
> Fix: makes autopairs filetype specific rules work

- lua/lsp/init.lua
This adds the circle as the default prefix for lsp servers not defined in lv-globals such as efm.
It also ads a not to inform users that they can have a prefix per lsp server by defining them in lv-globals
- for virtual text prefix and spacing
- for signs
- for underline
> Add default prefix for lsp settings.

- lua/settings.lua
Apparently both `vim.bo.expandtab = true` and `vim.o.expandtab = true` have some inconsistent behavior in `NVIM v0.5.0-dev+1282-gfbe18d9ca`. See #372 for more information.
This PR reverts back to the vimscript way of setting this variable.
> fix expandtab

- lua/lsp/vue-ls.lua
For some reason, neovim lsp can't seem to detect the binary for `vuels`. So I had to fix it by explicitly specifying where it is located.
> Fix Vue LSP

- utils/installer/install.sh
Previous check uname -a does not work if user has changed kernel.
Use os-release for true operating system identification.
Reference #346
> Use os-release file to check Ubuntu distro

- utils/installer/install.sh
It was not possible to install LunarVim if these programs were already
installed. The check is syntactically incorrect and would always return
non-0 status. The installer would always continue to install packer and
nvim even though they were already installed. This failed with an error:
"fatal: destination path '<PATH>/packer.nvim' already exists and is not
an empty directory."
Correct the syntax error by using test -e to check if the file exists.
> Fix packer and nvim already installed check

- utils/installer/install.sh
The function ```installpiponarch``` does not have the call to ```sudo``` resulting in a error during the installation of LunarVim if the arch-based OS does not have ```pip```  pre-installed
> fix pip install on Arch Linux

- init.lua
- lua/lv-globals.lua
- lua/lv-nvimtree/init.lua
- lua/settings.lua
In `lv-nvimtree`, you have `vim.g.nvim_tree_disable_netrw = 0` set which should keep netrw enabled, but this never actually gets set. There are several issues in the nvim-tree repo with people experiencing the same. The solution: set `nvim_tree_disable_netrw` before the `packadd` in `plugins`. The reason this is important is because netrw doesn't just function as a crappy file manager, it allows you to open external http links with `gf` or open in an external browser with `gx`.
https://github.com/kyazdani42/nvim-tree.lua/issues/354
The first commit fixes this by just adding `nvim_tree_disable_netrw`  to the `lv-globals.lua`  file and sourcing `lv-globals` before `plugins`.
The second commit is my attempt to follow the organizational pattern of the config. I add `nvim_tree_disable_netrw` …
> Enable netrw

- ftplugin/css.vim
- ftplugin/html.vim
- ftplugin/javascript.vim
- ftplugin/javascriptreact.vim
- ftplugin/yaml.vim
If you are editing multiple files at the same time, set will make those options for all buffers, while setlocal will only enable options for that buffer.
> Use setlocal insted of set

- README.md
The numbered list for `Install your own plugins` was all in one line
- Changed it to a proper sequence (added new lines)
- added highlighting (backticks) to file names
- fixed grammar (, instead of .) in pt 2
> README.md: Fix `Install your own plugins` numbered list

- init.lua
- lv-settings.lua
moved the including of lv-settings to above the settings so local settings configured in lv-settings can override the globals that get loaded in settings, 0.relative_number for example
> To fix settings include order

- README.md
Sorry for the bad title, I can't think of a better one.
LunarVim is a great project! However I think the commands offered in the README can be improved:
- Remove unnecessary `sudo` usage
- Improve manual compile instructions (do it in a temporary directory)
- Deleting only `site` directory when troubleshooting (so users don't lose history/swap/etc.)
- `-f` is required for `rm` when deleting plugins since `.git` may contain read only files
> Improve commands in README

- lua/lsp/init.lua
- lv-settings.lua
Document highlighting is a personal preference, like line wrapping, so this option allows it to be configured via lv-settings.lua.
> Add setting to enable/disable document highlighting

- lua/lv-galaxyline/init.lua
It can be difficult to determine if treesitter is functioning in the current buffer. This indicator provides a quick signal to show treesitter status.
> Add treesitter indicator to status line

- lua/lv-telescope/init.lua
The current telescope configuration doesn't appear to actually use the fzy file sorter even though it intends to (override_file_sorter = true).
> Enable the fzy file sorter for telescope

- lua/keymappings.lua
- lua/lv-globals.lua
- lua/settings.lua
* open remote link in browser correctly with gx, not in a tmp file
apparently this is a long standing issue, but [this](https://github.com/vim/vim/issues/4738#issuecomment-845318201) seems to fix this bug. Now `gx` will open remote http links properly in the browser.
> bug fix for netrw's gx command

- lua/keymappings.lua
- lua/lv-autocommands/init.lua
- vimscript/functions.vim
Including the quickfix buffer in the buffer list can lead to surprising circumstances where the quickfix buffer is displayed both in the typical place at the bottom of the UI and in the main window at the same time. Setting `nobuflisted` for quickfix buffers prevents this.
A mapping to toggle the quickfix window is also a relatively ubiquitous need, so this is also included.
> QuickFix quality of life

- README.md
Got these on debian: `rm: cannot remove 'neovim/.deps/build/src/luajit/src/lib_init_dyn.o': Permission denied ...`
> Fix neovim installation cleanup

- lua/lv-which-key/init.lua
This PR changes the which-key binding `<leader>lS` to the new Telescope DynamicFinder (`Telescope lsp_dynamic_workspace_symbols`), fixing https://github.com/ChristianChiarulli/LunarVim/issues/425 as suggested in the issue comments.
> Change Workspace Symbols binding to Telescope DynamicFinder

- lua/lsp/terraform-ls.lua
This PR adds terraform extension to the terraform-ls configuration, since no ls was being attached to the buffer.
> Add file types to terraform language server config

- lua/lsp/go-ls.lua
This PR removes "." from root pattern in the go ls setup.
This was causing nvim to  cwd after opening any `*.go` file in a project package, causing nvimtree to change directory  and making telescope finders unusable as well.
`go.mod` and `.git`  should be enough as project boundaries.
> Fix go root pattern in go ls setup

- lua/keymappings.lua
I realize that nvim-compe key map is missing. it should be in lua/keymappings.lua.
> nvim-compe key map added

- lua/plugins.lua
It looks like `master` is not correctly loading `FTerm`, this is not a major issue because `FTerm` is not used in the base config. However, if people start to dip into `extras` they will get caught by this like I did
> Fix: Correctly require FTerm in plugins.lua

- README.md
- utils/installer/install.sh
I noticed LunarVim didn't have official support for Gentoo, so I modified the installer scripts with the necessary checks (I hope I'm not forgetting anything).
Some info needs to be added to README.md also, didn't intend it to go on this PR though.
> Modifying installer.sh (and README.md) to be suited for Gentoo

- lua/lv-which-key/init.lua
This may be controversial because it changes the functionality from "toggle highlighting forever" to "clear highlighting / current search"
I think the latter is the more natural behaviour, however, feel free to reject this change. There is also the potential to bind the clear search to `<leader>n` to keep it in line with `n/N` keybinds for next/prev search.
> WhichKey: Make <leader>h clear search instead of toggling highlight

- init.lua
- lua/lv-spectre/init.lua
- lua/lv-which-key/init.lua
- lua/plugins.lua
Correctly load the Spectre plugin + add which-key integrations.
I configured the backlash key for Spectre options (leader is the default) as otherwise, key descriptions like "require('spectre.actions').replace_cmd()" are mixed with the which-key mappings (ugly). Also, Spectre options are only available from the buffer it opens.
I also took some time to refactor which-key mappings definitions to explicitly split normal from visual mappings.
IMO the plugin has some flows and could be improved, but it's already a good starting point.
> Fix spectre

- lua/lv-nvimtree/init.lua
- lua/lv-which-key/init.lua
- Add an offset to display NvimTree buffer in barbar.
_It won't work correctly if you enable "vim.g.nvim_tree_quit_on_open"._
- Add which-key support to barbar to enable missing mappings.
> Fix barbar integration with nvim-tree

- utils/vscode_config/keybindings.json
fixed use spacebar in other input(terminal, extensions, etc)
#217 
#256
> vscode use spacebar in other input

- lua/lv-globals.lua
- lua/settings.lua
- lv-settings.lua
Cursorline is another one of those options that some people really like and others really hate. Providing a toggle for it in lv-settings without changing the current default allows those in the latter camp to quickly set their preference.
> Allow cursorline option to be configured by lv-settings

- lua/lv-galaxyline/init.lua
- lv-config.lua
I made two changes.
1. Added suitable galaxyline themes for the colorschemes `gruvbox` and `nvcode`.
2. Added two lines of code to restore cursor position to beam/underline since neovim changes cursor style and won't switch back after quitting.
Hope this is useful. Thanks :)
> galaxyline themes for gruvbox and nvcode, restoring cursor shape

- lua/lv-dashboard/init.lua
This entry allows quick access to the neovim config files from anywhere. I find that I'm typically inspired to make changes to my nvim config when I run into something that irritates/annoys me while working on other projects. Having this dashboard entry allows me to open the relevant file, make the change, and get back to work with minimal context switching.
> Add dashboard entry to search nvim config files

- init.lua
- lua/lv-autopairs/init.lua
- lua/plugins.lua
Fixes issue https://github.com/ChristianChiarulli/LunarVim/issues/563
Autopairs replaced the old style of carriage return bindings with a setup function for compe.  Implemented the new setup.  I also had to disable lazy loading for compe since I could only make the two plugins work together if they are both loaded at start.
> fixes indenting by adding compe setup in autopairs config

- lua/default-config.lua
- lua/plugins.lua
This solves #574
you can enable the plugin by appending the following line to `lv-config.lua` and then running `:PackerSync`
```lua
O.plugin.dap_install.active = true
```
Afterward, while opening a file, you can install new debuggers using:
```
:DIInstall python_dbg
```
For a complete list of supported Debuggers , check [this](https://github.com/Pocco81/DAPInstall.nvim#list-of-debuggers) out
> Adding DAPInstall.nvim

- lua/default-config.lua
- lua/lv-snap/init.lua
- lua/lv-which-key/init.lua
- lua/plugins.lua
Worth testing it first of course, but this is a first pass at adding snap as an optional plugin, if enabled it will use the same bindings as Telescope does, at least for the a subset of Telescopes features. I can follow up with the other features that Snap supports and more, like grepping under cursor, grepping selection, etc.
It works for me locally, but please test.
> Add snap as an optional alternative to telescope

- lua/default-config.lua
Currently there is no default leader_key set, which causes the which-key config to break if 
there is no lv-config.lua file in the users config dir.
> [CONFIG] No default for leader_key.

- ftplugin/c.lua
- lua/default-config.lua
- utils/installer/lv-config.example.lua
This improves the default config for C/C++.
I've also enable cross-file rename, which allows an lsp rename to work across an entire project.
Table insertion is set to never by default, and can be customised by the user.
> [LSP] clang - Better defaults for clangd.

- lua/plugins.lua
We no longer need to use the `lua` branch, it has been [merged](https://github.com/lukas-reineke/indent-blankline.nvim/commit/bbf592143b366e1bd20cffb5e84a9df6dfcc77d2) into `master`
> indent-blankline.nvim lua branch has been merged into master

- ftplugin/python.lua
- lua/lv-galaxyline/init.lua
When using Efm and sumneko_lua in lua
When using efm and pyright in python
also fixed the filetypes in Python ftplugin efm arguments. removed other filetypes and just kept python for python.
> Show all LSP Clients attached to the Buffer in GalaxyLine Bar

- lua/default-config.lua
- lua/settings.lua
Before, the `settings.lua` file was quite messy and was hard to understand. It also used a mixture of `vim.o`, `vim.wo`, `vim.bo`, and `vim.opt`, when everything could just be placed with `vim.opt`.
This (for my slow and crispy computer) had shaved off 14 milliseconds (average of100 takes of all vim.opt `-` average of 100 takes of current). But even if this doesn't make much of a performance difference, it at least makes the `settings.lua` file easier to work with.
ALL SETTINGS WERE KEPT INTACT (mostly)
> Cleaner and Faster `settings.lua` File

- .github/ISSUE_TEMPLATE/general-issue-form.yaml
Fixes [504](https://github.com/ChristianChiarulli/LunarVim/issues/504)
I used GitHub issue form syntax, which I think allows for more structure.
I plan on adding more forms:
- A feature form
- A LSP issue form
Let's first discuss and agree on this one.
> Define a form for general issues

- utils/bin/nv
The path used by default in install.sh is [~/.config/nvim](https://github.com/ChristianChiarulli/LunarVim/blob/0096e0baa93f26097c1ce26a9e0a72bed0c5a468/utils/installer/install.sh#L103)
> Update nv script folder

- ftplugin/c.lua
Improves the auto-format to support C and header files for C and CPP.
> [LSP] clang - Support autoformat for all file-types.

- lua/plugins.lua
LspInstall is currently loaded automatically at start.  This pull request sets it to be lazy loaded.
LspInstall was lazy loaded last week with 'BufRead'.  But this did not work correctly in all cases and was changed to load at start.
Loading with the 'cmd' option seems to work reliably and it's how I've loaded it in my own config for a while.
> lazy load lspinstall

- ftplugin/ruby.lua
You can see this in the [default config](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/solargraph.lua).
> Solargraph uses stdio instead of --stdio

- .github/ISSUE_TEMPLATE/config.yml
Blank issues are still allowed, as all cases aren't potentially covered (we will see in the future)
> Configure the template chooser to include community links.

- lua/default-config.lua
- lua/lv-compe/init.lua
- lua/plugins.lua
Fixed #631 
For activation, you need to add the following line to your `lv-config.lua`
```lua
O.plugin.tabnine.active = true
```
Due to this [issue](https://github.com/tzachar/compe-tabnine#packer-issues), sometimes you might need to do this after `:PackerSync`
```bash
cd ~/.local/share/nvim/site/pack/packer/start/compe-tabnine
./install.sh
```
> Adding tabnine for compe

- lua/default-config.lua
- lua/lv-compe/init.lua
Sets the default directory for the vsnip-snippet to ~/.config/nvim/snippets/.
The directory can be changed via O.vsnip_dir.
> Snippets in config dir

- ftplugin/php.lua
- lua/default-config.lua
- utils/installer/lv-config.example.lua
Added the possibility for basics settings regarding the php-lsp.
Nothing to fancy I think.
Autoformat doesn't seem to work. I left a TODO in utils/installer/lv-config.example.lua.
> Basics for php lsp

- lua/lsp/init.lua
- lua/lsp/ts-fmt-lint.lua
- lua/plugins.lua
This makes CodeAction autofixes working
https://user-images.githubusercontent.com/51096534/124395931-e9493a80-dcd4-11eb-9b19-13cb85963f00.mp4
I changed efm to [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) on js/ts files only for now as it's less bloated than efm and it uses built-in neovim sources to provide out-of-the-box functionality. efm's codeActions also doesn't work.
Also added [nvim-lsp-ts-utils](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils) plugin to get usefull utils like Import all missing imports (exposed as :TSLspImportAll)
> Fix Lint CodeActions + Better dev experience on JS/TS

- lua/default-config.lua
- utils/installer/lv-config.example.lua
This only removes `O.extras` config option since it's no longer used. The extras plugins are activated individualy.
> Remove `extras` Config option since extras plugins are enabled individualy now

- lua/lsp/ts-fmt-lint.lua
`vim.fn.glob("node_modules/.bin/prettier")` returns an empty string if the path does not exist which is a truthy value in lua. The effect is that the path to the global prettier is replaced by the potentially non existent prettier from the project level.
> fixes condition to use local prettier

- lua/settings.lua
I think that remove the bg from Sign Column should make the ui more appealing when `O.transparent_window` option is true
> feat(transparent_window): add SignColumn

- lua/default-config.lua
This switches to absolute line numbers in insert mode and back to relative line numbers when insert mode is left. if `relative_number` is set to `false` line numbers will stay absolute no matter which mode is active.
> switch to absolute line numbers in insert mode

- lua/lv-compe/init.lua
Please refer [https://github.com/windwp/nvim-autopairs#mapping-cr](https://github.com/windwp/nvim-autopairs#mapping-cr) **nvim-compe** section.
If this keymap is preferred, maybe we can remove the map set in [autopairs](https://github.com/ChristianChiarulli/LunarVim/blob/bd9296c4e86b9223cce9ee3dd0d04c3f9e7cc370/lua/lv-autopairs/init.lua).
> Ensure the keymap set in lua/lv-autopairs/init.lua works as expected.

- ftplugin/c.lua
- ftplugin/go.lua
- ftplugin/javascript.lua
- ftplugin/javascriptreact.lua
- ftplugin/json.lua
- ftplugin/lua.lua
- ftplugin/python.lua
- ftplugin/ruby.lua
- ftplugin/rust.lua
- ftplugin/sh.lua
- ftplugin/typescript.lua
- ftplugin/typescriptreact.lua
- ftplugin/zig.lua
- ftplugin/zsh.lua
- init.lua
- lua/default-config.lua
- lua/plugins.lua
- utils/installer/lv-config.example.lua
* Get rid of all unnecessary complexity for setting up efm for formatting
* No need for efm server since it's no going to be used for formatting
(some languages need it for lint, e.g python, if those cases the efm
server was left and not completely removed)
*  Add `forma_on_save` option and remove all unnecessary format options for specific languages
1. Users can toggle format_on_save for all languages, and not have an option for every single language as it was before.
2. We don't need to worry about setting up formatters with efm anymore (which can be a pain to do)
3. Simplify the config, and get rid of a ton of unnecessary settings for specific languages. We don't have to parse x formatter that an user want to efm or whatever. Just having the formatter you want installed and in your …
> (feat) use neoformat as the defalt format option

- ftplugin/vue.lua
More specific root_dir configuration for most (typical) vue projects. The "." does not work in certain cases.
> Fix vue lsp root_dir configuration

- ftplugin/cs.lua
Add csharp language server (omnisharp) setup for .cs filetype. 
Requires csharp language server (":LspInstall csharp"). First time loading of omnisharp takes few seconds (2-10 sec).
> Add csharp language server (omnisharp) setup for cs filetype

- lua/default-config.lua
- lua/lv-treesitter/init.lua
- lua/plugins.lua
This adds three plugins that use treesitters parsing to provide smarter text objects
[ts_textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects) lets you define text objects for things like functions and classes
[ts_textsubjects](https://github.com/RRethy/nvim-treesitter-textsubjects.git) defines a smart text object that selects a semantic block around the cursor
[ts_hintobjects](https://github.com/mfussenegger/nvim-ts-hint-textobject) uses easymotion style hint labeling to show all the surrounding semantic blocks, letting you choose the correct one
I have also added which-key entries for all the above
> Add Treesitter extensions for better textobjects

- lua/lv-which-key/init.lua
Just changed the telescope project keybinding to `<leader>P` instead of `<leader>p`
> telescope project and packer had the same keybinding

- utils/installer/lv-config.example.lua
Trying to open/edit a PHP file throws an error:
```
Error detected while processing /Users/xxx/.config/nvim/ftplugin/php.lua:
E5113: Error while calling lua chunk: /Users/xxx/.config/nvim/ftplugin/php.lua:16: attempt to index field 'format' (a nil value)
Error detected while processing FileType Autocommands for "*":
Error while processing file: /Users/xxx/.config/nvim/ftplugin/php.lua
/Users/joanlopez/.config/nvim/ftplugin/php.lua:16: attempt to index field 'format' (a nil value)
Press ENTER or type command to continue
```
> Fix error in ftplugin/php.lua when opening a PHP file.

- lua/lv-which-key/init.lua
IMHO Symbols outline deserves a top level keybinding, same as `vimtree` explorer. On different scopes, both plugins help navigate code fast and efficiently.
> add top level keybinding for symbols outline.

- lua/plugins.lua
all the credit goes to @rebuilt,
when you run the `<leader>P`, you will no longer get the following error:
> fix telescope project issue

- lua/lv-neoformat/init.lua
Fixes #746
When we have 
```lua
O.format_on_save = false
```
inside `lv-config.lua`
we get the following error, because there is no `autoformat` group to be removed
> we don't need to remove autoformat group when there is none

- lua/lv-utils/init.lua
Fixes #750 
@ChristianChiarulli  we can either do this or remove the `<C-q>` [binding](https://github.com/ChristianChiarulli/LunarVim/blob/master/lua/keymappings.lua#L86).
> add missing QuickFixToggle() function

- .gitignore
I'm requesting the addition of a .gitignored folder for user configuration.  This can be useful if you want to split up your lv-config.lua into smaller files.  
Additionally, it compliments the management strategy I created here:
https://github.com/ChristianChiarulli/LunarVim/issues/758
This makes it so you don't see the git submodule every time you run 'git status'.  
I'm flexible on the name of the folder if you want to suggest something else.
> Add a git-ignored folder for users to store their personal configurations

- lua/lv-floatterm/init.lua
- lua/lv-utils/init.lua
Fixes #759 
While using `Lazygit` inside `FTerm`, `esc` key will act as quit instead of going to normal mode
> fix lazygit esc issue

- lua/default-config.lua
- lua/settings.lua
by setting
```lua
O.clipboard = ""
```
inside your `lv-config.lua` you can disable the neovim systemwide clipboard usage
> for context: somebody asked on discord how to disable it
> you can disable clipboard

- lua/default-config.lua
- lua/settings.lua
A neat little feature that I find quite useful
> 	Minimal number of screen lines to keep above and below the cursor.
This will make some context visible around where you are working.  If
you set it to a very large value (999) the cursor line will always be
in the middle of the window (except at the start or end of the file or
when long lines wrap).
> Scrolloff option in lv-config

- lua/lv-barbar/init.lua
Better keybindings for tab/buffer navigation.
This is what I have been using personally since NVcode.
The reasons to merge,
1. Consistency (Vi binding)
<C-h> <C-l> for window navigation
<S-h> <S-l> for tab/buffer navigation
2. Resolve conflicts with VimWiki
Tab and S-Tab would not work for VImWiki users.
By default, VimWiki mapped those to navigate between its wiki-links.
3. S-Tab is like ESC
I can deal with Tab key but no S-Tab
> chore: update keybinding for tab navigation

- lua/lv-which-key/init.lua
This is a nice default to have which doesn't require any additional plugins or configuration but simply replaces the built-in extremely basic spelling hint list with the which-key interface.
To test, simply:
```
:PackerCompile
set spell -- enable spell checking
z= -- press this on a misspelled word that is underlined
```
I haven't included the following,  but this is a nice addition to enable spell checking by default for certain filetypes:
```
vim.cmd [[autocmd FileType text,latex,tex,md,markdown setlocal spell]]
```
Alternatively, having a keybinding to toggle spell checking could be an option?
> Use which-key for spelling hints

- lua/plugins.lua
If lazyload event for FTerm is set to `BufRead`, you cannot call terminal or lazygit from the initial dashboard. By setting the lazyload event to the same as Dashboard, this issue is corrected.
> FTerm starts on same event as Dashboard

- README.md
- utils/installer/lv-config.example-no-ts.lua
- utils/installer/lv-config.example.lua
Some options had moved under `O.default_options`, also some plugins has been removed from LunarVim
> Readme update in accordance with default_plugin changes

- README.md
- utils/installer/install.sh
this make its possible to use a branch other then master while installing lunarvim, good for testing the clean install in rolling
```
LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)
```
> adding branch support in the installer.sh

- lua/lv-which-key/init.lua
- lua/settings.lua
Fix for leader key not being mapped before some plugins are configured.
Fixes #(issue)
#853
> [SETTINGS] Ensure <Leader> is mapped before plugin configs are sourced.

- lua/default-config.lua
- lua/lsp/ts-fmt-lint.lua
Fixes a regression where ESLint was removed. It is now possible to specify in `lv-config` :
```lua
O.lang.tsserver.linter = 'eslint' --or 'eslint_d'
```
Fixes #860 
Please check the relevant options.
Tested against javascript like types with `eslint` and `eslint_d` and it respects .eslintrc
> Add eslint and eslint_d to efm and remove prettier from efm

- lua/lsp/emmet-ls.lua
Enables emmet-ls support for vue filetype.
Please check the relevant options.
By using emmet-ls successfully on a Vue project.
> [Feature] Enable emmet-ls on vue filetype

- ftplugin/tex.lua
- lua/default-config.lua
- utils/installer/lv-config.example-no-ts.lua
- utils/installer/lv-config.example.lua
This is a repeat PR of #840 but in the new rolling set out.
I find myself using autosave (save &compile on focus change) on latex a lot as it compiles stuff in the background as I do something else, a lot of people i know have something similar within their IDEs, I believe it is an option that gets used by a lot of people, some hate it though so I thought it might be a good idea to give the option.
For ignore errors, sometimes latex gives errors the user may not care about and this results in them being bothered every time they compile.
There is another latex PR #861 , this doesn't interfere with it so no problem there.
Please check the relevant options.
I ran it with my configs and with default configs.
> Vimtex/Latex : Added autosave on focus loss option and list of errors to be ignored.

- lua/default-config.lua
- lua/lv-which-key/config.lua
This PR attempts to solve an issue with rustfmt not working. Tested on my own machine(MacBook Pro) on a rust crate created with `cargo init --bin`, 
I think it's a sensible assumption to assume that people will write code for the 2018 edition of rust.
Example output when running on a repository with async: 
- Created a repo with: `cargo init --bin`
- Indented a line too much.
- Run command `:FormatWrite` or `:w`
> Bugfix: Fixed edition issue with rustfmt.

- lua/lv-galaxyline/init.lua
This PR prevents this from appearing when having multiple buffers with lua files open.
Also fixed the filetypes index check.
> Prevent duplicate LSP clients from appearing in galaxyline

- lua/keymappings.lua
The line I removed overrides terminal apps' default ESC behavior.
Lazygit should work as expected now.
- leader gg -> commit -> Esc
> Remove t-keymap which overrides term-app's <ESC>

- lua/settings.lua
the tildes are not transparent and are shown for example in nvimtree.
you cant make them transparent, but we can remove them.
no trailing whitespaces are generated.
> remove tilde from EndOfBuffer in transparent mode

- README.md
- utils/installer/lv-config.example-no-ts.lua
- utils/installer/lv-config.example.lua
fixing my own mistake
:facepalm: instead of `goimport` it should be `goimports`
Fixes #884
- Read the `README.md`
> goimports instead of goimport

- utils/installer/lv-config.example.lua
Completely solves the issue stated in #881.
In #881 I forgot to edit the values in the example config as well. This PR fixes that. 
Installed LunarVim from scratch.
Created a repo with: cargo init --bin
Indented a line too much.
Run command :FormatWrite or :w
> Added --edition parameter to lv-config examples.

- ftplugin/python.lua
- ftplugin/sh.lua
- ftplugin/zsh.lua
- lua/lsp/ts-fmt-lint.lua
efm-langserver configuration(s) need to have root_dir configured. If root_dir is not configured, relative linters and formatters are not found, e.g. `./node_modules/.bin/prettier`
> [Bugfix] Set root_dir for efm-langserver configuration

- lua/plugins.lua
There was a typo in plugins.lua
Fixes #(issue)
Fixed the typo to reference vim-rooter.
> [Doc]: comment typo

- lua/plugins.lua
We didn't respect the `O.user_plugins` therefore no extra plugin would be installed
- Add an extra plugin
- Run `:PackerSync`
- Nothing happens
> we should install O.user_plugins

- README.md
Clicking on `Made with Lua` icon jumps to a 404 link <https://github.com/ChristianChiarulli/LunarVim/blob/rolling> (should at least be tree/rolling).
Click on `Made with Lua` icon.
> [Doc] fix: clicking made with lua icon opens a deadlink

- README.md
- utils/installer/install.sh
The installation process is sometimes stuck with 
`Ok to remove[y/N]?` message, this PR attempts to fix that
as described in updated `Readme.md` you can run the installer script with
`--overwrite` flag to remove leftover from previous installations.
> Fix the installation stuck on Ok to remove

- lua/core/compe.lua
- lua/default-config.lua
This PR fixes a typo in the setting name `vsnip_dir`.
> Fix vsnip_dir typo

- lua/core/which-key.lua
The current O.user_which_key allows user to add top-level mappings, but its difficult to e.g. change a single item in a sub-menu..
Thats because the for() loop which iterates over each k,v pair replaces the root of each key entirely.
Simply giving the user-defined mappings to wk.register() overrides things which much finer control.
> [WHICH-KEY] Use wk.register() to handle the overrides.

- ftplugin/c.lua
- ftplugin/cmake.lua
- ftplugin/dart.lua
- ftplugin/go.lua
- ftplugin/json.lua
- ftplugin/lua.lua
- ftplugin/php.lua
- ftplugin/python.lua
- ftplugin/ruby.lua
- ftplugin/rust.lua
- ftplugin/sh.lua
- ftplugin/tex.lua
- ftplugin/yaml.lua
- ftplugin/zsh.lua
- lua/core/formatter.lua
- lua/default-config.lua
- lua/lsp/tsserver-ls.lua
We need to have some default formatters for each lang
Also, there was a bug that wouldn't set the formatter config.
- open a lua file
- run `:Format`
- run `:lua print(vim.inspect(O.formatters.filetype['lua']))`
> Added default formatters

- ftplugin/tex.lua
- lua/default-config.lua
- utils/installer/lv-config.example.lua
This PR makes the latex lsp more flexible and easier to configure. Almost every setting can be made in lv-config.lua. With those the user can choose which build arguments and which preview options are to be used by lunarvim.
My hope is that this is a desired PR in the light of #638.
Disclaimer: This is a copy of #671, which has been closed by me. I've messed up big time I think. The main difference is that this PR is now based on rolling and has a cleaner commit history. I'm still learning sorry for the inconvenience.
Please check the relevant options.
- Bug fix (non-breaking change which fixes an issue)
- Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- I have tested these changes with opening .tex and .bib files and checking for linting …
> User configurable latex lsp#2

- ftplugin/c.lua
fix a typo in ftplugin/c.lua that leads to E5108: Error executing lua /home/qvieth/.config/nvim/ftplugin/cpp.lua:4: attempt to index field 'c' (a nil value)  while using Formatter in C file
> [Bugfix] index field typo in ftplugin/c.lua

- lua/default-config.lua
- lua/lsp/tsserver-ls.lua
Sorry, https://github.com/ChristianChiarulli/LunarVim/pull/921 is broken.
`vim.api.nvim_buf_get_name(0)` should call on every format. I think any `vim.api.nvim_buf_get_name(0)` for formatter put in config files(default-config or lv-config) should be careful, as it's only run once on config file loaded.
Also fixed filename should be escaped with `vim.fn.fnameescape`.
> Fix tsserver formatter not working

- ftplugin/css.lua
- lua/default-config.lua
Adds formatter for css and any filetype symlinked to that filetype, eg. scss and less. I would like to continue add more formatters, specifically via prettier. I noticed there is now a decent amount of duplicated code between formatters so any suggestion on improving that pattern would be appreciated :)
Formatted both `.css` and `.scss` files.
> Add css (and pre-processors) support

- ftplugin/rust.lua
rust projects don't have a `Carrust.toml` file at the root. it's `Cargo.toml`
Edit:
Maybe this should go straight to `master` branch as rust projects are simply broken due to this ?
> Fix rust root pattern

- ftplugin/elixir.lua
- lua/default-config.lua
Added default formatter for Elixir language Default is `mix format`
Tested with Elixir Lsp installed
> [Feature]: added default elixir formatter

- lua/core/dashboard.lua
There is a hard coded `showtabline` value in the `dashboard.lua`, which overrides the user defined (`lv-config.lua`) `O.default_options.showtabline` value. This PR fixes the issue.
Set e.g. `O.default_options.showtabline = 0` in your `lv-config.lua`. Before fix the Dashboard overrides the value, but after the fix the user defined value is honored.
> [Bugfix] Use user defined value when setting showtabline on BufLeave

- lua/plugins.lua
The 'after' keyword has no effect.  Since the dependencies are autoloaded, the 'after' setting is not being applied.  Packer can only manage plugins in the 'opt' folder with the 'after' keyword.
The 'after' keyword was needed when we were lazy loading compe and tree-sitter but now it does nothing.  
As described here https://github.com/wbthomason/packer.nvim/issues/435
The listing in the packer_compiled file shows an empty table for 'after'
```lua
["nvim-autopairs"] = {
config = { "\27LJ\2\n.\0\0\3\0\2\0\0046\0\0\0'\2\1\0B\0\2\1K\0\1\0\19core.autopairs\frequire\0" },
load_after = {},
loaded = true,
needs_bufread = false,
path = "/home/nelson/.local/share/nvim/site/pack/packer/opt/nvim-autopairs"
},
```
Opened lua file to make sure autopairs works and that indenting works as well. 
- ...
> Autopairs event trigger

- lua/lang/clang.lua
clang-format find the nearest .clang-format in the files' parent
directories.
This enables clang-format to choose the correct formatting options in e.g. monolithic projects containing different libraries with different styles.
> [LANG] c/cpp: formatter - run clang-format from CWD of file.

- lua/lang/lua.lua
- lua/lang/php.lua
- lua/lang/sh.lua
- lua/lang/terraform.lua
Prefix formatter.nvim's tempfile with ".formatter" so they should be hidden by default. This was added to any lang that mentions `stdin = false`.
> [Feature] Hide formatter.nvim tempfiles

- .github/workflows/format.yaml
- utils/installer/install_stylua.sh
Add an installer for Stylua mainly to be used for the CI as to avoid downloading an entire rust toolchain.
Only tested locally
```bash
bash ./utils/install/install_stylua.sh
```
> [Feature] Add an installer for Stylua

- lua/lang/elixir.lua
on-attach was missing for elixir and keybindings like `gd` or 'shift-k` did not work, this PR fixes that
Fixes #(issue)
Tested with elixir-lsp installed and now keybindigs are working perfect for elixir
> [Bugfix]: fixed elixir on-attach

- lua/core/which-key.lua
Adds support for telsecope theme selection with preview
running `<leader>sp` shows this
> :tada: telescope supports colorscheme preview

- .luacheckrc
Lucheck needs to be [configured](https://github.com/neovim/neovim/blob/master/.luacheckrc) to understand LV code
- Run
```bash
luarocks install luacheck
cd ~/.config/nvim
luacheck .
```
> configure luacheck to better undersant LV code

- lua/lsp/ts-fmt-lint.lua
- Bugfix: A $ was missing in front of `{INPUT}` so eslint linting was not working
- Feature: Now warnings are correctly recognised and colorized for Eslint !
To test just open a javascript like file with eslint error/warnings (configuration and level can be done in `.eslintrc.js`)
> [Bugfix/Feature]: diagnostics level for eslint and $ missing

- lua/lang/cs.lua
nvim-lspconfig has fixed the OmniSharp (csharp) LPS root_dir default configuration. See PR #1084
https://github.com/neovim/nvim-lspconfig/pull/1084
The corresponding configuration can now be removed from LunarVim.
Note! Requires updated nvim-lspconfig, i.e. `:PackerUpdate` or similar is mandatory.
Change has been tested on few .NET Core projects with and without solution (.sln) file.
> [Bugfix] Remove OmniSharp LSP root_dir config after nvim-lspconfig PR #1084

- lua/core/telescope.lua
Until we have a better alternative like [this](https://github.com/caojoshua/telescope.nvim/pull/1) or [this](https://github.com/nvim-telescope/telescope.nvim/pull/914).
Fixes #812
before:
after:
> [Feature] Better path_display default for telescope

- README.md
- init.lua
- lua/default-config.lua
- lua/keymappings.lua
- lua/lv-utils/init.lua
- lua/settings.lua
- utils/installer/lv-config.example-no-ts.lua
- utils/installer/lv-config.example.lua
- Add the ability to override all the default keymappings that aren't prefixed with `<leader>`
`O.keys.normal_mode = { {'[d', '<PageUp>'}, {']d', '<PageDown>'}, }`
- Add the ability to augment the existing keymappings
`require("lv-utils").add_keymap_insert_mode({ silent = true }, { { "<C-s>", ":w<cr>" } })`
Fixes #(issue)
#960
All the keybindings are still working, and overrides from `lv-config` seem to be working as expected.
> [Refactor] Make default keybindings configurable

- init.lua
- lua/plugin-loader.lua
- lua/plugins.lua
This splits the plugin configuration from the loading logic.
The plugins.lua file would now contain only the plugin's configurations.
The plugin-loader.lua file contains the logic for loading plugins + handling packer's initialization.
I went for an object-oriented approach for the package-loader as it provides a clear interface.
I think it's better to have an object with clear responsibilities that can be injected as a dependency instead of doing require("mymodule").myfunction everywhere in the code. IMO the code would be more structured and easier to maintain in the future.
Also, it will be possible to have a state and pass the package-loader to other parts of the application (as I said dependency injection). For example, we could inject it into the which-key module (probably at the …
> Split plugin loading logic from the configuration

- lua/lsp/ts-fmt-lint.lua
- lua/lsp/tsserver-ls.lua
1. Use nvim-lspconfig default root_dir configuration for tsserver
2. Fix ts-fmt-lint setup
- prioritize local linter over global linter
- fix `lintFormats` typo
- only eslint_d supports `--fix-to-stdout`. Set formatter (i.e. "fix") only if eslint_d is used.
With a Typescript project using
- global eslint_d
- local eslint_d
- global eslint
- local eslint
> [Bugfix] Fix tsserver lsp setup. Fix ts-fmt-lint setup

- lua/default-config.lua
- lua/lsp/init.lua
This PR addresses issue #895 it the simplest way possible. It may be
preferable to implement a more complex solution to disable individual
keybinds or allow the user to override them in some other way.
I decided to submit this as a PR first because I didn't want to try
making larger changes without feedback.
I toggle the config option and it does enable and disable the default keybinds.
> [Feature]: Add setting to enable/disable the default lsp keybinds

- lua/core/nvimtree.lua
- lua/plugins.lua
as @williamgoulois mentioned the latest `nvim-tree` toggle doesn't work on dashboard
Fixes #1018
open nvim without any files
while on dashboard run `<leader>e`
run the following while on dashboard:
```vim
:lua print(vim.inspect(vim.loop.fs_stat(vim.fn.fnamemodify(vim.fn.bufname(), ':p'))))
```
as the [code](https://github.com/kyazdani42/nvim-tree.lua/blob/0a13676f30230f4f049b2efaccc5e0936067b475/lua/nvim-tree.lua) shows, because the `stat.type == directory` the `M.find_file` function returns without actually showing the `nvim-tree`
but since we have `follow=1` the `M.toggle()` function already follows a file and if not a file then shows a directory: 
```lua
function M.toggle()
if view.win_open() then
view.close()
else
if vim.g.nvim_tree_follow == 1 then
M.find_file(true)
end
if not …
```
> [Bugfix] Update nvim-tree to the latest version without the dasboard issue

- lua/keymappings.lua
Terminal mode navigation keys are now working
Fixes #1029 
- `:new term://bash`
- `<c-j>` or `<c-k>`
> [Bugix] Terminal navigation keys

- lua/core/linter.lua
The autolint group was renamed, but nothing else was refactored
https://github.com/ChristianChiarulli/LunarVim/commit/d02265175f33fb1586e5e1f080e0730c8642a961#diff-a377666d446cc8c4dac647dfb20d14cc8d2bc4b1c1152e9d6f3639a0a45e7378L6
> Fix autolint group definition

- lua/lang/ruby.lua
The [sorbet lsp server is included](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#sorbet) in nvim-lspconfig. This adds support for this in addition to the solargraph support that was already there.
I tested it on my project that uses sorbet, and it worked with no other setup:
> [Feature]: Add sorbet lsp for ruby

- README.md
- lua/default-config.lua
- lua/lsp/init.lua
- utils/installer/lv-config.example-no-ts.lua
- utils/installer/lv-config.example.lua
Allow the user to set a custom on_attach callback for lspconfig. 
This also fixes a bug where `lspconfig.common_on_attach` is undefined when `O.lsp.document_highlight` is set to `false`, but it was still called regardless.
Add this to `lv-config.lua` and verify that it's working
```lua
O.lsp.on_attach_callback = function(client, bufnr)
-- ref: https://github.com/neovim/nvim-lspconfig#keybindings-and-completion
local function buf_set_option(...)
vim.api.nvim_buf_set_option(bufnr, ...)
end
--Enable completion triggered by <c-x><c-o>
buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")
end
```
> [Feature] Make common_on_attach configurable

- lua/core/bufferline.lua
shift x should remove the previous char and not close the buffer. 
Fixes #1053
> remove remapping of shift - x 

- lua/core/bufferline.lua
- lua/core/telescope.lua
- lua/core/which-key.lua
- utils/installer/lv-config.example.lua
Move leader keybindings into the whichkey configuration file
Fixes #(issue)
When resetting keybindings via whichkey.reset()  or `lvim.builtin.which_key.mappings = nil`,  some keybindings are still available because they are defined in other configuration files.   
Check keybindings to make sure they still work
> Move leader keybinding into the whichkey config

- README.md
- init.lua
- lua/core/autocmds.lua
- lua/core/dashboard.lua
- lua/default-config.lua
- lua/lsp/init.lua
- lua/lv-utils/init.lua
- utils/installer/lv-config.example-no-ts.lua
- utils/installer/lv-config.example.lua
- Rename `lvim.autocommands` -> `lvim.autocommands.custom_group`. THis makkes it clearer that we're expecting a table and not a single entry. And it also allows us to expose `lvim.autocommands` to the user to allow for modification.
- Add `core.autocmds` to allow for evaluating the augroups _after_ `lvim.autocommands.custom_groups` has been updated.
Fix ignored user autocommands
Uncomment the example lines at the `lv-config[-examle].lua` to see the effect, or copy these lines manually
```lua
lvim.autocommands.custom_groups = {
{ "BufWinEnter", "*.lua", "setlocal ts=8 sw=8" },
}
```
> Fix ignored user autocommands

- lua/core/galaxyline.lua
Display "Tab size: " instead of "Spaces: " if indenting with tabs.
In the galaxyline, LunarVim displays a text like "Spaces: _n_", where _n_ is the amount of spaces the user indents with, extracted from `shiftwidth`.
However, if a user indents with tabs, LunarVim still displays "Spaces: _n_", which can be very misleading.
This fix additionally checks the `expandtab` option and changes sets the text to "Tab size: _n_" if `expandtab` is `false`.
Just like the check on `shiftwidth`, I check the option for the current buffer.
Fixes #(issue)
Alternatingly set different values for the following options and confirm the expected behavior:
`set tabstop=4`
`set shiftwidth=4`
`set expandtab` / `set noexpandtab`
> [Bugfix] Show correct indentation settings in galaxyline

- lua/core/telescope.lua
There is no `defaults.find_command` option for telescope setup. Its inclusion in `telescope.lua` would confuse users that expect the default behavior of telescope to change using this option. So we remove the option.
- Remove the option from `telescope.lua`
- Check that telescope command returns the same results: `Telescope find_file`
> [Refactor] Remove defaults.find_command from telescope

- lua/lv-utils/init.lua
With `format_on_save` enabled, the user is required to save twice (tested on go and cpp) as the formatting is applied postwrite.
This change ensures formatting is done prewrite.
Verify only one save is required to keep the foramtting changes
> [Bugfix] Ensures formatting is done prewrite

- lua/settings.lua
Fix comment typos in settings.lua
> - [Doc]: comment typos

- lua/spacegray/highlights.lua
I use `WarningMsg` highlight group in my config and saw that it is set to orange in `spacegray` colorsheme
> [Bugfix]: WarningMsg color is red instead of orange

- lua/lv-utils/init.lua
Currently, lv-config.lua does not get autoformatted. Changes the autocommand from `BufWritePost` to `BufWritePre`
Open lv-config.lua
set `lvim.format_on_save = true`
Save lv-config.lua.  Autoformat should be enabled
> BufWritePre enables format on save for lv-config.lua

- lua/default-config.lua
lvim would complain on opening `.tex` files as there were no `lang` fields for them. This adds the required formatter, linter and lsp path for `.tex` files
Verify that `texlab` attaches on opening a `.tex` file and that formatting and linting works.
> [Bugfix] Add `lvim.lang` fields for `.tex` files

- lua/core/terminal.lua
In your lv-config do:
```lua
lvim.builtin.terminal.execs = {{"lazygit", "gg", "LazyGit"}, {"gdb", "tg", "GNU Debugger"}} 
```
To add any list of executable shortcuts to be launch by toggleterm. Table structure is
```
{{exec_path, keymap, name}}
```
You can also do:
```lua
lvim.builtin.terminal.execs[#lvim.builtin.terminal.execs+1] = {"gdb", "tg", "GNU Debugger"}
```
To append an executable.
> modified terminal to be able to add any executable

- init.lua
- lua/lsp/init.lua
I noticed an issue where you could no longer set `lvim.lsp.default_keybinds = false`. This is because the lsp keybindings were set up on the first require of that module. Which happens before reading the user lv-config.lua. I simply wrapped it in a function instead and called it after keymappings.
- Set `lvim.lsp.default_keybinds = false` in `~/.config/lvim/lv-config.lua`.
- Open a file where an LSP would run.
- Press tab in normal mode on something you expect to have signature help.
- Nothing happens because the binding no longer exist.
> [Bugfix] Wrap lsp default_keybindings in function instead of load on 1st require

- lua/core/autocmds.lua
- lua/core/compe.lua
Currently, hitting TAB triggers autocomplete in all files.  In simple text files hitting TAB should insert a tab character.  
This pr allows a user to specify filetypes in which they don't want Compe mappings.
By default this pr excludes markdown and txt files.  
The list of filetypes can be specified with
``` 
lvim.builtin.compe.exclude_filetypes = { "md", "markdown", "mdown", "mkd", "mkdn", "mdwn", "text", "txt" },
```
Fixes #(issue)
https://github.com/ChristianChiarulli/LunarVim/issues/1121
Editing markdown files and making sure a tab character is inserted. 
Editing other files to make sure compe behavior remains the same
> Conditionally enable TAB to trigger completion based on filetype. Disable completion for simple text files

- lua/plugins.lua
* Just adds package.json and package-lock.json for the root patterns of
vim-rooter
* The other ones are the default patterns, see `:help g:rooter_patterns`
> include `package-lock.json` & `package.json` in root patterns

- lua/core/galaxyline.lua
Resolve null-ls tag in galaxyline
Open lunarvim and see that galaxyline resolves null-ls to the linter it's actually using.
> feat: resolve null-ls tag in galaxyline

- ftplugin/asm.lua
- ftplugin/beancount.lua
- ftplugin/crystal.lua
- ftplugin/d.lua
- ftplugin/perl.lua
- ftplugin/sql.lua
- lua/core/galaxyline.lua
- lua/default-config.lua
- lua/lsp/null-ls.lua
1. null ls formatter name is different from the actual command
for example `clang_format` is the `null-ls` formatter but `clang-format` is the actual command so we need to check for the existence of the command, not the formatter
2. show formatter inside `galaxyline`, otherwise, we wouldn't know if `null-ls` is activated or not 😅 
3. a couple of langs are supported natively by `null-ls` so I've added them
1. Save this as `Program.cs`
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceProcess;
using System.Text;
using System.Threading.Tasks;
namespace OWINTest.Service
{
static class Program
{
/// <summary>
/// The main entry point for the application.
/// </summary>
static void Main()
{
ServiceBase[] ServicesToRun;
ServicesToRun = new ServiceBase[] …
```
> null-ls formatter name is different from its command

- lua/default-config.lua
Vue.js language server provider name vetur -> vuels
Fixes #1148 
Open a Vue.js project and vuels activates without issues
> fix: correct vue lsp provider name

- README.md
There is only 1 way of updating LunarVim now.
> Just removing the old way of updating LunarVim

- lua/lsp/null-ls.lua
Description
When `eslint_d` is used as **linter** (i.e. lsp **diagnostics**), null-ls `eslint` configuration should be used with `eslint_d` command/executable.
Fixes issue #1101 
More info:
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/9b8458bd1648e84169a7e8638091ba15c2f20fc0/doc/BUILTINS.md#eslint
Tested with 
- eslint as linter (local)
- eslint_d as linter (global and local)
> fix: use null-ls eslint diagnostics config with eslint_d exe linter

- init.lua
Setting up auto commands from `lv-config` didn't work. Default autocommands (`core.autocmds`) is loaded after `lv-config` is loaded, so the `lvim.autocommands.custom_groups` has never been assigned. I change the order to load the module `core.autocmds` to fix this issue.
- Add some autocmd on `lv-config` file.
```lua
lvim.autocommands.custom_groups = {
{ "ColorScheme", "*", "hi Visual guibg=#383d45" },
}
```
- Check the visual color is changed
> [Bugfix]: autocmd custom_groups not loaded

- utils/installer/install.sh
When a user has a non-permissive umask, the execute or even read permissions may be missing on /usr/local/bin/lvim after the sudo cp step
Fixes #(issue)
- Check logs
- ...
> Bugfix: Protect against a strict umask

- ftplugin/gdscript.lua
- lua/default-config.lua
Close #358 by adding LSP support for gdscript, **syntax highlighting is already supported by tree-sitter.**
LSP config reference: https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#gdscript
One small problem about using `nc` as executable is that **some** version of `nc` doesn't work.
In my testing the GNU `nc` installed with homebrew failed to run, but BSD `nc` bundled with macOs work just fine, also `ncat` from `nmap` work fine too.
Furthermore, windows user *may* want to use their own version of `nc` binary replacement.
To use custom `nc`, small hack in `lv-config.lua`:
```lua
lvim.lang.gdscript.lsp.setup.cmd[1] = "ncat"
```
or just fix path..
Fixes
#358
With Godot Engine opened, LspInfo show that it's attached and code completion is working.
> [Feature]: Add gdscript LSP support

- lua/lsp/init.lua
- lua/utils/init.lua
Clean up `formatting_handler`
Formatting still works with `stylua`
> cleanup formatting handler

- init.lua
- lua/keymappings.lua
- lua/utils/init.lua
- lua/utils/keymap.lua
Move key mapping helpers to utils/keymap.
Rework some logic which allows to remove some LOC.
Define mapping modes in a constant table.
Load user key maps on top of the default ones instead of merging them and excluding one or the other. This means that it's now possible to just provide additional mappings while keeping the defaults.
I could also replace all `nvim_set_keymap` calls with the new helpers.
Fix #1140 
I added Keymap:L18 ` print(mode, #mapping)`, modified `lvim.keys.n` and it worked as expected.
> [Refactor] Define keymapppings helpers in utils.keymap

- lua/default-config.lua
- lua/lsp/handlers.lua
- Add diagnostics' source name and to help distinguish where it's coming from.
- Add diagonstics' code to make it easier for the user to turn it off if the provider supports that.
`setup_handlers()` from lsp wasn't getting called also.
> feat: add diagnostics source name

- lua/core/galaxyline.lua
- lua/lsp/null-ls.lua
- lua/utils/init.lua
Adds a utility function to get the registered `null-ls` providers by the file type. 
This helps clean up the logic in `galaxyline` quite a bit, and it's useful for debugging purposes.
`null-ls` providers are still showing up correctly in `galaxyline`
> feat: get null-ls registered providers by filetype

- lua/keymappings.lua
With the previous commit, the following way to set keybindings broke
```lua
lvim.leader = "\\"
```
This pr add parenthesis to fix the logic
```
vim.g.mapleader = (lvim.leader == "space" and " ") or lvim.leader
```
> Wraps the logic in parenthesis so it works correctly

- lua/lsp/null-ls.lua
It gets confusing to show the `null-ls` provided name instead of the actual command name
> show the actual command

- utils/bin/lvim
Currently, the nvim process is launched as a child of the shell process. In my case, this made the tmux think that the running process is a shell script rather than the nvim. This led to the broken tmux-nvim integration, wrong tmux window title and etc. Also, I believe that this update has many other user cases.
`exec` shell command replaces the shell process with the given command.
I've updated the shell script locally and tested that the LunarVim itself is working fine and that the tmux determines the process correctly.
> [Feature] Add exec to lvim binary

- lua/core/bufferline.lua
- lua/core/compe.lua
Make compe and bufferline keymaps overridable.
> [Feature] Make keymaps of bufferline and compe configurable

- lua/core/autocmds.lua
Fix comment typos in autocmds.lua
> [Doc]: comment typos

- lua/core/bufferline.lua
- lua/core/compe.lua
- lua/keymappings.lua
- lua/utils/keymap.lua
- utils/installer/config.example-no-ts.lua
- utils/installer/config.example.lua
Convert our keymappings to match which-key style.
This will allow us to migrate all our keymappings to which key once we will be able to do it.
It is also more explicit for the user in case he wants to replace a specific keymap.
! It will break user-defined keymappings in config.lua as the format has changed.
`:map`, `:nmap` ...
> [Refactor] Adopt which key mapping style

- README.md
- init.lua
- lua/core/bufferline.lua
- lua/core/compe.lua
- lua/core/which-key.lua
- lua/default-config.lua
- lua/keymappings.lua
- lua/lsp/init.lua
- lua/utils/init.lua
- utils/installer/config.example-no-ts.lua
- utils/installer/config.example.lua
A refactor of the core logic for keybindings
- Allow editing any default mapping _individually_ with autocomplete support in `~/.config/lvim/config.lua`
- Add a new key binding to view all the defaults `<leader>Lk`
Fixes #1194 and partially #490
See the examples in the README
> [Refactor] Allow editing default keymaps

- lua/lsp/handlers.lua
On an LSP I use that isn't a part of lunarvim, the source is nil, so after editing a line, I got the error that line 31 had a nil value when it wasn't expected.
`Error executing vim.schedule lua callback: /Users/will/.local/share/lunarvim/lvim/lua/lsp/handlers.lua:31: bad argument #1 to 'find' (string expected, got nil)`
I edited the same line after making this change and I did not get the error. Now that LSP reports correctly, and my other LSP that has a source is still reporting with it's source name and a colon
> [Bugfix]: Fix lsp reporting when v.source is nil

- lua/core/nvimtree.lua
Add a new possible behavior to nvimtree :
pseudo-code:
```lua
if (isOpened) then
if (isFocused) then
close()
else
focus()
end
else
open()
end
```
Fixes #980 
Tested with multiple splits, windows.
- Set in your lv-config.lua
```lua
lvim.builtin.which_key.mappings.e = {"<cmd>lua require'core.nvimtree'.focus_or_close()<CR>", "Explorer"}
```
- Now `<leader>e` will use this behavior instead of toggle
> [Feature]: Add possibility to focus nvimtree instead of toggle

- README.md
- lua/keymappings.lua
Add capability to set keymap with custom opt. eg.
```lua
lvim.keys.insert_mode["jj"] = "<ESC>", -- use generic_opts
lvim.keys.insert_mode["<C-j>"] = {'pumvisible() ? "\\<C-n>" : "\\<C-j>"', { expr = true, noremap = true }}, -- use user defined opt
lvim.keys.insert_mode["<C-k>"] = {'pumvisible() ? "\\<C-p>" : "\\<C-k>"', { expr = true, noremap = true }}, -- use user defined opt
```
Fixes https://github.com/ChristianChiarulli/LunarVim/issues/1140#issuecomment-889728879
- Add `lvim.keys.insert_mode["<C-j>"] = {'pumvisible() ? "\\<C-n>" : "\\<C-j>"', { expr = true, noremap = true }`
- Press control+j on insert mode when completion box appear. Navigation works
> [Feature]: Keymap with custom opts

- lua/core/nvimtree.lua
Add a check to see if the user has defined their own `g.nvim_tree_bindings` before defining the defaults.
* Add if guard to `nvimtree.lua`
* Run `lvim` without a user defined `g.nvim_tree_bindings`. Default bindings work as expected.
* Run `lvim` with a user defined `g.nvim_tree_bindings` in `~/.config/lvim/lv-config.lua`. User's bindings work as expected.
> [Bugfix] Allow users to define their own nvim-tree bindings

- lua/core/nvimtree.lua
- lua/core/rooter.lua
- lua/default-config.lua
- lua/lsp/init.lua
- lua/lsp/null-ls.lua
- lua/plugins.lua
- lua/utils/init.lua
- Enable querying the language-server for the `root_dir`
- Use `root_dir` to set the current working-directory (CWD) and enable it by default
- Make vim-rooter configurable and add an option to disable it
Inspired by "ahmedkhalf/lsp-rooter.nvim"
1- Disable vim-rooter
```lua
lvim.builtin.rooter.active = false
```
2- Open any file with LSP support and see the "smart_cwd" in action :)
> feat: add lvim.lsp.smart_cwd

- lua/lsp/null-ls.lua
- Use more stateful comments regarding `root_dir` detection logic.
- Remove redundant `if ts_clien then` since it's guaranteed after 
passing the first condition.
1. Add this to your `config.lua` 
`lvim.builtin.rooter.active = false`
2. Check that CWD is still updating with LSP
> chore: minor cleanup to root_dir comments

- lua/lsp/init.lua
As many filetypes have default formatters configuration with empty exe value, LunarVim needs to check if exe has been set before overriding the LSP clients formatter.
With e.g. `cs` filetype (i.e. C#), the csharp LSP client (OmniSharp) can do rudamentary formatting, but with default configuration the formatter is disabled because of 
Tested with C# project (OmniSharp LSP) without changing the `lvim.lang.cs.formatters` default configuration AND then later setting `clang_format` as formatter exe value. Without exe value, omnisharp formatting capability is not overridden with empty formatter, but with `clang_format` exe value, the clan_format will override omnisharp's formatting capability.
> [Bugfix]: Don't override formatter with empty exe

- lua/core/gitsigns.lua
as mentioned [here](https://github.com/lewis6991/gitsigns.nvim/commit/27e1e95e1aa8d4ec0aabbf5148013f58a1bc4b40)
> use_decoration_api has been removed from gitsigns

- ftplugin/ps1.lua
- lua/default-config.lua
Adds support for PowerShell language server (powershell_es) configuration
1. Installed Microsoft PowerShell: https://github.com/PowerShell/PowerShell/releases
2. Installed PowerShellEditorServices: https://github.com/PowerShell/PowerShellEditorServices/releases
3. Added configuration e.g. `lvim.lang.ps1.lsp.setup.bundle_path = "/path/to/PowerShellEditorServices"`
4. Opened a PowerShell `.ps1` file and saw powershell_es language server activated.
> [Feature] Add PowerShell language server support

- lua/core/galaxyline.lua
- lua/utils/init.lua
We don't need `util.list_extend_unique` after #1240
> chore: remove now-redundant utility function

- lua/core/info.lua
- lua/core/which-key.lua
- lua/lsp/init.lua
- lua/lsp/null-ls.lua
- lua/utils/init.lua
Add an info panel with some useful status reports for the current lunarvim configuration. 
It operates per files, and tries to give suggestions about setting up linters and formatters. 
Todos:
Fixes #1187 
```lua
-- Add this to your `config.lua` 
lvim.builtin.which_key.mappings["Li"] = {
"<cmd>lua package.loaded['core.info']=nil; require('core.info').toggle_display(vim.bo.filetype)<cr>",
"Toggle LunarVim Info",
}
```
> Add LunarVim info panel (Experimental)

- lua/core/dashboard.lua
I've added a space after the plug unicode icon cause it doe'snt appear fully in LunarVim for me. So though would be better.
Pretty useless PR. xD
I reran lunarvim now it works
> [Refactor]:Added space after plug icon

- lua/lsp/init.lua
Don't change the CWD if we get a "/" as the project directory result from the language-server.
> avoid using smart_cwd if root_dir is not found

- lua/core/commands.lua
- lua/settings.lua
Add command `:LvimInfo` to toggle/show LunarVim info panel (in addition to `<leader>Li`). 
- Open a file(type) for which you want to check LSP, formatter and/or linter info.
- Run command `:LvimInfo`
> [Feature] Add LvimInfo command

- lua/utils/init.lua
We should source the keybindings before loading the plugins, so that we don't overwrite any new ones.
Some plugins like "aserowy/tmux.nvim" uses C-hjkl for movement, and these should take effect now.
> fix: do not overwrite plugins bindings in reload

- lua/core/which-key.lua
With `<cmd>let @/=""<CR>` its not possible to use `n`,`N` or stuff like `gcn` anymore because the last search is overwritten. With `:nohlsearch` this is not the case. The search keeps working only the highlight is removed.
Fixes an issue I didn't file
Tested manually after applying the change (using `<leader>h` after doing a search.
> [Bugfix]: change 'no highlight' behavior

- lua/core/nvimtree.lua
Updates the bufferline when pressing q in nvimtree. Previous behavior would not update the bufferline.
I pressed q
> [Bugfix]: Fix nvimtree quit to update bufferline

- lua/core/info.lua
Improve highlight matching of formatting and linting providers.
> [Bugfix] LvimInfo highlight match fix

- lua/keymappings.lua
Add the lvim.keys.command_mode table for configuring key bindings for
the command mode. Include bindings for <C-j> and <C-k> similar to the
ones available for insert mode.
For example, using:
```lua
local cmd_opts = { noremap=true, expr=true, silent=false }
lvim.keys.command_mode["<Up>"]    = { [[pumvisible() ? "\<Left>"  : "\<Up>"   ]], cmd_opts }
lvim.keys.command_mode["<Down>"]  = { [[pumvisible() ? "\<Right>" : "\<Down>" ]], cmd_opts }
lvim.keys.command_mode["<Left>"]  = { [[pumvisible() ? "\<Up>"    : "\<Left>" ]], cmd_opts }
lvim.keys.command_mode["<Right>"] = { [[pumvisible() ? "\<Down>"  : "\<Right>"]], cmd_opts }
```
in the `config.lua` file with the patch produces the same result as:
```lua
local cmd_opts = { noremap=true, expr=true, silent=false }
vim.api.nvim_set_keymap("c", …
```
> [Feature] Add command mode key mapping table

- lua/core/telescope.lua
- lua/core/which-key.lua
Add two simple functions that allow opening and grepping LunarVim Files from anywhere.
Use `<leader>L` to see the new options.
> feat: use telescope to quickly open lunarvim files

- ftplugin/elixir.lua
Fixes #1308 
in elixir files instead of `/* stuff */` we'll get `# stuff`
> Fix commentstring for elixir files

- lua/core/galaxyline.lua
- lua/core/status_colors.lua
Add the new config variable "lvim.builtin.galaxyline.show_mode" to
control if the mode name should be shown in the galaxyline. The option
defaults to false to preserve the current behavior.
Tested with `lvim.builtin.galaxyline.show_mode = false`, `lvim.builtin.galaxyline.show_mode = true` and without `lvim.builtin.galaxyline.show_mode` in the `config.lua`
> [Feature] Add a new option to show the mode name in galaxyline

- lua/lsp/null-ls/formatters.lua
- lua/lsp/null-ls/linters.lua
Support [has been added](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/106) to null-ls for extending builtins args :tada: 
``` lua
lvim.lang.sh.formatters = {
{
exe = "shfmt",
args = { "-i", "2", "-ci" },
},
}
```
> [Bugfix] Support extending null builtin args

- .pre-commit-config.yaml
- lua/core/compe.lua
- lua/core/dap.lua
- lua/core/gitsigns.lua
- lua/core/telescope.lua
- lua/core/terminal.lua
- lua/core/which-key.lua
- lua/plugins.lua
It's unncessary to check if a plugin is loaded during `config` part in Packer, since it "Specifies code to run after this plugin is loaded."
See: `:h packer.use()`
Also remove the redundant `augroup` logic for linter and formatter since each file is only sourced ones.
Fixes #1003
Run on a clean install
```shell
rm -rf ~/.local/share/nvim ~/.config/nvim/plugin/*
nvim --headless +'autocmd User PackerComplete sleep 100m | qall' +PackerInstall
nvim --headless +'autocmd User PackerComplete sleep 100m | qall' +PackerSync
nvim +PackerCompile
```
> [Refactor] Clean-up redundant module-load checks

- .github/workflows/install.yaml
- utils/bin/install-latest-neovim
- utils/installer/install-neovim-from-release
Fix the slow CI workflow by using a neovim binary directly from the github release page instead of installing all the build dependencies. 
We'll test it directly and then install any missing deps individually.
> Fix slow CI by installing a neovim binary directly

- init.lua
- lua/default-config.lua
- utils/installer/config.example-no-ts.lua
- utils/installer/config.example.lua
This feature allows user to pass a custom table to null_ls setup function.
I have tested this with `root_dir` overwrite.
Example config: 
```
lvim.lsp.null_ls.setup.root_dir = require("lspconfig").util.root_pattern("Makefile", ".git", "node_modules")
```
With this I can see null_ls root set to the `app` folder when opening a file in a project with structure like this
```
repo/
├── .git/
└── app/
├── node_modules/
├── App.js
├── package.json
└── yarn.lock
```
Eslint and babel sometimes have weird interactions, where if you're running eslint or eslint_d from repo root and not `app` folder (see project structure above), you might run into errors where eslint can't find your babel config because it either looks for it from cwd and upwards or only cwd.
Making sure `null_ls` root is set …
> [Feature] Expose null ls setup to user config

- lua/core/compe.lua
Fixes #(issue)
Emmet completion does not work correctly.  An expression like `nav>ul>li` should produce
```html
<nav>
<ul>
<li></li>
</ul>
</nav>
```
Instead, it just inserts a tab character.  
This pr adds a check to see if emmet_ls is active.  Enables emmet completion if emmet language server is active.   
```lua
elseif is_emmet_active() then
return vim.fn["compe#complete"]()
```
To set up emmet-ls  add this to your plugins.  
```lua
lvim.plugins ={
{
"aca/emmet-ls",
config = function()
local lspconfig = require("lspconfig")
local configs = require("lspconfig/configs")
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true …
```
> Check if emmet is active.  Enable emmet completion if emmet language server is active

- .github/workflows/format.yaml
- .github/workflows/lint.yaml
- .pre-commit-config.yaml
`jdtls` is causing the `CI` to throw errors, we should ignore that file till we find the root cause
> [Bugfix] ignore jdtls to fix `CI`

- lua/lsp/null-ls/services.lua
- lua/lsp/utils.lua
Remove vim-rooter dependency when configuring null-ls local providers
Install prettier locally and test that it still works with yaml files for example.
> [Refactor]: Remove vim-rooter dependency

- lua/lsp/null-ls/services.lua
There shouldn't be an error log entry when the provider hasn't be checked if it's on path.
> fix: remove wrongful log entry from null-ls setup

- ftdetect/nix.lua
- ftplugin/nix.lua
- lua/default-config.lua
Fixes #1345
support syntax highlighting and LS for `*.nix` files
```sh
cargo install rnix-lsp  # to get LS
nix-env -i -f https://github.com/nix-community/rnix-lsp/archive/master.tar.gz # i don't know why 🤣 
nix-env -iA nixpkgs.nixfmt # if you want to use nixfmt formatter
```
to get treesitter support:
```vim
:TSInstall nix
```
and to use `nixfmt` formatter, add the following to your `config.lua`
```lua
lvim.lang.nix.formatters = { { exe = "nixfmt" } }
```
> [Feature] nix support

- lua/core/dashboard.lua
Rename `Settings` to `Configuration` in dashboard. To decrease confusion, for new comers.
> rename settings to configuration in dashboard

- lua/default-config.lua
- lua/lsp/null-ls/formatters.lua
- lua/lsp/null-ls/linters.lua
Fixes two issues
1. linters for `vim` files was set to `{""} ` in `default-config.lua` which is wrong.
2. we didn't check for the existence of `lvim.lang[filetype]` before using it, which cause this error
opened a sample `.vim` file and a sample `.rmd` file without any errors
> [Bugfix] fix formatter/linter nil issue

- lua/core/nvimtree.lua
- lua/core/which-key.lua
This adds buffer local autocmds to setup the bufferline offset which is
important since currently the bufferline doesn't get updated when someone does
`NvimTreeOpen` and co. Also important when someone does `:q`.
This also refactor the changedir function.
I opened and closed nvimtree
> [Refactor]: consistent update of bufferline offset with nvim-tree

- lua/core/project.lua
Adds the `show_hidden` option to show hidden files in project module telescope.
By adding the option to my config.lua
> [Feature]: Add show_hidden option to project module

- init.lua
- utils/bin/lvim
This also simplifies the way to invoke LunarVim to just be:
`nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua"`
Fixes #1352
Add this to test the rtp variable more easily
```lua
print("-- rtp list: ")
local rtp_list = vim.opt.rtp:get()
local user_rtp_list = {}
for _, path in pairs(rtp_list) do
if vim.startswith(path, "/home") and not path:match(".*packer.*") then
table.insert(user_rtp_list, path)
print(vim.inspect(path))
end
end
print("-- pack list: ")
local pack_list = vim.opt.packpath:get()
local user_pack_list = {}
for _, path in pairs(pack_list) do
if vim.startswith(path, "/home") and not path:match(".*packer.*") then
table.insert(user_pack_list, path)
print(vim.inspect(path))
end
end
```
You can now start LunarVim by just using `nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua"` :)
> fix: set runtime directories correctly

- lua/core/dashboard.lua
- lua/core/project.lua
Don't overwrite dashboard config from the project setup function. Also, allow the rest of the settings to be configurable.
It was always setting the second slot in the dashboard to be "Recent Projects", that is not the case anymore.
> [fix]: don't overwrite dashboard config

- utils/installer/config.example-no-ts.lua
One sample config fixed call to telescope project. Another sample config got outdated instruction, this commit is updating that one too.
> fix telescope.project call in sample config (without ts)

- lua/core/which-key.lua
Add a simple git diff with prev header
Fixes #1363
open a file and use `<leader>gd` to see diff with `HEAD~1`
> use `<leader>gd` to see git diff with previous head

- lua/lsp/peek.lua
Set the correct cursor in peek definition window
Fixes #1419 
Open Lunarvim and run `gp` on a sample item to show preview, observe that the cursor is in the correct position
> Set correct cursor in the preview window

- lua/config/defaults.lua
Fix tailwindcss address bcz of [this commit](https://github.com/kabouzeid/nvim-lspinstall/commit/bd3adbb94f07ee12f7a721ec45a94e7825c32c66#diff-2f2bb4dfdb18304474c7e8e159b5d96ba5dacca10502f99c8c93e92959ed6f9b)
open a sample file that uses tailwindcss and observer that it works!
> [Hotfix] update tailwindcss cmd path to match lspinstall

- utils/installer/install.sh
During installation, this error aries.
```
Would you like to check lunarvim's NodeJS dependencies?
[y]es or [n]o (default: no) :
Would you like to check lunarvim's Python dependencies?
[y]es or [n]o (default: no) :
Would you like to check lunarvim's Rust dependencies?
[y]es or [n]o (default: no) :
--------------------------------------------------------------------------------
Backing up old LunarVim configuration
cp: cannot stat '/home/user/.config/lvim/*': No such file or directory
```
The * should outside the quotes in `cp -R "$dir/*" "$dir.bak/."`
FYI, https://stackoverflow.com/questions/34254164/what-is-cp-cannot-stat-error-in-unix-i-get-this-error-when-trying-to-copy-thin/51239548
Reinstalling LunarVim. It worked.
> [Bugfix] Fix cp cannot stat error during installation

- init.lua
Fixes #1442
- Run command `set rtp?` and `set packpath?`
- Results shows that */after paths indeed comes after paths without.
- Testing on a user plugin "vimtex" now loads correctly.
> [Bug]: fix runtime path order

- lua/core/which-key.lua
Adds ability to switch back to the previous buffer (like alt+tab in windows). Which-key command is `<leader> -> b -> b`
https://user-images.githubusercontent.com/5767281/131635300-ea41deb7-3af2-4ccc-829c-57f62d913da6.mp4
No need for testing, it's just a new which-key command.
> [Feature]: Add new which-key command for switching to the last buffer

- lua/core/lualine/components.lua
If the file has no buffer type, just don't show anything in the lsp section of lualine
right now it shows the table address
just open a file using `lvim test`
> [BUGFIX] don't show table address in lualine

- lua/plugins.lua
Load nvim_comment's setup from module `core.comment`
Try overriding some nvim_comment configs via `lvim.builtin.comment` and it works
For example
```
lvim.builtin.comment.line_mapping = "<leader>cl"
lvim.builtin.comment.hook = function()
require("ts_context_commentstring.internal").update_commentstring()
end
```
> [Bugfix]: load nvim_comment setup from core module

- lua/lsp/handlers.lua
when showing diagnostics in a floating window, trim lines
Fixes #1480 
- add `lvim.lsp.diagnostics.virtual_text = false` to your `config.lua`
- try viewing a diagnostics using `gl`
> [Bugfix] string cannot contain newlines error while showing diagnostics

- ftplugin/dockerfile.lua
- lua/config/defaults.lua
[Screen Recording 2021-09-06 at 11.04.40.mov.zip](https://github.com/LunarVim/LunarVim/files/7113232/Screen.Recording.2021-09-06.at.11.04.40.mov.zip)
When adding a builtin null-ls linter or formatter to docker, they wont get applied. 
Reproduction:
```lua
lvim.lang.docker.linters = { { exe = "hadolint" } }
```
The output of:
```
:LvimInfo
```
is empty
and the dockerfile is not getting linted by hadolint
This behaviour is from  https://github.com/LunarVim/LunarVim/blob/9eeb4f23da3967c1b01e26853163b47f5dcbdc2e/lua/lsp/init.lua#L122
where we set up null-ls with vim filetype, not Lvim global object and
its 'lang' keys.
Therefore, inside this function https://github.com/LunarVim/LunarVim/blob/9eeb4f23da3967c1b01e26853163b47f5dcbdc2e/lua/lsp/null-ls/linters.lua#L65
, for example, lvim lang …
> [Bugfix]: use correct filetype name for docker

- lua/core/lualine/components.lua
…nstead of table
There was a weird situation that caused msg to be boolean instead of table in lualine
> Fix lualine error while opening js files

- lua/lsp/handlers.lua
in neovim 0.6 diagnostics didn't show up in some lang servers
which would get fixed by this
> Show correct inline diagnostics in neovim 0.6

- utils/installer/uninstall.sh
The uninstaller still had the old path set.  
This updates the path to `~/.local/bin`
> Correct path of uninstall script.

- lua/core/lualine/components.lua
I noticed the treesitter symbol in the statusline is always visible, even when the current buffer has an unsupported filetype. While taking a look at the existing code, I saw the logic for toggling the icon already exists, but apparently it doesn’t work. This is a quick one liner to fix it. 
Opened a bunch of buffers with different filetypes and the treesitter symbol is either visible or hidden, depending on filetype. Seems to work fine, at least on my end. But please take a look and decide for yourself.
> Show treesitter icon only with supported filetype

- lua/plugins.lua
For new installs, configuration will fail for cmp because `require('cmp')` fails. This configures `cmp` immediately after install only if it is not already configured.
Make a new install, check that cmp is configured after `PackerSync` by doing `:lua print(vim.inspect(lvim.builtin.cmp))`
Or checkout `rolling` before `cmp` was introduced, do a `PackerSync` then checkout `rolling` with the latest changes and `PackerSync` yet again.
> [Bugfix] Fix loading cmp config after Packer install

- .luacheckrc
- init.lua
- lua/bootstrap.lua
- lua/config/defaults.lua
- lua/config/init.lua
- lua/config/settings.lua
- lua/core/dashboard.lua
- lua/core/project.lua
- lua/core/telescope.lua
- lua/core/terminal.lua
- lua/core/which-key.lua
- lua/lsp/init.lua
- lua/plugin-loader.lua
- lua/utils/init.lua
- tests/bootstrap_spec.lua
Remove most of the hard-coded paths that can lead to trouble on other platforms. 
NOTE: We are not able to `require` any modules before adjusting the `&rtp`. So any utility functions that are to be used need to be manually defined in `init.lua`.
TODO: 
[ ] make it work on the CI
[ ] fix `runtimepath` for windows, possible use it unmodified
It should start as normal.
> refactor: use more flexible paths

- lua/lsp/init.lua
While we heavily depend on nvim-cmp for completion with lsp, it should not block other capabilities of the lsp.
Given a use case when user tries to unload or opt for an alternative to nvim-cmp-lsp, the line of code that I fixed will return basic capabilities instead of nothing at all (no capabilities for ls)
> [Bugfix] common capabilities returning nothing if no cmp_nvim_lsp

- README.md
Previous versions of LunarVim had the bin located in `/usr/local/bin/lvim`.
Since the new one is at `.local/bin/lvim`, if $PATH has the previous bin location before the new one, new installations on systems that had already LunarVim installed in the past, will fail to work.
Hence, the old one should be removed.
> [Doc] Update README.md to delete old bin

- lua/plugins.lua
Lualine has breaking changes in its configuration. 
See this [PR](https://github.com/shadmansaleh/lualine.nvim/pull/24#event-5300370888)
This will break LunarVim's and users' lualine config. 
Therefore, pinning Lualine's [the latest commit before the PR](https://github.com/shadmansaleh/lualine.nvim/commit/62bfe80fb6e0cd51cec6fc9df9e1768f7d37d299)
> fix(lualine): pin version to avoid breaking config

- lua/lsp/peek.lua
Noevim 0.6 has a different signature, so we need to support both in order for peek functions to work
> [Feature] Make peek function work in neovim head and 0.5

- README.md
- lua/bootstrap.lua
- lua/core/which-key.lua
- lua/plugin-loader.lua
- lua/utils/init.lua
- utils/installer/install.sh
- utils/installer/install_bin.sh
- Added `LvimCacheReset` which can be used to remove any files
responsible for caching the startup process, e.g. those used by Packer and Impatient
- Added `utils/install/install_bin.sh` to make it easier to update the lvim binary
Fixes #1542 #1555
Set `lvim.log.level = "debug"`
- start lvim with `lvim +LvimCacheReset`
- run `:LvimCacheReset`
> fix: more robust reloading

- lua/config/defaults.lua
For some reasons this field is missing from the default configuration. Therefore, when accessing this key inside lsp handlers, it will return nil. For now we are lucky that there are some internal handling within the lsp that convert nil to false or disable the feature. However, this pull request propose that we define a default value for this configuration  
Concern: I dont know where and how to update the documentation (if there is any)
> [Fix] missing default configuration for update_in_insert

- lua/bootstrap.lua
- lua/core/dashboard.lua
Display LunarVim version on dashboard only when a git tag is found.
This is a temporary fix until we come up with a better way to retrieve the latest version.
> fix(dashboard): hide version when no tag found

- lua/core/autopairs.lua
When pressing `<cr>` in popupmenu in tex files parentheses were put after function name, while curly brackets should be used.
`lvim.builtin.autopairs` is extended with new settings, to be used in `nvim-autopairs.completion.cmp` `setup` function
Related to #1257
- open a tex file
- make sure you use LSP and texlab
- press enter when a latex function is selected in popupmenu
- now you'll see curly brackets appear after function name
> [Bugfix]: latex completion: insert `{` instead of `(` when completing

- lua/core/cmp.lua
This allows users to change the options of the complete action' mapped to `<CR>` for cmp.
For example, I prefer it not to `select`, so I would add `lvim.builtin.cmp.confirm_opts.select = false` to my `config.lua`
This also make it so that if there is a snippet currently in place, it completes the current completion and then jumps instead of falling back to inserting a newline.
- Add `lvim.builtin.cmp.confirm_opts.select = false` to `config.lua`, enter a snippet and press `<CR>`
> [Feature] Allow cmp confirm options to be configured and jump after confirm if available

- lua/lsp/handlers.lua
Set a max width of 120 to the `gl` floating window, so users can see it properly
Fixes #1587
> [Bugfix] Wrap the `gl` floating window diagnostics

- lua/config/defaults.lua
- lua/lsp/init.lua
The goto definition didn't properly work in lunarvim
Fixes #1603
for example go to init.lua over at `init` part, in this line
```lua
require("bootstrap"):init()
```
and run `gd`, that should move you to the definition in `bootrap.lua`
> Fix the lua goto definition bug and add better common capabilities

- lua/bootstrap.lua
- og_install.ps1
- utils/bin/lvim.ps1
- utils/installer/install.ps1
- utils/installer/uninstall.ps1
This pull request adds a `install.ps1` for an easy installation on Windows, an `uninstall.ps1` for removing the lunarvim folder and adds a usage description in `README.md`.
This is basically a conversion from bash to powershell. To work on windows however two lua scripts are changed in the installation process.
- ~/.local/share/lunarvim/lvim/lua/default-config.lua
- ~/.local/share/lunarvim/lvim/init.lua
On both these files the string `os.getenv "HOME"` is replaced with `os.getenv "HOMEDRIVE" .. os.getenv "HOMEPATH"` because on windows a `HOME` environment variable does not exist.
Due to the lack of onboard package management of windows `winget` is used for installing dependencies. If `winget` is not installed the script stops but tells the user the reason.
Fixes #804 
- Powershell 5.1
- …
> feat: add installation script for Windows

- lua/core/gitsigns.lua
Gitsigns has deprecated `watch_index` in favor of `watch_gitdir`
in this commit:
https://github.com/lewis6991/gitsigns.nvim/commit/489fe088c4bc7efa12ddcc47bcef915863e3b753
> watch_index is deprecated, use watch_gitdir instead

- lua/core/telescope.lua
Adjust the menu height for `find_lunarvim_files()` that got too short after a regression in Telescope.
> fix: adjust layout after a regression in telescope

- lua/core/nvimtree.lua
- lua/onedarker/LSP.lua
Not all of the nvim-tree settings has been migrated to the `setup` syntax
> fix: use the new nvim-tree syntax

- lua/onedarker/diff.lua
- lua/onedarker/init.lua
- lua/onedarker/palette.lua
This PR adds highlight colors to the `Diff*` highlight groups and makes diff. Significantly improves readability of diff output over the default scheme.
The colors are taken from [navarasu/onedark.nvim](https://github.com/navarasu/onedark.nvim)
Fixes #1576 
The colors are subjective. Diff can be tested using
```
lvim -d <file 1> <file 2?
```
> [Bugfix]: Add `Diff*` colors to onedarker

- lua/config/defaults.lua
- lua/core/terminal.lua
When I try to open log file by pressing `<leader>Lld`, nothing happens.
I found it was caused by this line:
https://github.com/LunarVim/LunarVim/blob/238bbf18ac4e35152be06736c75e94a81e3382e8/lua/config/defaults.lua#L23
`lvim.log.viewer.cmd` is not executable in this case. Use `less` instead of `lnav` will solve it
> fix: can't open lvim log file cause by `lvim.log.viewer.cmd`

- lua/core/dap.lua
Defining signs for `DapBreakpointRejected` and `DapStopped`. These would earlier fallback to the defaults and as a result were not formatted well on the default theme.
This has been tested on DAP and the `lldb-vscode` adapter.
> [Feature]: Add signs for DAP

- utils/installer/install.sh
`install.sh` doesn't work properly. It always link local lvim regardless of the `ARGS_LOCAL` value. 
This PR fixes the if-else condition to correctly check `ARGS_LOCAL`.
- Uninstall lvim 
- Run the installer
Uninstall lvim
```
$ rm -rf ~/.local/share/lunarvim
$ sudo rm /usr/local/bin/lvim
$ rm ~/.local/bin/lvim
$ rm -rf ~/.local/share/applications/lvim.desktop
```
Run the installer
```
$ ./utils/installer/install.sh
```
> fix(installer): fix ARGS_LOCAL condition

- lua/core/terminal.lua
- lua/core/which-key.lua
Add missing lsp.log entry in `log_viewer` which was always defaulting to the default log.
Each one of these should open a different file
- `<Leader>Lld`
- `<Leader>Lll`
- `<Leader>Lln`
> fix: add missing lsp.log entry in log_viewer

- lua/lsp/manager.lua
because we are using `is_overridden` in here:
```lua
if lsp_utils.is_client_active(server_name) or is_overridden(server_name) then
```
we need to make sure it returns true if the lang server is actually overriden
> fix: return correctly for overridden lang servers

- README.md
- lua/config/init.lua
`lvim.lang.FOO.lsp` is no longer supported after #1584.
You can either use `:NlspConfig` for most of the settings you might need, or override the setup by adding an entry to `lvim.lsp.override = { "FOO" }`.
You should see a warning if you have any `lvim.lang.FOO.lsp` settings in your `config.lua`.
> fix: add deprecation notice for lvim.lang.foo.lsp

- lua/lsp/providers/jsonls.lua
better json schema defaults
Fixes #1673
> feat: better default json schemas

- lua/lsp/config.lua
the character used for `virtual_text` causes random issues, just use the default one
Fixes #1609
> fix: the virtual_text charachter causes issues

- lua/lsp/config.lua
- lua/lsp/null-ls/init.lua
A few month ago PR #1323 was merged into rolling. It allowed users to pass a custom table to null-ls setup function. A few days ago PR #1584 removed that feature.
In particular these lines:
https://github.com/LunarVim/LunarVim/commit/d01ba08eaec1640ac2d038893525b3ba0af25813#diff-064818389bf764a41f5910117a4eecd09ac7e0f2a7f34189854cfd7003021363L161
https://github.com/LunarVim/LunarVim/commit/d01ba08eaec1640ac2d038893525b3ba0af25813#diff-064818389bf764a41f5910117a4eecd09ac7e0f2a7f34189854cfd7003021363R117
To me this seems like an accident since the documentation ([example config](https://github.com/LunarVim/LunarVim/blob/rolling/utils/installer/config.example.lua#L85-L99)) has not been updated to accommodate for the feature removal, so I am submitting this PR to fix that mistake.
I have …
> [Bugfix] Allow user to pass table to null-ls setup function

- lua/lsp/config.lua
- lua/lsp/init.lua
This PR makes the lsp buffer keymaps configurable by the user. The mappings are set up in `lvim.lsp.buffer_mappings.normal_mode`. Similarly, `insert_mode` and `visual_mode` mappings are also created but are currently empty. 
This follows from #1651. 
This PR has the changes requested by @kylo252 in #1651. 
Fixes #1494
> [Feature]: User configurable LSP key map

- lua/core/telescope.lua
- lua/core/which-key.lua
- lua/lsp/config.lua
- lua/lsp/init.lua
1. the default prompt for code actions is really ugly, use the one that the telescope provides instead
2. add new auto command to refresh and display code lens actions in supported language servers
which can be disabled using
```lua
lvim.lsp.code_lens_refresh = false
```
the code action would look like this:
and the lens thingies would look like this in rust:
> [Feature] better code action prompt and auto show codelens actions

- lua/lvim/plugins.lua
Fixes deprecation notices, which are still coming in waves.
See: https://github.com/kyazdani42/nvim-tree.lua/issues/759
> fix: pin nvim-tree

- lua/lvim/core/commands.lua
- lua/lvim/core/which-key.lua
- lua/lvim/plugin-loader.lua
- Add `LvimReload` as a command for ease of use
- Update which-key entries
Fixes #1746
- `<leader>Lr` -> reload lunarvim's configuration
- `<leader>pr` -> packer re-comiple
> fix: update which-key bindings for LvimReload

- tests/minimal_lsp.lua
- utils/bin/lvim.ps1
Allow using `minimal_lsp.lua` on Windows
Fixes a problem where args aren't passed when using `lvim.ps1` 
This now works on Windows
```pwsh
nvim -u .\minimal_lsp.lua
```
> feat: add support for using minimal_lsp on windows

- lua/lvim/core/treesitter.lua
- utils/installer/install.sh
There was a regression from https://github.com/LunarVim/LunarVim/pull/1841 causing toggleterm and dashboard to not appear due to PackerSync not running with them enabled.
Fixes #1895
> fix: dashboard now runs on fresh installs

- init.lua
- lua/lvim/config/init.lua
- lua/lvim/core/builtins/init.lua
- lua/lvim/keymappings.lua
Overloading keymappings now works correctly even after reloading.
Fixes #1758
`<leader>Lk` should show that the changes are persistent.
> fix: overloading keymappings now works correctly even after reloading

- lua/lvim/config/init.lua
I only change to use `[ ]` when set modules, otherwise the modules didn't set to nil as they begin with `lvim.core` which can't use dot syntax.
After trying the following code snippet first and find it only output "aaa", I know that this is the right way to set modules.
```lua
for module, _ in pairs(package.loaded) do
if module:match "lvim.core" then
-- print(module)
if nil == package.loaded.module then
print "aaa"
end
if nil == package.loaded[module] then
print "bbb"
end
end
end
```
Take https://github.com/LunarVim/LunarVim/pull/1897 as an example, I can't see the change I made to lualine by `LvimReload` since the `lvim.core.lualine` module didn't reload properly. After apply this commit, I can see the change after executing `LvimReload` immediately.
> fix(reload): set lvim modules to nil correctly

- README.md
- lua/lvim/config/init.lua
- lua/lvim/lsp/null-ls/init.lua
Consolidate configuration styles for linters and formatters
Fixes #1756
- Add this to your `config.lua`
```lua
lvim.lang.c.formatters = {"test"}
```
> refactor: deprecate lvim.lang.FOO

- lua/lvim/lsp/handlers.lua
- lua/lvim/lsp/init.lua
For Neovim nightly builds (versions greater than 0.5.1), every time the LSP server published diagnostics (quite frequently in my case), it would define and re-define a sign, leaving hundreds of cleared highlight groups.
Additionally, because position was being used instead of mapping by name, the highlight groups were incorrect.
This PR fixes both of these problems.
Fixes #1880
Use neovim nightly, open a decently sized document that has a supported and setup LSP.
Make an error that triggers a lot of diagnostic errors (for example an `{` in the middle of a function), then trigger cmp autocomplete and scroll through. This error should no longer occur while using this PR.
> fix(lsp): correct map and prevent highlight leak of diagnostic signs in 0.6

- lua/lvim/config/init.lua
- lua/lvim/keymappings.lua
Prior to this PR:
- A key mapping remains after reloading even after removing the line setting it
- Key mappings were loading using the user's config before being reloaded
- There was no way to easily unmap a default key mapping
After this PR:
- Removing the line setting a key mapping and triggering a reload will unbind that key mapping
- Key mappings are loaded after the user's config is loaded
- Setting a key mapping to false will explicitly unset that binding
Open `config.lua`, set the following and save:
```
lvim.keys = {
normal_mode = {
["<C-b>"] = "<cmd>lua print('hi!')<cr>",
["<A-j"] = false
}
}
```
`:nmap <A-j>` will show that `<A-j>` has been unset
`:nmap <C-b>` will show that `<C-b>` has been set
Set to the following (remove the two normal mode binding lines):
```
lvim.keys = { …
```
> fix(keymap): unset on reload, load correct order, add unset default

- lua/lvim/core/telescope/custom-finders.lua
This sets the git dir and work tree to where lvim is installed. Without this, viewing the
changelog shows the git log for the current working directory.
The previewers don't work, but the commit list shows. The previewers may
need changes to telescope.
Run `lua require('lvim.core.telescope.custom-finders').view_lunarvim_changelog()` in a git
work tree that is not for LunarVim. It will now show the log for LunarVim.
> Bugfix: allow LunarVim changelog to work outside the lvim directory

- lua/lvim/bootstrap.lua
- lua/lvim/config/settings.lua
- lua/lvim/core/log.lua
Use an independent [shadafile](https://neovim.io/doc/user/starting.html#shada-file) from base Neovim.
Fixes mingled jumplists when using both Neovim and LunarVim.
> fix: use an indepdent shadafile from neovim

- lua/lvim/plugin-loader.lua
if you have large number of plugins ( more than 70) running `:PackerSync` wouldn't finish
and gets stuck, this fixes that by forcing at most 50 concurrent git jobs for packer
more info:
https://github.com/wbthomason/packer.nvim/issues/120
> fix: packersync issue when you have large number of plugins

- lua/lvim/config/init.lua
- lua/lvim/core/bufferline.lua
- lua/lvim/core/dashboard.lua
- lua/lvim/core/nvimtree.lua
- lua/lvim/core/which-key.lua
- lua/lvim/keymappings.lua
- `lvim.keys` no longer holds the default values
- only load the default keymaps once
- `lvim.keys` is always loaded after the default values, so it will always take precedence
- configurable which-key registration for `dashboard` and `nvimtree`
Fixes #1548, #1755, 
- These should all be assigned to the *same value* inside the table. They should override each other, so the result will always be `Binoculars`
```lua
lvim.keys.normal_mode["B"] = ":echo 'Banana'<cr>"
lvim.keys.normal_mode["<S-b>"] = ":echo 'Basketball'<cr>"
lvim.keys.normal_mode["<s-b>"] = ":echo 'Binoculars'<cr>"
```
- it's also possible to override NvimTree's binding directly now
```lua
lvim.keys.normal_mode["<space>e"] = ":echo 'hello'<cr>"
```
> refactor: load the default keymaps once

- lua/lvim/core/autocmds.lua
> It's better not to use `vim.fn.resolve` and set it like this:
> 
> ```lua
>   if vim.loop.os_uname().version:match "Windows" then  
>     -- autocmds require forward slashes even on windows
>     user_config_file = user_config_file:gsub("\\", "/")
>   end
> ```
> 
> Otherwise it will cause error as `string.gsub()` has two return values.
> 
> ```
> E5113: Error while calling lua chunk: Vim:E118: Too many arguments for function: resolve
> ```
> fix(windows): remove redundant `resolve` call

- lua/lvim/lsp/manager.lua
- Avoid installing an overridden server. 
- call `lspconfig` directly for overridden servers.
Fixes #1972
This should now work.
```lua
lvim.lsp.automatic_servers_installation = false
vim.list_extend(lvim.lsp.override, { "clangd" })
local opts = {}
require("lvim.lsp.manager").setup("clangd", opts)
```
> fix(lsp): avoid installing an overridden server

- lua/lvim/bootstrap.lua
- lua/lvim/core/cmp.lua
- lua/lvim/plugins.lua
Use lazy-loading to avoid configuration errors during headless installations. 
chore: bump cmp's version
fix: lazy-load cmp's setup
fix: proper order for luasnip setup
Fixes some issues with luasnip's vscode-loader
Passes the CI
> fix: correct order for cmp's setup

- lua/lvim/plugins.lua
It had worked correctly for installing, but not when upgrading.
> fix(cmp): revert broken sequential loading

- lua/lvim/core/autopairs.lua
if next character is a close pair and it doesn't have an open pair in same line, then it will not add a close pair
[More Info](https://github.com/windwp/nvim-autopairs#dont-add-pairs-if-it-already-has-a-close-pair-in-the-same-line)
Fixes #2015
> fix: dont close if next char is a close pair and no pairs in same line

- lua/lvim/bootstrap.lua
- lua/lvim/core/commands.lua
- lua/lvim/core/dashboard.lua
- lua/lvim/core/telescope/custom-finders.lua
- Fix `lvim` version not displaying correctly on Dashboard when on rolling.
- Add `LvimVersion` that calls `get_changelog()`
- some enhancements to `get_changelog()` including copy to clipboard on `<CR>` and a better default previewer.
> fix: more accessible changelog

- ftdetect/fsautocomplete.lua
- lua/lvim/config/supported_languages.lua
This add's support for the language F#. The LSP is called `fsautocomplete` and is available in [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#fsautocomplete) and in [nvm-lsp-install](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/init.lua#L56)
This should be available with `LspInstall`. 
Added the auto command to a clean lvim installation and opened a fsharp project work with. The language type was correctly identified.
> feat: add support for fsharp

- utils/installer/config.example.lua
The example config file has a sample for unmapping a LunarVim key by
setting it to "".  When I tried that, the result was that the key became
a no-op.  If I instead set it to nil, the key returned to default vim
operation.  In particular, I was trying to unmap normal mode L and H.  I
got to nil by searching for how to delete a entry in a dictionary in
lua, but I'm not familiar with lua.
Fixes #(issue)
- Check logs
- ...
> Fix example of unmapping an lvim default

- lua/lvim/core/info.lua
- lua/lvim/lsp/null-ls/code_actions.lua
This PR adds the interface for null-ls code actions config, which has the same interface as formatters & linters.
Support for `:LvimInfo` is also added.
Having the following code in `config.lua`
```lua
local code_actions = require "lvim.lsp.null-ls.code_actions"
code_actions.setup {
{ name = "gitsigns" },
}
```
Then run `:LvimInfo` or `:Telescope lsp_code_actions`.
> feat: null-ls code_actions interface

- lua/lvim/core/telescope.lua
Ignore files in `.git` in `live_grep`.
I think it's a more sane default.
> fix: better default, ignore `.git` in `live_grep`

- init.lua
- lua/lvim/plugin-loader.lua
Change the `colorscheme` without requiring a restart.
Fixes #1862
This should work correctly
```lua
lvim.plugins = {
{"folke/tokyonight.nvim"},
{
"folke/trouble.nvim",
cmd = "TroubleToggle",
},
{"ulwlu/elly.vim"},
}
lvim.colorscheme = "elly"
```
https://user-images.githubusercontent.com/59826753/144629989-0b540d61-facb-4986-bd04-8bfd167c2f67.mp4
> fix: no restart required when changing colorscheme

- lua/lvim/core/nvimtree.lua
Since last update custom nvimtree keymaps stopped working (e.g. `l` to open into folder)
This PR moves them under `lvim.builtin.nvimtree.setup.view.mappings.list`, so they're customizable by users.
To add a new keymap in `config.lua`
``` lua
local nvim_tree_cb = require("nvim-tree.config").nvim_tree_callback
table.insert(lvim.builtin.nvimtree.setup.view.mappings.list, { key = "C", cb = nvim_tree_cb "cd" })
```
Also what about adding `C` mapping by default? It's like nerdtree's one and it's a good alternative to the default one, `<c-]>`
> fix(nvimtree): restore default mappings + make them customizable

- lua/lvim/core/autopairs.lua
New additions:
```lua
{
disable_filetype = lvim.builtin.autopairs.disable_filetype,
disable_in_macro = lvim.builtin.autopairs.disable_in_macro,
ignored_next_char = lvim.builtin.autopairs.ignored_next_char,
enable_moveright = lvim.builtin.autopairs.enable_moveright,
enable_afterquote = lvim.builtin.autopairs.enable_afterquote,
map_c_w = lvim.builtin.autopairs.map_c_w,
map_bs = lvim.builtin.autopairs.map_bs,
disable_in_visualblock = lvim.builtin.autopairs.disable_in_visualblock,
fast_wrap = lvim.builtin.autopairs.fast_wrap,
}
```
Partially fixes #1997
```lua
vim.list_extend(lvim.builtin.autopairs.disable_filetype, {"sh"})
```
> fix(autopairs): add missing configuration entries

- lua/lvim/core/nvimtree.lua
Fixes #2007
It caused issues if telescope was started in folders containing spaces or folders that are symlinks.
- Put the cursor on folders containing spaces or folders that are symlinks
- Press `gtf` or `gtg`
- Enjoy
> fix(nvimtree): handle paths containing spaces

- lua/lvim/core/terminal.lua
- remove `hidden` parameter, so it can be persistent
- map keybinding for both normal and term modes
- a default shell is now always reachable with `<C-t>` according to `lvim.builtin.terminal.direction`
- add an addition keybinding `<C-\>` for `lazygit`
since it's hard to hit `<leader>gg` within the `timeoutlen` < 300ms
Try both `<C-t>` and `<C-\>` and see how `lazygit` is persistent.
https://user-images.githubusercontent.com/59826753/144755634-5a398719-403f-4721-b29b-f0e222d80d03.mp4
> feat(terminal): lazygit can now be toggled

- lua/lvim/lsp/config.lua
- lua/lvim/lsp/handlers.lua
- lua/lvim/lsp/init.lua
- lua/lvim/plugins.lua
- lua/lvim/utils/hooks.lua
- utils/installer/install.sh
- Add some missing handlers configuration for full compatbility with Neovim v0.6
- Remove code that specific to v0.5.0 considering that most plugins don't support it anymore
- Add a check in the installer to verify that v0.5.1 or higher is available
- bump treesitter version with `vim.cmd` parsing support
Using `gl` now uses the new `vim.diagnostic.open_float()` call.
> feat: full compatibility with neovim v0.6

- lua/lvim/core/terminal.lua
No longer trigger an error when `lazygit`, or any other term bin, are missing.
Fixes #2047
> fix: no longer treat lazygit missing as an error

- lua/lvim/bootstrap.lua
- lua/lvim/config/settings.lua
- utils/installer/install.ps1
- utils/installer/install.sh
- `spellfile` is now set in `settings.lua`
- remove all unnecessary calls to `vim.fn.mkdir` from bootstrap
- add a check to verify all lvim dirs in the installer
Fixes #2045
> fix(bootstrap): remove hard-coded spellfile option

- lua/lvim/core/terminal.lua
Instead of throwing an error if `lvim.builtin.terminal.open_mapping` is set to `nil`, this simply doesn't add the default binding
Set `lvim.builtin.terminal.open_mapping = nil` in `config.lua`. Note that it doesn't throw errors on startup.
> [Bugfix] Allow disabling the open binding for ToggleTerm

- lua/lvim/core/terminal.lua
Avoid binding `<c-\\>` directly, instead use `<c-\\><c-g>`
> chore(terminal): avoid problematic layzgit mapping

- lua/lvim/lsp/utils.lua
Fixes an issue with `LvimInfo` not parsing the `client_id` correctly.
> fix(lsp): correct client_id parsing in lvim-info

- lua/lvim/lsp/templates.lua
- fix(lsp): correct client_id parsing in lvim-info
- fix(lsp): allow overriding custom providers
- Can open `LvimInfo`
- Can override `sumneko_lua` with "lua-dev"
- Can disable `vuels` and actually remove the generated `vue.lua`
```lua
vim.list_extend(lvim.lsp.override, {"vuels" })
```
> fix(lsp): allow overriding servers with custom providers

- utils/installer/install.sh
This allows backup to succeed for people who use symlinks for managing dotfiles.
Currently errors with the following:
```
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1350) [sender=3.2.3]
````
Tested locally with `~/.config/lvim/config.lua` symlinked to a local file.
- Run command `./utils/installer/install.sh`
> Bugfix: installer backup linked files with rsync

- lua/lvim/core/autopairs.lua
This removes nvim-cmp/nvim-autopairs auto-completion behavior that's problematic. I give specific examples in #2082 showcasing the problem.
It's still possible to auto-complete with parens. If the auto-completion menu is open, typing `(` will add the opening and closing parens in addition to importing the function. I think this is simpler and clearer.
Fixes #2082
I ran this locally and it seems to work fine. The problematic examples I gave in #2082 have been fixed.
> fix: remove autopairs cmp completion

- utils/installer/install.sh
Avoid errors related to installing node-modules into a folder
that is not writable by the user executing the script.
1. no need execute the entire script, you can change the last line
```bash
install_nodejs_deps
```
2. now set `$NPM_HOME` to some nonsense.
```bash
env NPM_HOME="/var/my_node_modules" bash ./utils/installer/install.sh
```
> fix(installer): check if npm-prefix is writable

- README.md
- lua/lvim/config/init.lua
- lua/lvim/lsp/config.lua
- lua/lvim/lsp/handlers.lua
- unify the style between the handlers and diagnostics float-opts
- deprecate `lvim.lsp.popup_border` in favor of `lvim.lsp.float`
to allow further customizations
Fixes #2095
Invoking `vim.lsp.buf.hover()` (you can use `<K>`) should show borders now by default.
> fix(lsp): set the handlers opts for v0.6 as well

- utils/installer/install.sh
Typos existed  in the error message when installing node dependencies. You was changed to your.  "Please set you NPM_HOME correctly and try again." is now "Please set your NPM_HOME correctly and try again." The misspelling of privileges was also fixed. 
Testing:
- Run command `./install.sh` (do not use sudo, and also ensure you have not set up a prefix for the global installation directory as described [here](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally). 
- Ensure the error message regarding NPM is now grammatically correct.
> refactor(install.sh): fix typo in node error message

- lua/lvim/core/treesitter.lua
Avoid running the setup for treesitter in headless mode since it's harder to debug.
> refactor: avoid running ts.setup in headless

- lua/lvim/lsp/providers/sumneko_lua.lua
- lua/lvim/plugins.lua
Use [lua-dev.nvim](https://github.com/folke/lua-dev.nvim) instead of `cmp-nvim-lua`.
It provides better signature support.
Origin
Now
It could also have plugin's completion by modifying [here](https://github.com/LunarVim/LunarVim/pull/2043/files#diff-072b5a568c83434dda5a33ca67ecdcb46358ba94308236464a9dc8b1578bbff7R7)
> feat(luadev): better vim api completion

- lua/lvim/core/autocmds.lua
- lua/lvim/lsp/init.lua
- lua/lvim/lsp/manager.lua
- lua/lvim/lsp/utils.lua
- lua/lvim/utils/hooks.lua
Fixes the issue where `highlight_document` is still active when the server has already been stopped, when using `LspStop` or `LvimReload` for example.
You should no longer see any warnings after about `document_highlight` after calling `LspStop`.
> refactor: more consistent autocmds

- lua/lvim/lsp/init.lua
- The formatter in the `select_default_formater` function is still using its old function, that make `format_on_save` doesn't choose `null-ls` as default formatter
- Change the name of that function to new null-ls api function to make it work correctly
> fix(lsp): formatter now use new null-ls api function

- lua/lvim/config/defaults.lua
- lua/lvim/config/init.lua
- lua/lvim/config/settings.lua
- lua/lvim/core/autocmds.lua
- tests/specs/bootstrap_spec.lua
- tests/specs/config_loader_spec.lua
- add headless-mode settings that can help prevent truncating error messages
- move the colorscheme autocmds into their correct module
> refactor(settings): add headless-mode settings

- lua/lvim/utils/git.lua
Removing a `Log:error` line that was added but is, imo, more problematic than helpful.
I think the root cause is that the install script for lunarvim uses `--depth 1` when cloning which means the only ref/tag is `master` by default. So, the check for if the first tag is a number `%d` will result in the error message always being printed, causing a notification and message that is annoying/misleading and could potentially cause someone to waste time figuring the "problem". 
1. Uninstall lunarvim with the uninstall script.
2. Install lunarvim with the install script.
3. Open lunarvim/lvim. Before this fix I was seeing a notify and a message: "Unable to retrieve current tag. Check the log for further information"
> fix: remove "error" message from git tag

- lua/lvim/lsp/null-ls/code_actions.lua
- lua/lvim/lsp/null-ls/formatters.lua
- lua/lvim/lsp/null-ls/linters.lua
- lua/lvim/lsp/null-ls/services.lua
- allow passing the full list of options when registering sources,
such as `{ cwd = "", disabled_filetypes = "", ... }`
- both `cmd` and `exe` are allowed (backwards compatibility)
- `args` is internally translate to `extra_args` (backwards compatibility)
but can still use `generator_opts.args` instead
Fixes #1833
Your current configuration should still work, but now you can pass any other option that null-ls accepts
```lua
local linters = require "lvim.lsp.null-ls.linters"
linters.setup {
{
exe = "luacheck", -- you can also use `command = "luacheck"
cwd = function(params) -- force luacheck to find its '.luacheckrc' file
local u = require "null-ls.utils"
return u.root_pattern ".luacheckrc"(params.bufname)
end,
},
}
local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup …
```
> refactor(null-ls): allow passing full list of options for sources 

- lua/lvim/core/terminal.lua
This is due to inconsistencies of `:2ToggleTerm`
Fixes #2146
---
Thank you @00sapo for looking into this!
> refactor(term): leave the first few ids unassigned

- lua/lvim/lsp/templates.lua
- lua/lvim/utils/hooks.lua
No need to stop clients on `LvimReload` since we're not using `lspconfig/configs` directly anymore. And `LspRestart` doesn't currently re-attaches all the buffers correctly.
Fixes a regression from #2157
> fix(lsp): no need to stop clients on LvimReload

- utils/installer/install_bin.sh
Switch the delimiter used in `sed` since usernames can contain `@` symbol
Fixes #2162
```bash
bash utils/installer/install_bin.sh
```
> fix(installer): usernames can contain @ symbol

- lua/lvim/core/autocmds.lua
Should not use `sh` filetype for `zsh`.
They have much different syntax.
> fix(zsh): don't set filetype to sh

- lua/lvim/lsp/config.lua
Show the code of lsp diagnostics when available. 
This was working fine already for null-ls, now it should work fine as well for lsp servers.
**old**
**new**
> fix(diag): show lsp-diag code in open_float

- lua/lvim/core/autopairs.lua
we don't need to add these weird rules, let the user add them if they wanted to
Fixes #2204 
```lua
lvim.builtin.autopairs.on_config_done = function(autopairs)
autopairs.add_rule(Rule("$$", "$$", "tex"))
-- and more
end
```
> fix(autopairs): remove weird tex rules from autopairs

- lua/lvim/lsp/config.lua
Do not throw exception in case of incorrect eslint configuration
1. Open a project with eslint
1. Add a syntax error to `.eslintrc`
1. Open any js file in the project and hover a first line
**Before change**
Lunarvim throws the following error:
```
E5108: Error executing /.local/share/lunarvim/lvim/lua/lvim/lsp/config.lua:26: attempt to index field 'user_data' (a nil value)
```
**After change**
There is a float window with a correct message
```
eslint_d: SyntaxError: Cannot read config file: .eslintrc.json
Error: Unexpected token { in JSON at position 1
```
> fix(lsp): avoid accessing undefined user_data

- lua/lvim/lsp/config.lua
use `volar` instead of `vuels
Fixes #2229
> feat(vue): set volar as default language server instead of vuels

- README.md
Add command to install LunarVim on Windows to README.
I have installed LunarVim on a few different computers and have found it difficult to find the installer script because it was not listed in the README. 
Please feel free to change the labels for Windows/Linux installers; I don't know if the bash installer is also meant for Mac, and I'm sure there are other things I may have overlooked.
In Windows Sandbox:
- Install Chocolatey
- Run command: `choco install neovim git`
- Run command:
```powershell
iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1'))
```
It should be noted that if the user does not have Git installed, the open Powershell instance will close without giving the user a chance to see …
> docs(readme): add powershell installer script for Windows

- utils/installer/install.ps1
Fixes a bug in install.ps1 that throws error running while installing node/python dependencies.
Fixes #2178 
Tested by running install.ps1 on PowerShell 7.2.1, dependencies are now installed.
NOTE: This does not work on PowerShell 5.x as we are using *-ErrorAction Break*.
Reproduce:
```
Set-ExecutionPolicy Bypass -Scope Process -Force
pwsh .\utils\installer\install.ps1
```
Logs:
```
...
[INFO]: Checking dependencies..
Would you like to check lunarvim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
changed 35 packages, and audited 36 packages in 5s
2 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
Would you like to check lunarvim's Python dependencies?
[y]es or [n]o (default: no) : y
Requirement already satisfied: pynvim in …
```
> [Bugfix]: added -ScriptBlock to run commands ```install.ps1```

- Makefile
Fixes inability to install LunarVim for Nix users by replacing the default `/bin/bash` with `/usr/bin/env bash`.
Fixes #2240
- Point branch + repository of `install.sh` to my local repository.
- Change `/bin/bash` to `/usr/bin/env bash` and push that commit.
- Successful installation of LunarVim.
> fix(installer): universal bash

- lua/lvim/core/lualine/components.lua
Add proper space between glyphs and number for diff components.
Before:
After:
> fix(lualine): add space to diff components

- lua/lvim/core/lualine/components.lua
Remove the space for the treesitter icon.
Looks like
> fix(lualine): compacter size for treesitter icon

- lua/lvim/core/lualine/components.lua
The 2-char width characters cause problems in windows terminal.
Related to #1897
> fix(lualine): use 1-char width symbol for changed

- utils/installer/install.sh
This PR adds yarn support for the installer script. Nothing else.
Fixes #2279
In `utils/installer/install.sh` install_nodejs_deps uses pnpm then yarn and falls back to npm at last.
```shell
curl -fsSL https://get.pnpm.io/install.sh | sh -
bash utils/installer/install.sh
```
> feat(installer): use pnpm to install nodejs dependencies(#2279)

- lua/lvim/config/settings.lua
- lua/lvim/lsp/config.lua
People usually are not that fast, this has caused a lot of issues, the most recent one being https://github.com/tpope/vim-fugitive/issues/1951
also make sure that lsp floating window is focusable to fix issues like https://www.reddit.com/r/lunarvim/comments/srwss8/unable_to_scroll_inside_the_floating_popup/
> fix(timeoutlen): this has caused way too many issues in the past

- README.md
- utils/installer/install.sh
Add possibility for the user to auto install dependencies based on a flag that can be either `-y, --install-dependencies` which will not prompt the user for dependency installing, or `-n, -no-install-dependencies` which won't install deps altogether.
The default behavior of prompting is maintained.
Because while fiddling around with my dotfiles and automatic setup, I'd like to be able to run the script without any sort of interaction (heavily inspired on `npm init -y`
Ran the test locally in docker containers using the same installation configuration but with the different file:
- `bash <(curl -shttps://raw.githubusercontent.com/khaosdoctor/LunarVim/feature/auto-install-deps-sh/utils/installer/install.sh) -y`
- `bash <(curl -shttps://raw.githubusercontent.com/khaosdoctor/LunarVim/feature/a …
> feat: add option to automatically answer 'yes' for sh install script

- lua/lvim/lsp/init.lua
Allows for nicer autocompletion for `:NlspConfig` by default.
`:NlspConfig <language server>`
> feat: enable nlsp-settings schemas

- lua/lvim/config/settings.lua
The default intro message can be confusing if there's a problem with dashboard/alpha.
Related #2314, and many others :sweat_smile:
```lua
lvim.builtin.dashboard.active = false
```
> fix: disable the default intro message

- lua/lvim/core/nvimtree.lua
Fixes the issue with nvim-tree when you do a `lvim .`
instead of taking half of the window, it will resize to`30`
> fix: nvim-tree taking half the window on open

- utils/installer/install.sh
This PR fixes variable name typo introduced [here](https://github.com/LunarVim/LunarVim/pull/2330/files#diff-f8eb0b418c92b4d7f4f76654d1ed676ec9ff9124561c6a8cf6e6b1db63a43388R325) that made backup being skipped.
> [Bugfix]: correct typo in backup function

- lua/lvim/core/lualine/styles.lua
- lua/lvim/core/lualine/utils.lua
- lua/lvim/plugins.lua
Only assign lualine's theme to onedarker after the plugin has been enabled and installed.
```lua
lvim.builtin.lualine.options.theme = "onedarker"
```
Should pass the CI more consistently now.
> fix(lualine): conditional theme loading

- lua/lvim/plugin-loader.lua
Restore the previous behavior of automatically trying to set the colorscheme
Fixes #2364
> fix: automatically set colorscheme

- lua/lvim/core/alpha.lua
- lua/lvim/core/autocmds.lua
do not set laststatus if globalstatus is activated
Fixes #2365
> fix(alpha): globalstatus after openning files from dashboard

- lua/lvim/core/bufferline.lua
I think there should be a space between icon and the diagnostics count. See below for screenshots. Let me know if this issue is specific to my terminal emulator.
- Use `alacritty`
- Open a project with LSP
- Open a second buffer to show the bufferline
- Make a mistake in your code
> fix(bufferline): add an additional space before diagnostics

- lua/lvim/lsp/peek.lua
@otto-gebb can you verify if this fixes your issue or not?
Fixes #2369
> fix(peek): make sure popup_options are positive

- lua/lvim/lsp/peek.lua
Print an error in case LSP is unable to get contents
Fixes #2369
> fix(peek): print error if lsp is unable to get file contents

- lua/lvim/core/terminal.lua
Basically if you use `<space>` as your leader and keep the removed line in this commit
you would face some weird behavior if you try to use lazygit commit message ( hitting `<space>c` and then using space in your commit message)
> fix(terminal): weird lazygit commit message bug

- lua/lvim/core/which-key.lua
Lunarvim has keyboard shortcuts for various LSP searches, that feeds results to quickfix list.
It is useful then to have a quick way to inspect LSP results in quickfix via Telescope.
New keyboard shortcut for Telescope quickfix
See issue #1985
- Clicked `gr` on a symbol
- Pressed `Space l e` to see results in Telescope
> [Feature]: Keyboard shortcut for quickfix in Telescope

- README.md
> See #1906  and the Note under the `Breaking changes` section in the README
Was probably forgotten in [here](https://github.com/LunarVim/LunarVim/commit/c946ddda812c5c2d217061a9016eb8001970d659)
> docs(README): change forgotten breaking change in example

- README.md
The default version of PowerShell installed on most people's computers is v5, however the script only works on v7+. It would be good to have some indicator of this in the readme. I edited the readme and included a link on how to install too.
> fix(windows): specify required powershell version for the installation script

- lua/lvim/core/telescope.lua
when selecting code actions in telescope, it should only use `actions.select_default`
Fixes #2374
> fix(telescope): set <cr> binding to actions.select_default only

- lua/lvim/lsp/config.lua
- tests/specs/lsp_spec.lua
In this MR https://github.com/LunarVim/LunarVim/pull/2304 "ocamllsp" was added to the lsp servers "override" list
Not long after, "ocamlls" have been deprecated in favor of "ocamllsp", see https://github.com/williamboman/nvim-lsp-installer/pull/498
I replaced it my lvim local copy and cleaned the cache
> refactor(lsp): replace deprecated ocamllsp with ocamlls

- utils/installer/install.ps1
- utils/installer/uninstall.ps1
This PR fixes and issue that prevents a new line to be correctly added on the Powershell `$Profile` file to set the lvim alias.
This also fixes and issue that prevents the execution of the `uninstall.ps1` script. It was lacking the call to the `main` function. It also fixes some issues when trying to parse the cli args, and also when trying to test some of the old folders to be removed.
This was tested on a local install of LunarVim, in a Windows 11 machine with the latest version of Powershell installed.
> fix(installer/pwsh): fixes some details on installer and uninstaller

- utils/installer/config.example.lua
- utils/installer/config_win.example.lua
Fixes warnings caused by the use of lsp deprecated diagnostics methods, for document and workspace:
- lsp_document_diagnostics
- lsp_workspace_diagnostics
Warnings are displayed if `trouble document diagnostics` and `trouble workspace diagnostics` keyboard mappings suggested in the `config.example.lua` or `config_win.example.lua` are used.
> fix: update deprecated methods in example configuration for trouble.nvim

- lua/lvim/config/init.lua
- lua/lvim/core/info.lua
- lua/lvim/core/log.lua
- lua/lvim/lsp/providers/sumneko_lua.lua
- lua/lvim/plugin-loader.lua
- lua/lvim/plugins.lua
- lua/lvim/utils/hooks.lua
- tests/specs/config_loader_spec.lua
- tests/specs/plugins_load_spec.lua
- refactor: re-enable `packer.sync()` in `LvimReload` (was removed earlier for being too unstable)
- perf: remove `LvimSyncCorePlugins` from always getting called in `LvimReload` (too slow)
- fix: handle missing plugins in `LvimSyncCorePlugins` (`packer.rollack()` is currently getting stuck if a plugin doesn't exist)
- fix: wrap `LvimReload` with `vim.schedule()` to fix a data-race condition on `BufWritePost` (probably something new with nvim-tree)
- fix: override packer's log level correctly
Fixes #2408
A restart of lvim is probably still required tho
```lua
lvim.colorscheme = "tokyonight"
table.insert(lvim.plugins, {
"folke/tokyonight.nvim",
})
```
> refactor: re-enable packer.sync() in LvimReload

- lua/lvim/core/cmp.lua
- lua/lvim/lsp/config.lua
Now users can limit cmp menu width. Sometimes it looks too large when completion entries are too long.
To limit menu width put this line in `config.lua`:
``` lua
lvim.builtin.cmp.formatting.max_width = 50
```
where `50` is the number of columns that aren't exceeded.
> [Feature] Add option to set maximum cmp menu width

- utils/installer/config_win.example.lua
Avoid the deprecation warning upon installation by changing lvim.builtin.dashboard to lvim.builtin.alpha, following the changes to config.example.lua
Relaunch Lunarvim, deprecation message is gone.
> docs(windows): use lvim.builtin.alpha in config_win.example.lua

- lua/lvim/core/cmp.lua
- snapshots/default.json
Make sure we are using the latest cmp changes
also gets rid of this error message
> feat(cmp): `documentation` is deprecated in favor of `window.documentation`

- lua/lvim/core/lualine/components.lua
Fix some components on lualine with color theme gaps (diff, filetype, diagnostics)
Fixes #2403
Check if the "diff", "filetype" and "diagnostics" components on lualine respect the current theme.
> fix(lualine): color theme gaps in some components

- lua/lvim/plugins.lua
> fix(luasnip): only use user snippets if the folder exists

- lua/lvim/bootstrap.lua
- lua/lvim/utils/git.lua
- lua/lvim/utils/hooks.lua
- require v0.7+ for starting lunarvim (prevent issues with manual update)
- running `:LvimUpdate` when using a neovim <0.7 should switch to the tag `1.1.3` automatically and print a warning message 
Related #2476
- startup requirement: modify `~/.local/bin/lvim` to use a `nvim-0.6.1` appimage
- `LvimUpdate`: see https://github.com/LunarVim/LunarVim/issues/2476#issuecomment-1100859112
> feat: lock nvim <0.7 to a specific tag

- lua/lvim/core/nvimtree.lua
The nvimtree custom filter is a list of vim regex https://github.com/kyazdani42/nvim-tree.lua/blob/0f0f858348aacc94f98ba32880760c5a5440b825/doc/nvim-tree-lua.txt#L453-L457
Escaping the dot character avoids to filter filenames like "acache", "icache" etc
> fix(nvimtree): escape the dot character in custom filter

- lua/lvim/lsp/config.lua
- lua/lvim/lsp/peek.lua
Fixes #2489 
@danielo515 can you check if this helps you?
you can customize it using
```lua
lvim.lsp.peek.max_height = 15
lvim.lsp.peek.max_width = 30
lvim.lsp.peek.context = 10
```
> feat(peek): make sure max width and height are customizable

- utils/installer/install.sh
This makes sure users provide an acceptable answer when being prompted to confirm an action. I was installing LunarVim and accidentally answered `u` instead of `y` to a question, and the script interpreted it as a no and skipped the step.
Figured I'd just create a PR immediately, wdyt? Didn't touch the powershell script because that's scary.
I've ran the install script from my branch directly:
```
$ LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/williamboman/LunarVim/install-script-ensure-proper-prompt-answer/utils/installer/install.sh)
```
> feat(installer): ensure correct responses when prompting user

- README.md
The "black" utility does not include linting functionality.  So
including it in that section of the example configuration file,
leads to an error message on startup.
> Remove "black" from linting section in README.md

- .github/ISSUE_TEMPLATE/general-issue-form.yaml
- .github/ISSUE_TEMPLATE/lsp-issue-form.yaml
- .github/workflows/install.yaml
- .github/workflows/plugins.yml
- README.md
- lua/lvim/plugins.lua
- utils/installer/install.ps1
- utils/installer/install.sh
- require nvim v0.7+ for new installs
- update documentation
- chore: update neovim's moniker for winget
Fixes #2525
> refactor: lock new installations to nvim v0.7+

- lua/lvim/lsp/init.lua
- lua/lvim/lsp/manager.lua
- snapshots/default.json
- tests/minimal_lsp.lua
remove the usage of the deprecated setup-hook from `nvim-lsp-installer`, see https://github.com/williamboman/nvim-lsp-installer/pull/631
custom setup works fine
```lua
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "clangd", "pyright" })
local opts = {
cmd = { clangd_bin, unpack(clangd_flags) },
on_attach = custom_on_attach,
}
require("lvim.lsp.manager").setup("clangd", opts)
-- require("lvim.lsp.manager").setup("clangd") --- this also works now, since opts has been made actually optional :)
```
> refactor(lsp): decouple the installer setup-hook

- lua/lvim/bootstrap.lua
- lua/lvim/impatient/profile.lua
- lua/lvim/lsp/null-ls/init.lua
- lua/lvim/lsp/templates.lua
- tests/specs/bootstrap_spec.lua
~~Changes to "data" are currently unstable~~
- fix(lsp): undo stdpath overload to avoid datarace
- chore(linting): minor fixes
If the user adds an LSP setup call in their `config.lua`
```lua 
require("lvim.lsp.manager").setup("ccls", {})
```
then that will be executed before we've had a chance to call `require("nvim-lsp-installer").setup {}`, which happens in `require("lvim.lsp").setup()` which in turns relies on values from `config.lua`.. 
so it seems currently difficult to allow for both, instead, we'll revert the stdpath overload to keep things consistent with the old settings 😞 
Fixes #2507
It's already the default behavior, and having this in `config.lua` no longer throws an error
```lua
require("lvim.lsp.manager").setup("emmet_ls", {})
```
> fix(lsp): undo stdpath overload to avoid datarace

- utils/installer/install-neovim-from-release
the URL used to download neovim are different if a version is specified vs if we leave it to default to the latest build.
Fixes #(issue)
This script has been tested as follows:
RELEASE_VER=v0.6.1 bash /scripts/install-neovim-from-release
bash /scripts/install-neovim-from-release
and the nvim version verified after the installation.
> fix(installer): latest and specified release version for neovim have different urls

- lua/lvim/core/gitsigns.lua
This exposes gitsigns yadm feature flag to allow user to enable it in their 
config:
```lua
lvim.builtin.gitsigns.opts.yadm.enable = true
```
Tested locally.
Upstream docs: https://github.com/lewis6991/gitsigns.nvim#usage
> [Feature] gitsigns yadm support

- lua/lvim/core/cmp.lua
This adds tmux to the cmp sources.
https://github.com/andersevenrud/cmp-tmux
Tested locally, cmp-tmux works as expected.
> feat: add cmp-tmux to the list of sources

- lua/lvim/core/terminal.lua
- lua/lvim/core/which-key.lua
- lua/lvim/plugin-loader.lua
- lua/lvim/utils/hooks.lua
make use of the lua-autocmds API to run `packer.clean()` right after `packer.install()` instead
Fixes #2547
Only adding/removing some plugin from `lvim.plugins` in `config.lua` should open packer.display
```lua
table.insert(lvim.plugins, {
"norcalli/nvim-colorizer.lua",
config = function()
require("colorizer").setup({ "css", "scss", "html", "javascript" }, {})
end,
})
```
> revert: do not run packer.sync() on every reload

- lua/lvim/core/autocmds.lua
> fix(autocmd): actually use the format wrapper

- lua/lvim/lsp/utils.lua
refreshing codelens actions everytime we move the cursor is a bit too much, especially on rust, since on each cursor move it needs to update all references...
> feat(codelens): cursorhold is too much intrusive for codelens

- .github/ISSUE_TEMPLATE/general-issue-form.yaml
- .github/ISSUE_TEMPLATE/lsp-issue-form.yaml
- .github/pull_request_template.md
This updates the general issue template so the commands to execute to get the relevant logs do not dissapear when you paste the result of the first one. This always frustrates me. Also, the placeholder is not possible to copy, so it is even more work
I did not tested, but I don't think it is necessary
> chore: update templates

- lua/lvim/core/telescope.lua
- lua/lvim/core/which-key.lua
- lua/lvim/plugins.lua
Running `Telescope notify` doesn't have effect
There are two workaround.
1. manually load `notify`'s telescope extension if `notify` actived, as this pr
2. lazy-load `notify` by `event` or `after` key of `packer` provided:
```lua
{
"rcarriga/nvim-notify",
-- by event
event = "BufWinEnter",
-- by after
after = "telescope.nvim"
},
```
In the second workaround, I prefer to `after` because I could use `notify` in the startup of nvim. But `after` key may be buggy as described in #1729.
> fix: load notify's telescope extension properly

- .github/workflows/commitlint.config.js
- lua/lvim/config/init.lua
- lua/lvim/config/settings.lua
- lua/lvim/core/alpha.lua
- lua/lvim/core/alpha/dashboard.lua
- lua/lvim/core/autocmds.lua
- lua/lvim/core/bufferline.lua
- lua/lvim/core/commands.lua
- lua/lvim/core/log.lua
- lua/lvim/keymappings.lua
- lua/lvim/lsp/init.lua
- lua/lvim/lsp/manager.lua
- lua/lvim/utils/git.lua
- tests/specs/config_loader_spec.lua
- utils/installer/config.example.lua
- utils/installer/config_win.example.lua
**BREAKING CHANGE**: modifying the default options for keymaps and autocmds is now done by overwriting them, since they won't be loaded into the global `lvim` table anymore. **Make sure to check the updated structure of `lvim.autocmds` if you intend to use that table.**
- changes to `lvim.keys` in `config.lua` are now persistent after saving the file and/or `:LvimReload`
- ~~`undodir` and `spelldir` are validated and created if they don't exist~~
- `undodir` is validated and created if it doesn't exist
- `spellfile` is left to be handled by neovim which should create the appropriate file and directory on-demand, see `:h spellfile`
- feat: add `Log:set_log_level()`
- refactor: use the lua-commands api
- refactor!: use the lua-autocmds api
Fixes #2166
---
use the native neovim-api to create …
> refactor: load the default options once

- ftdetect/bicep.lua
- ftdetect/fish.lua
- ftdetect/fsautocomplete.lua
- ftdetect/julia.lua
- ftdetect/nix.lua
- ftdetect/sol.lua
- ftdetect/zig.lua
These filetypes are already detected in neovim by default so there's no
need to do it in lunarvim as well.
> refactor: remove redundant ftdetects

- lua/lvim/core/bufferline.lua
`:BufferKill` command will now prompt to use force to close a modified or a term buffer.
fixes #2642
- modify some buffer
- run `:BufferKill`
- pressing enter should abort by default, while typing `y` or `yes` will force quit the buffer
> feat: prompt when closing modified/term buffers

- lua/lvim/core/log.lua
Add the date to the timestamp of the LVIM logs.
It follows the same format as the default neovim log file, so this will make it more consistent.
fixes #2611 
- require structlog and get lvim log
- log anything
- check the log to see the full timestamp
> fix(log): add date to the timestamp of logs

- lua/lvim/core/autocmds.lua
`LvimToggleFormatOnSave` can disable the format-on-save feature properly, but once the feature is disabled from the enabled state, this command cannot enable it again. This is because `vim.api.nvim_get_autocmds` returns an empty list after disabling the feature.
This commit checks the size of the returned autocmd list when `M.toggle_format_on_save` is called and enables the feature if the size is 0.
Run `LvimToggleFormatOnSave` several times, and confirm that the code is automatically formatted after running `LvimToggleFormatOnSave` from the disabled state.
> fix(autocmds): toggle format-on-save properly

- .gitignore
- lua/lvim/core/nvimtree.lua
- lua/lvim/lsp/config.lua
- snapshots/default.json
This change introduced in https://github.com/kyazdani42/nvim-tree.lua/pull/1308/commits/d369e7d063a76a2810dce473d237f0c7c831bab7 doesn't play nicely with packer
- Run `:PackerSync` without getting warnings..
> fix: skip calling nvim-tree.setup() more than once

- lua/lvim/lsp/utils.lua
The notification message is too noisy when there are no matching language server each time we save with `format_on_save` is on. That's enough if it notifies only once.
<div align = "center">
</div>
> chore(lsp): notify format request failed once when there is no client

- lua/lvim/core/lualine/components.lua
unqiue buf client names in lualine lsp components
> fix(lualine): unique buf client names

- lua/lvim/plugins.lua
- tests/specs/plugins_load_spec.lua
- utils/ci/generate_new_lockfile.lua
- utils/ci/verify_plugins.lua
- utils/ci/verify_plugins.sh
- utils/installer/install.sh
- fix(plugins): explicitly lock the commit sha-1 to avoid having to rely
on Packer's snapshots, which are unreliable in headless mode
- feat(installer): add a verify plugins hook that runs post-installation
that will match the plugins current sha-1 against the defaults
fixes #2748, #2686
Installing should not trigger any errors, to see how rolling was broken, test the following
1. switch to rolling
2. cherry-pick fc93de17
3. installing lvim to another temporary location
```bash
INSTALL_PREFIX="/tmp/lvim/v4" LUNARVIM_RUNTIME_DIR="/tmp/lvim/v4" LUNARVIM_CONFIG_DIR="/tmp/lvim/v4/conf" LUNARVIM_CACHE_DIR="/tmp/lvim/v4/cache" bash utils/installer/install.sh --local
```
4. you should see an error about a hash mismatch
```bash
Verifying core plugins
mismatch at [toggleterm.nvim]: expected …
```
> feat(installer): add verify-plugins hook

- lua/lvim/lsp/config.lua
- lua/lvim/lsp/init.lua
- lua/lvim/lsp/templates.lua
- utils/installer/config.example.lua
- utils/installer/config_win.example.lua
Allow user to change default settings of `nvim-lsp-installer`
User can use `lvim.lsp.installer` to change setting of `nvim-lsp-installer`, accepts the same values as [original default configuration](https://github.com/williamboman/nvim-lsp-installer#default-configuration)
```lua
lvim.lsp.installer = {
ensure_installed = {
"rust_analyzer",
"sumneko_lua",
"taplo",
"tsserver",
"cssls",
"jsonls",
},
ui = {
border = "rounded",
icons = {
server_installed = "✓",
server_pending = "➜",
server_uninstalled = "✗",
},
keymaps = {
toggle_server_expand = "<CR>",
install_server = "i",
update_server = "u",
uninstall_server = "d",
},
},
}
```
> feat(lsp): add option to override default `nvim-lsp-installer` settings

- lua/lvim/lsp/config.lua
- lua/lvim/lsp/init.lua
- lua/lvim/lsp/providers/jsonls.lua
add a new `lvim.lsp.nlsp_settings.setup` table for configuring https://github.com/tamago324/nlsp-settings.nvim
- fix(lsp): update nlsp's json schemas path
- feat(lsp): add option to override nlsp-settings
integration with `schemastore.nvim` will now actually work :)
> feat(lsp): add option to override nlsp-settings

- lua/lvim/core/commands.lua
This adds two new commands, as suggested in #2708. One for open the lunarvim log as a file, and another to just open lunarvim log.
They follow a similar naming as they which-key counterparts, one being named after open and the other after edit:
- `LvimOpenlog`
- ~~`LvimEditlog`~~
fixes #2708 
I tested it on my config and it works fine
- ~~`:LvimEditlog`~~
- See logs
- `:LvimOpenlog`
> feat(logger): add open command

- lua/lvim/lsp/utils.lua
fix(lsp): update format filter for nightly, see https://github.com/neovim/neovim/commit/fa3492c5f7645feb979c767046b6ff335ea9d6ca
fixes #2757, #2640
1. enable `stylua`
2. `:set ts=8 sw=8`
3. formatting with the lua-server follows neovim's settings, so the above should take effect if the filter is broken.
4. change `.stylua.toml` and try again
> fix(lsp): update format filter for nightly

- lua/lvim/core/comment.lua
Comment default config was set with extra = false with a comment
suggesting this was for `g>`, `g<`, etc. mappings. However, the `extra`
argument is for the `gco`, `gcO`, and `gcA` mappings which should be enabled
by default and, in my opinion are very useful. The extended mappings are
still disabled by default.
Try the mappings.
> fix(comment): add extended mappings

- lua/lvim/core/terminal.lua
- lua/lvim/lsp/init.lua
use the `desc` field in `vim.keymap.set` to avoid relying on `which-key`
directly.
fixes #2752
all LSP keymaps should still work _and_ have a description.
> refactor(whichkey): use vim.keymap.set directly

- lua/lvim/plugin-loader.lua
fixing :PackerSync on large config from being stuck while syncing
add max_jobs to make large configs work. sometimes `packersync` stuck 
recommendation is from @abzcoding mentioned in https://github.com/abzcoding/lvim/issues/67#issuecomment-1172866361
i don't see any downsides.. 
from the official repo:
`max_jobs = nil, -- Limit the number of simultaneous jobs. nil means no limit`
fixes #(https://github.com/abzcoding/lvim/issues/67)
- Run command `:PackerSync`
> fix: adding max_jobs = 40; to :PackerSync

- lua/lvim/config/defaults.lua
- lua/lvim/lsp/config.lua
- lua/lvim/lsp/init.lua
- lua/lvim/lsp/utils.lua
- feat(lsp): bind formatexpr and omnifunc by default
- fix: pass filter correctly to format-on-save
fixes: #2741, #2866
- press `gqap` to format a paragraph
- use `<c-x><c-o>` to trigger native omni completion
> feat(lsp): bind formatexpr and omnifunc by default

- lua/lvim/core/cmp.lua
…etion.
Removes emmet logic from cmp.lua   We were performing a check to see if emmet was active on every completion request.  This slows down completion regardless of the filetype you're editing.  Additionally, the emmet logic no longer works and is no longer required to get emmet running in lunarvim.  
If a user wants to run emmet, they can configure it like so:
```lua
lvim.plugins = {
{
"aca/emmet-ls",
ft = {
"html",
"typescriptreact",
"javascriptreact",
"css",
"sass",
"scss",
"less",
},
},
{
"jackieaskins/cmp-emmet",
run = "npm run release",
},
}
table.insert(lvim.builtin.cmp.sources, { name = "emmet" })
lvim.builtin.cmp.formatting.source_names["emmet"] = "(Emmet)"
```
> perf(cmp): remove redundant check for emmet-ls

- lua/lvim/lsp/manager.lua
A server_name can be the same as its filetype, which will match the given pattern if you set any filetype autocmd for it. This might prevent a server from attaching.
Consider the html lsp. Its server_name is simply `html`. This might prevent a user from setting up plugins like `nvim-colorizer`, `nvim-ts-autotag` or using the emmet lsp in tandem.
Solution:
Use the lua API so we can match the specific command string, which contains only the manager's setup call, instead of trying to match/parse the result of `:autocmd`. 
- Set a 'html' filetype autocommand.
- Check `:LvimInfo`. 
- Lsp should be attached.
> fix(lvim/lsp/manager): make client_is_configured more reliable

- lua/lvim/core/project.lua
I set `lvim.builtin.project.active = false` in my configuration and caused a lot of errors because project_nvim was being called nonetheless
> fix: use pcall for setting up project.nvim 

- lua/lvim/core/nvimtree.lua
As commit <https://github.com/kyazdani42/nvim-tree.lua/commit/9a02dedd92fad67b04b2a3fee2de20555956b089>, `nvim-tree` has removed trailing spaces from the default `indent_markers` icons. That would cause an issue when unneeded space was rendered in tree in `LunarVim`. Add all available icons setting, so that this will make more consistent.
- Before:
width="235" 
alt="before" 
src="https://user-images.githubusercontent.com/42694704/180992072-8d223eac-8d1f-4260-b462-23bbd198d974.png">
- After:
width="235" 
alt="after" 
src="https://user-images.githubusercontent.com/42694704/180991473-9694c73f-abfe-4e69-b391-58e8c109e473.png">
</div>
> fix(nvimtree): remove `indent_markers` icons trailing space

- utils/installer/install.ps1
`install.ps1` gets flagged by antivirus software due to Invoke-Expression even though it's commented out.
Deleting the comment apparently fixes the problem.
The commented lines didn't seem useful in any way, therefore I think removing them is justified.
fixes #2817
- Fixed the problem on my machine with Bitdefender Total Security antivirus installed.
> fix(installer) comment causes antivirus false positives

- lua/lvim/core/which-key.lua
Add which-key keybinding to cycle to next buffer
fixes #2872
- Start LunarVim
- enter the buffer window: `<leader>b`
- find the new option "Next" in the menu
> feat(whichkey) add default keybindings to cycle to next buffer

- lua/lvim/config/init.lua
- lua/lvim/core/builtins/init.lua
- lua/lvim/core/info.lua
- lua/lvim/core/mason.lua
- lua/lvim/core/which-key.lua
- lua/lvim/lsp/config.lua
- lua/lvim/lsp/init.lua
- lua/lvim/lsp/manager.lua
- lua/lvim/lsp/templates.lua
- lua/lvim/lsp/utils.lua
- lua/lvim/plugins.lua
- snapshots/default.json
- tests/minimal_lsp.lua
- tests/specs/lsp_spec.lua
> `mason.nvim` is the next generation version of `nvim-lsp-installer`. It builds on
> top of the very same foundation as `nvim-lsp-installer`, but with a majority of
> internals refactored to improve extensibility and testability.
fixes #2850
> refactor!: migrate to mason.nvim

- lua/lvim/core/which-key.lua
When require `telescope.builtin.internal`, produce an error Module no found.
Telescope => [init.lua](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/init.lua)
- Open Preview Colorschemes
> fix: handle deprecated telescope.builtin.internal

- lua/lvim/lsp/config.lua
- lua/lvim/lsp/providers/tailwindcss.lua
The first commit adds a helper function to check for dependencies in a `package.json` file.
The second enables the server and adds a custom provider for it, where we hijack `root_dir` to check if the server be attached.
Logic follows the vscode extension https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss.
> In order for the extension to activate you must have tailwindcss installed and a Tailwind config file named tailwind.config.js or tailwind.config.cjs in your workspace.
The PR also paves the way for enabling angularls by default, if something similar to https://github.com/neovim/nvim-lspconfig/pull/1462 gets merged there (afaik, it's working).
- Open a tailwind project, server should be attached.
- Open a non tailwind project, server should not be attached …
> feat(lvim/lsp): enable tailwindcss by default

- lua/lvim/core/lualine/components.lua
set icon color according to the status of treesitter
fixes #(issue)
L
> fix(lualine): set icon color according to the status of treesitter

- utils/installer/install.ps1
By default PowerShell does not create the file associated with `$PROFILE` during the installation. [MS Docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.2#:~:text=By%20default%2C%20the%20profile%20does%20not%20exist%2C%20even%20though%20PowerShell%20stores%20a%20path%20and%20file%20name%20for%20it.)
The Windows installer script throws an error when trying to add the `lvim` alias to the user profile.
- added a check to create the file if nonexistent
fixes #2758 and partly #2805 
- Run `utils/installer/install.ps1` on fresh vm / without a user profile.ps1
> fix(installer): create profile.ps1 if nonexistent

- utils/installer/config_win.example.lua
LunarVim had an issue on windows where it displayed nvim-tree error messages on start up
the was to edit the config.lua file and change all the nvim-tree settings from `false` to `nil`
from this
to this:
This results with no error messages on start up on windows
> docs(windows): update example config for nvim-tree

- lua/lvim/keymappings.lua
- utils/installer/config.example.lua
Buffer cycling keymaps should be delegated to which-key. These keymaps fulfil the same role and are therefore redunant.
part of https://github.com/LunarVim/LunarVim/issues/2872#issuecomment-1201616659
- Buffer cycling is implemented and tested here https://github.com/LunarVim/LunarVim/pull/2873/commits/5f9f711c93c79ef63410390f8b47a0fc3cf0ea5f
> refactor(keymaps)!: don't hijack H/L by default

- utils/installer/config.example.lua
- utils/installer/config_win.example.lua
- Update `config_win.example.lua`
- Fix typo workspace > workspace
> docs(windows): update example config

- lua/lvim/lsp/null-ls/linters.lua
null-ls linters may have either `DIAGNOSTIC`, `DIAGNOSTIC_ON_OPEN`, or `DIAGNOSTIC_ON_SAVE` as its method parameter. e.g., https://github.com/jose-elias-alvarez/null-ls.nvim/blob/8914051a3d399e9715833ad76bbf5fe69ea7faf0/lua/null-ls/builtins/diagnostics/buf.lua#L12
Currently, only linters with `DIAGNOSTIC` are shown in the lsp component on the statusline regardless of whether the linters are registered and work properly.
This is due to `lvim.lsp.null-ls.linters.list_registers` returning only linters with `DIAGNOSTIC`.
This PR makes that function retrieve the linters with all three method types and return the merged list.
- Register `buf` null-ls linter, which is set to `DIAGNOSTIC_ON_SAVE`, open a supported file (i.e., proto file), then check if `buf` linter is shown in the statusline.
> fix(statusline): display null-ls linters properly

- utils/installer/install.sh
- feat(installer): handle INSTALL_PREFIX not on PATH
- feat: skip optional deps on permission errors
fixes #2905
add this rule to Makefile
```make
install-local:
@echo starting LunarVim local test installer
@env \
INSTALL_PREFIX=/tmp/p2 \
NPM_HOME=/usr/local \
LUNARVIM_CONFIG_DIR=/tmp/p2/xdg/config \
LUNARVIM_RUNTIME_DIR=/tmp/p2/xdg/data \
LUNARVIM_BASE_DIR=/tmp/p2/xdg/data/lvim \
bash ./utils/installer/install.sh --local
```
> feat(installer): handle INSTALL_PREFIX not on PATH

- lua/lvim/core/autopairs.lua
- lua/lvim/core/cmp.lua
- snapshots/default.json
- adapt new recommendations
- add `<c-y>` as an alternative `confirm` binding (should play better with autopairs and luasnip)
- add `<up>` and `<down>` bindings for selecting completions
- minor cleanup to `method.jumpable`
fixes #2876
> refactor(cmp)!: adapt new recommendations

- lua/lvim/lsp/manager.lua
The predicate function of the lsp manager should accept one argument to make it more clear and portable
- It is just a minor style correction
> fix(lsp): pass name arg to should_auto_install

- lua/lvim/core/comment.lua
`Ctrl` + `/` now works for block comments. Visual select something, press `Ctrl` + `/` and it should NOT comment out the whole line but only the selection.
fixes #2937
> fix(ts_context_commentstring): block comment match new api

- lua/lvim/core/lualine/components.lua
- lua/lvim/lsp/config.lua
Just a simple cleanup. The deepcopy can be removed, and the component logic was duplicated.
> chore: remove unnecessary code

- utils/installer/config.example.lua
- utils/installer/config_win.example.lua
The currently way to remove items from skipped_servers list doesn't make any effect on the original list `lvim.lsp.automatic_configuration.skipped_servers`:
```lua
vim.tbl_map(function(server)
return server ~= "emmet_ls"
end, lvim.lsp.automatic_configuration.skipped_servers)
```
The function `vim.tbl_map` only returns a new list with the certain function applied, and doesn't modify the original one. Also, by the example `return server ~= "emmet_ls"`, it doesn't return the list with filtered values, and yes a list with booleans resulted by the function.
The solution for this is just assigning the returned list from the `vim.tbl_map` function inside the original list `lvim.lsp.automatic_configuration.skipped_servers` and also changing the function to `vim.tbl_filter`, because this way makes …
> docs(lsp): fix the way of removing items from skipped_servers

- lua/lvim/core/cmp.lua
The CR mapping of cmp overrides the provided confirm_opts, making this change permanent. This PR avoids that.
- Test CMP CR to select a mapping
> fix(cmp): do not mutate the original confirm_opts on CR

- lua/lvim/plugins.lua
- snapshots/default.json
[folke is back](https://github.com/LunarVim/LunarVim/pull/2538#issuecomment-1238668560), so we don't need to use the alternative repos anymore
cc: @danielo515
> fix(plugins): bring back original folke repos

- lua/lvim/core/cmp.lua
When cmp prompt is open and nothing is selected cr did nothing
Also fixes snippets texts being overwritten when you select an option 
fixes #2977
This PR superseeds #2979 
- Trigger cmp window and do not select anything
- Tap enter and see how it properly inserts a newline
- Expand one snippet using cmp
- check that selecting a cmp item while editing the snippet does not override the snippet text
> fix(cmp): fix cmp select on CR

- lua/lvim/core/autocmds.lua
fixes #2952
- Run `:LspStop` after attaching.
- Run `:autocmd CursorHold`, `lsp_document_highlight` should not be there.
See also https://github.com/LunarVim/LunarVim/pull/2953
> fix(core/autocmds): do not check for existence on clear_augroup

- lua/lvim/lsp/utils.lua
Checks for existence of buffer local `documentHighlight/codeLens` autocommands before registering another one.
- Run `:e` multiple times. 
- There should be only one `CursorHold` autocmd for codelens/documentHighlight for the current buffer.
> fix(lsp/utils): do not register duplicate autocommands

- utils/installer/config.example.lua
- utils/installer/config_win.example.lua
fix 'lvim.builtin.treesitter.highlight.enabled = false' not work.
Change config to take effect.
> fix(example config): fix config for treesitter

- .luarc.json
- lua/lvim/lsp/providers/sumneko_lua.lua
`lua-dev` has changed the way it accepts settings, this will now hopefully accommodate those changes!
- fix `lvim.` auto-completion in `config.lua`
- add a select list of plugins by default that should always have auto-completion
```lua
plugins = { "plenary.nvim", "telescope.nvim", "nvim-treesitter", "packer.nvim", "LuaSnip" }
```
fixes #3002
- open `config.lua` start typing `lvim.builtin.telescope.`
- open `config.lua` start typing `require'packer.`
> fix(lsp): enforce lvim completion for lua-server

- lua/lvim/core/telescope.lua
- lua/lvim/core/telescope/custom-finders.lua
- add the ability to display untracked files by default when invoking `find_project_files`
- can be turned off by setting the `show_untracked` to `false`.
```lua
-- show untracked files
require('lvim.core.telescope.custom-finders').find_project_files()
-- skip untracked files
require('lvim.core.telescope.custom-finders').find_project_files({show_untracked = false})
```
> feat(telecope): set show_untracked by default

- lua/lvim/core/breadcrumbs.lua
- lua/lvim/core/illuminate.lua
- lua/lvim/plugins.lua
- utils/installer/install.sh
- revert: suggest using PackerCompile and instead of hard-coding config
- fix(installer): remove useless shallow clone
- `rm ~/.config/lvim/plugin/packer_compiled.lua`
- `lvim +PackerSync`
- check that winbar works :rocket:
> revert: fix Packer instead of hard-coding config

- README.md
Fix the missing branch export necessary for rolling branch, where it was defaulting to master.
fixes #(issue)
- Check logs
- ...
> fix: add branch export for rolling installation

- lua/lvim/core/indentlines.lua
instead of using `vim.g` use the normal setup for [indent_blankline](https://github.com/lukas-reineke/indent-blankline.nvim#setup)
> fix(indentblankline): make sure to use the new syntax for all options

- lua/lvim/core/breadcrumbs.lua
- lua/lvim/core/telescope.lua
- see: https://github.com/LunarVim/LunarVim/commit/552197499cb1ca0b858d24c8d035bc6404f41148#r84561561
- add `neo-tree` filetype to breadcrumbs excludes
- neo-tree has it's own winbar, remove unnecessary setting winbar to `nil` on excludes check
- Tested this on my local
> fix: small fixes on telescope pickers & breadcrumbs

- .github/workflows/format.yaml
- use up-to-date ci actions tag
see: https://github.com/LunarVim/LunarVim/pull/3060#issuecomment-1255660048
> fix(ci): resolve stylua ci rare error

- lua/lvim/core/log.lua
Fixed:
- incorrect type hint in `add_entry` method description
- added missing `event` parameter type hint
- corrected reference from `vim.log.log_levels` to the current `vim.log.levels`
> fix(log): correct add_entry code documentation

- README.md
`maintained` option is not supported anymore https://github.com/nvim-treesitter/nvim-treesitter/issues/2887
N/A
> doc: Replace Tree-sitter `maintained` with `all` in README

- init.lua
- lua/lvim/core/autocmds.lua
I want to be able remove or change all of the autocommands defined in lunarvim
e.g:
```lua
pcall(function()
vim.api.nvim_del_augroup_by_name "_last_status"
end)
vim.api.nvim_clear_autocmds { pattern = "lir", group = "_filetype_settings" }
```
> feat(autocmds): make sure all autocmds are modifiable

- snapshots/default.json
When trying to install (either `stable` or `rolling` release) by following the instructions I was getting the following error:
```
[DEBUG 23:01:44] update.lua:102: Failed to update folke/lua-dev.nvim: {
data = {
data = {
data = {
exit_code = 128,
signal = 0
},
msg = "Error checking out commit 6ff40c0 for folke/lua-dev.nvim remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0\nfatal: invalid reference: 6ff40c0"
},
msg = "Error getting updates for folke/lua-dev.nvim: remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0\nfatal: invalid reference: 6ff40c0"
},
msg = "Error checking updated commit for folke/lua-dev.nvim: 9da602d"
}[packer.nvim] [DEBUG 23:01:46] packer.lua:347: Processing plugin specs[packer.nvim] [INFO  23:01:46] packer.lua:783: Finished compiling …
```
> fix: set `lua-dev.nvim` to a valid commit version.

- lua/lvim/plugins.lua
- snapshots/default.json
https://github.com/neovim/neovim/issues/12587 is now fixed.
> chore(plugins): remove deprecated FixCursorHold.nvim

- lua/lvim/plugin-loader.lua
I don't think anyone wants to wait 5 minutes for a git clone to fail. I think one minute is more than enough
Reduce the timeout of packer for git clone
I don't think it is required, but CI should test this already
> refactor: smaller timeout for packer

- ftplugin/lua.lua
now, when you're hovering over a require('a.b.c'), you can type gf, and go to the 'c.lua' file
> feat: type gf on require file

- lua/lvim/core/nvimtree.lua
This setting is a hidden gem for JVM devs that have deeply nested directory structures. 
This PR doesn't change the default value, it just adds the setting to the `lvim.builtin.nvimtree` object so that it is discoverable via LSP autocompletion
> Add group_empty nvimtree setting

- utils/installer/install.sh
The installer now checks if the user has a config at `.config/lvim/config.lua` and won't overwrite it if that's the case.
fixes #3146
- Install luavim using the utils script
- Edit the default config file at `.config/lvim/config.lua`
- Uninstall luavim using the utils script
- ReInstall luavim using the utils script
The config file has been overwritten
- Edit the default config file at `.config/lvim/config.lua`
- Modifie the install script and check it using shfmt (`shfmt -i 2 -ci -bn -l -d utils/installer/install.sh`
- Uninstall it and Reinstall it with the modified script
The config file has not been overwritten
> fix: don't overwrite previous config

- .github/ISSUE_TEMPLATE/general-issue-form.yaml
- .github/ISSUE_TEMPLATE/lsp-issue-form.yaml
- .github/workflows/install.yaml
- .github/workflows/plugins.yml
- README.md
- lua/lvim/bootstrap.lua
- lua/lvim/lsp/utils.lua
- lua/lvim/utils/hooks.lua
- utils/installer/install.sh
- require v0.8+ for starting lunarvim (prevent issues with manual update)
- running :LvimUpdate when using a neovim <0.8 should switch to the tag 1.1.4 automatically and print a warning message
see #2491 for more info on the implementation
closes #3019
should pass the CI?
> feat: lock new installations to nvim 0.8+

- lua/lvim/lsp/handlers.lua
Right now, if illuminate is active lsp hover border will not be used. I don't see why those two should be related. I removed the condition to always have it on.
> fix: always use border for lsp hover

- .github/workflows/close-inactive-bot.yml
Added a new GitHub workflow to mark issues as stale, and close them after 14 days of inactivity thereby.
fixes #3168
Through GitHub actions.
> feat: Workflow to stale/close inactive issues | Fixes #3168

- lua/lvim/core/lualine/init.lua
fixes #(issue)
- Check logs
- ...
> fix(lualine): guard setup on install

- lua/lvim/core/theme.lua
- lua/lvim/plugin-loader.lua
The two colorscheme lines below inside `xpcall` function couldn't take any advantage of the `debug.traceback` function.
https://github.com/LunarVim/LunarVim/blob/6ab3e8a73920e3d2e02e57f7dd3a1f3d8e54ee63/lua/lvim/plugin-loader.lua#L109-L111
So when users set colorscheme that hasn't been installed, they will be warned with
> "problems detected while loading plugins' configurations" 
without knowing what happen inside their config. We should move it outside and handle its own error instead.
~~Also clear core plugins' caches on saving `config.lua` file. So that the change will instantly load without exiting and entering `lvim` again.~~
fixes #2856
- Set `lvim.colorscheme="something"`
- Should be warned with
> feat: warn user when setting un-installed colorscheme

- utils/installer/config_win.example.lua
Sorry for missing the second config example.
This is an follow-up for #3176.
> fix(typo): fix language server name typo in config example #3176

- lua/lvim/core/cmp.lua
I'm using https://github.com/gelguy/wilder.nvim for cmdline suggestions and the recent change to cmp.cmdline is conflicting with my configs, so I added an extra property in the cmp config object to control cmp.cmdline
added `lvim.builtin.cmp.cmdline` config to control cmp from the config.lua file
```lua
-- in config.lua
lvim.builtin.cmp.cmdline.enable = false
```
> feat(cmp): add configs for cmp.setup.cmdline

- lua/lvim/core/telescope.lua
1. Fixes #3064 by defining the delete_buffer bindings only for the buffers telescope. This lets you use the default C-d/C-u in insert mode and dd in normal mode for other telescopes, and prevent an error from showing, while retaining functionality in the buffers telescope.
2. Also removed duplication of defining the default binds
> fix: telescope delete_buffer binds correct scope (and small refactor)

- snapshots/default.json
I can't wait for the bot to it
Bump nvim-tree.lua to version [b01e7be](https://github.com/nvim-tree/nvim-tree.lua/commit/b01e7beaa6f0dbbf5df775cf4ecc829a23f0be54), it has changes from this PR https://github.com/nvim-tree/nvim-tree.lua/pull/1637
> chore: bump nvim-tree.lua version to `b01e7be`

- lua/lvim/lsp/providers/sumneko_lua.lua
- snapshots/default.json
types has been moved from `lua-dev.sumneko` to `lua-dev.config`
more info: https://github.com/folke/lua-dev.nvim/commit/42e9c5126904d6715ece660224610f3a38e4b8d4
> fix(lua-dev): make sure we are loading the correct types

- lua/lvim/keymappings.lua
Remove the _J_ and _K_ key mappings for moving lines of code since the _J_ mapping overrides the standard _J_ (join lines) action.
Not having the standard _J_ mapping is confusing for new users. _Alt-j_ and _Alt-k_ are still available for moving lines.
- Verified that _J_ (join lines) works in visual block mode.
- Verified that _Alt-j_ and _Alt-k_ can still be used to move lines.
> fix: Remove J and K key mappings for move

- lua/lvim/utils/git.lua
Removed an extra `a` in https://github.com/lunarvim/lunarvim/blob/rolling/lua/lvim/utils/git.lua#L43
> fix: typo in git.lua

- lua/lvim/core/breadcrumbs.lua
i want to be able to exclude `noice`, `notify` and ... filetypes from breadcrumbs
> fix(breadcrumbs): make winbar_filetype_exclude customizable

- lua/lvim/core/cmp.lua
Just added a name for treesitter to cmp to make sure al built-in sources are named
Just use it
> fix: name treesitter source in cmp

- lua/lvim/lsp/providers/sumneko_lua.lua
- lua/lvim/plugins.lua
- snapshots/default.json
[lua-dev.nvim](https://github.com/folke/lua-dev.nvim) is now [neodev.nvim](https://github.com/folke/neodev.nvim)
> fix(luadev): this plugin has been renamed

- lua/lvim/core/which-key.lua
Disabling gitsigns `next_hunk` and `prev_hunk` navigation messages
> fix: disable gitsigns hunk navigation message

- lua/lvim/config/settings.lua
[VIM algorithm does not support spellchecking for Asian characters](https://vim-jp.org/vimdoc-en/spell.html#spell-cjk), but they are spellchecked by default anyway, which results in every sentence highlighted as wrong when you use multiple languages in your file.
Before the change:
all Asian characters are spellchecked and, as a result, underlined
After the change:
they are omitted from spellchecking
- Open an empty buffer
-  Paste a few Japanese/Chinese sentences
```md
こんにちは、LunarVimは素晴らしいです
お疲れ様でした
This is a correct English sentence.
VIMの日本語のスペルチェックは不可能です
```
- set the language spelling `:set spelllang=en`
- all Asian characters are highlighted as errors
- append the `cjk` to disable Asian characters spell checking `set spelllang+=cjk`
- now everything is correct
> fix: disable unsupported asian characters spellchecking

- lua/lvim/core/breadcrumbs.lua
Got an "Error detected while processing CursorMoved Autocommands for '*'", originating from when winbar_filetype_exclude is not populated/set to nil.
> fix: nil table in breadcrumbs in autocommand

- lua/lvim/core/autocmds.lua
Removes `_format_options` autocmd group which was causing issues for some users.
fixes #3237
> fix(autocmds): remove _format_options group

- lua/lvim/core/theme.lua
This fixes the problem that `tokyonight` colorscheme cannot be found.
Related #3311
> fix(theme): do not fallback to tokyonight if no user's theme found

- lua/lvim/core/lir.lua
`nvim-web-devicons` is reloaded causing issue that user cannot have their own custom icon change.
- Before: 
- Set custom icon in `config.lua`
```lua
require("nvim-web-devicons").set_icon {
["docker-compose.yml"] = {
icon = "",
color = "#00a4ff",
name = "Dockerfile",
},
}
```
- See that the icon now change (which cannot be achieved before)
> fix(icons): do not reload `nvim-web-devicons` module

- lua/lvim/config/init.lua
- lua/lvim/core/breadcrumbs.lua
- lua/lvim/core/nvimtree.lua
Use hlgroup from web devicons instead of creating our own, so the name doesn't contain illegal characters.
fixes #3330
lvim Dockerfile.ops-1
> fix(breadcrumbs): use hlgroup from web devicons in breadcrumbs

- lua/lvim/core/which-key.lua
Removes keymapping left behind when nvim-notify was removed
fixes #3329 
Tested locally. 
Key map is removed from the menu
- ...
> fix: Remove notify which key mapping

- lua/lvim/core/log.lua
related to #3202
There is a wrong call when overriding vim.notify
There is no issue related, but there is a discussion #3202 
- Not tested
> fix: call proper log function in notify override

- lua/lvim/lsp/manager.lua
[This fix](https://github.com/LunarVim/LunarVim/commit/b8f681374b25740e0aea1c859bf313197ed63dd5) doesn't work anymore since [this commit](https://github.com/neovim/nvim-lspconfig/commit/fe7a6f41e59654db6bbc9eb2d084decc54b295e4#diff-0e1bd346624fa540fa153e867fbc2036ced5c83d5cd7d79d9308df1328b7c879R69-R79) in lspconfig because the commit removed `command` from the autocommand. This PR changes the lua match from the now nonexistent `command` to `desc` which does contain the name of the server
fixes #3144
Opened a cpp file in lvim (cpp because then both c and cpp ftplugins will run, so require("lvim.lsp.manager").setup("clangd") will be called twice)
Before this change a warning appeared: `Client 1 quit with exit code 1 and signal 0`
> fix(lsp): don't start servers multiple times

- lua/lvim/lsp/manager.lua
Apparently in the latest neovim build, filetype.lua or packer.nvim is working a bit different, 
for example when I want to load a plugin only in certain filetypes, this happens:
because some autocmds don't have a description:
> fix(lsp): do a nil check before string matching autocmd desc

- lua/lvim/core/telescope/custom-finders.lua
When LunarVim is cloned in ~/.config/nvim (to make it play with Neovide), the LunarVim which-key shortcuts `Lf` and `Lg` did not work, because a wrong base-directory was used.
fixes #(issue)
I tested the shortcuts in both settings - when LunarVim is cloned to ~/.config/nvim and when installed the usual way.
- Check logs
- ...
> fix(finders): use lunarvim basedir

- lua/lvim/core/log.lua
- lua/lvim/plugin-loader.lua
- utils/ci/verify_plugins.lua
- utils/installer/install.sh
- refactor(installer): skip unstable headless update
- fix(installer): verify that packer is installed
- refactor(packer): skip dodgy snapshot feature
fixes #3358, #3311
see https://github.com/LunarVim/LunarVim/pull/3338#issuecomment-1296238671
> refactor(installer): skip unstable headless update

- lua/lvim/config/settings.lua
disables smartindent
fixes #3219
1. Open any file with lines like `# this is a title`
2. Use >> on that line
3. The line is indented
> fix(defaults): don't use smartindent

- lua/lvim/core/alpha/startify.lua
depending on the random iteration order `resolve_config` in alpha.lua would sometimes overwrite val with {} after `resolve_buttons`
fixes #3027
Opened lvim 20 times and checked if all sections were present
> fix(alpha): make startify sections always appear

- lua/lvim/core/breadcrumbs.lua
Make breadcrumb update less frequent by changing the `CursorMoved` event to `CursorHoldI`
I think having a short delay on updating the breadcrumbs is more acceptable than having a huge lag on moving cursor. 
fixes #3353
> fix(breadcrumbs) Performance issue, change CursorMoved event to CursorHoldI

- lua/lvim/plugin-loader.lua
- lua/lvim/utils/hooks.lua
- fix(hooks): use ColorScheme event in the reload-hook
- fix(packer): run packer recompile on cache_reset
- fix(packer): actually restrict sync core plugins
fixes #3257
tested with @ChristianChiarulli 's config files
```bash
#!/usr/bin/env bash
export INSTALL_PREFIX="/tmp/lvim/v2"
export LV_BRANCH="fix-reload-hooks"
export LV_REMOTE="kylo252/lunarvim.git"
export LUNARVIM_BASE_DIR="/tmp/lvim/v2/base"
export LUNARVIM_RUNTIME_DIR="/tmp/lvim/v2/data"
export LUNARVIM_CONFIG_DIR="/tmp/lvim/v2/conf"
export LUNARVIM_CACHE_DIR="/tmp/lvim/v2/cache"
installer_url="https://raw.githubusercontent.com/kylo252/LunarVim/6fc2e4fc3545228b4ded9fa3d08feda6bc1978da/utils/installer/install.sh"
installer="$(mktemp)"
curl -LSs "$installer_url" -o "$installer" && bash "$installer" --no-install-dependencies
```
> refactor(hooks): use colorscheme event after reload

- init.lua
- lua/lvim/config/_deprecated.lua
- lua/lvim/config/init.lua
- lua/lvim/core/theme.lua
- lua/lvim/keymappings.lua
- tests/specs/config_loader_spec.lua
moves `lvim.builtin.theme.options` into `lvim.builtin.theme.tokyonight.options` since they are
specific to how `tokyonight` is configured.
- all the deprecated options are now in a single file
- use `__newindex` to handle new entries
- this gives us much better flexibility (e.g. this can handle `lvim.builtin.theme.options.dummy`)
- and it allows us to generate a trace where that action was last defined
- chore: remove merge duplicate
related #3313, #3378
```lua
-- add this somewhere in your config
lvim.builtin.theme.options.dim_inactive = true
```
> refactor(theme)!: decouple tokyonight options

- lua/lvim/utils/hooks.lua
bug in nvim-tree is breaking things on reload
- Run command `:PackerSync`
> fix: revert ColorScheme autocmd execution

- lua/lvim/config/init.lua
- all the deprecated options are now in a single file
- use `__newindex` to handle new entries
- this gives us much better flexibility (e.g. this can handle `lvim.builtin.theme.options.dummy`)
- and it allows us to generate a trace where that action was last defined
originally added in #3384
```lua
-- add this somewhere in your config
lvim.builtin.theme.options.dim_inactive = true
```
> refactor(config): better deprecation handling

- lua/lvim/bootstrap.lua
- lua/lvim/config/defaults.lua
- lua/lvim/core/log.lua
fixes #3377 
- Run command `:LvimUpdate`
> fix(logger): set console logging to sync

- utils/installer/install.ps1
- utils/installer/uninstall.ps1
use the master branch instead of rolling in the windows installer
not tested
> fix(installer): Use master in windows installer

- lua/lvim/core/bufferline.lua
closing active buffer with bufferline caused nvimtree to go "fullscreen"
close active buffer with bufferline
> fix(bufferline): use buf kill on close

- utils/installer/install.ps1
This can prevent spacing in the path causeing the Set-Alias error.
Simply add a '' to prevent the error/bug.
fixes #(issue)
Fix error when the path to the lvim.ps1 have spacing.(e.g. the username has spaces)
- Run the setup script, then run the```. $profile```, see if there is any error message.
> fix(installer): use quotes in set-alias

- lua/lvim/core/commands.lua
- lua/lvim/core/which-key.lua
Added command `:LvimDocs` and keybind `<leader> L d` to open LunarVim's documentation (https://www.lunarvim.org/docs/installation) as requested in #3312.
> This ticket is assigned to another user, please favour their PR over this one. I thought I would submit a PR as there has been no activity for a while & no draft PR open. I'm very new to LunarVim (and NeoVim) and saw this ticket as a great opportunity to get involved and start learning more. 😄 
fixes #3312
- macOS (Ventura 13.0)
- Windows 11
- Linux - Tested by @LostNeophyte 
* Ran command `:LvimDocs` and verified the link opened in my default browser.
* Ran the keybind `<leader> L d` and verified the link opened in my default browser.
> feat: add command & keybind to view docs

- lua/lvim/core/autocmds.lua
The autoreload config cmd was created on every save which incremented the number of autorelaod functions
fixes #3392
fixes #3391
- Reload config a couple times
- Run command `:lua vim.pretty_print(vim.api.nvim_get_autocmds {group="lvim_reload_config_on_save"})`
- See one config reload autocmd
- Nothing brakes even with quite a lot of swift saves
> fix(autocmds): add separate autoreload config group 

- lua/lvim/core/autopairs.lua
After running :LvimReload, with each run autopairs' `on_confirm_done` was added to cmp's events, and that caused additional `()` to be added to function completion (only noticed this in lua though). This PR makes sure the event listener is added only once
- Run command `:LvimReload` a couple times
- See that one pair of parenthesis is added with completion
> fix(autopairs): attach confirm_done only once

- lua/lvim/core/dap.lua
configurable logging level for dap/dap-ui
```lua
-- config.lua
lvim.builtin.dap.log.level = "debug"
```
start a debug session and check `$LUNARVIM_CACHE_DIR/dap.log`
```lua
-- config.lua
lvim.builtin.dap.ui.notify.threshold = vim.log.levels.INFO
```
run `:PackerCompile` and check that "setup called twice" has disppeared
> feat: configure dap logging

- lua/lvim/plugin-loader.lua
Increases git clone timeout in packer when in headless so that the installer is less likely to fail
fixes #3464 
not tested, but I did test that changing it to 0 makes the install fail so this should work as well
> fix(packer): increase clone timeout in headless

- lua/lvim/lsp/manager.lua
Fixes regression as a result of #3366
This prevented `powershell-editor-services` lsp and possibly others from attaching
> fix(lsp): some servers have dynamic commands

- utils/installer/install.ps1
Fixes the following error message when verifying the version in the powershell script:
```
Error detected while processing command line:
E114: Missing quote: " | cquit | else | quit | endif
```
Manually executed to confirm that there are no longer any error messages. Script now completes with:
```
Your LunarVim installation is now up to date!
```
> fix(installer): fix syntax error with powershell installer

- CONTRIBUTING.md
CI tests check the PR title, but there's no information in the guidelines how to do it
> docs(contributing): make it clear how to title PRs

- lua/lvim/core/bufferline.lua
Fixes a bug in buf_kill where wrapping around doesn't work. Lua indexes start at 1 and not 0, so the last element is `#buffers` and not `#buffers - 1` :)
fixes #(issue)
opened 2 buffers, closed the first one
> fix(bufkill): wrap around correctly

- lua/lvim/core/bufferline.lua
`buf_nums` can be nil if `lvim.builtin.bufferline.options.mode == "tabs"`
fixes #3367 
opened a buffer with `mode="tabs"` in bufferline
> fix(bufferline): fallback to empty table if `buf_nums` is nil

- lua/lvim/lsp/providers/sumneko_lua.lua
- Enables `busted` and `luassert` libraries by default to prevent popup every time
- Enables [`checkThirdParty`](https://github.com/sumneko/lua-language-server/wiki/Settings#workspacecheckthirdparty)
fixes #3439
- Tested in VS Code, confirmed no issues and very minimal startup time increase (`~22ms`)
Currently unable to test in LunarVim, but it would be my first time using it anyway, so bad behaviour would be hard to catch.
> fix(lsp): sumneko-lua library scanning

- README.md
Adds a warning to the README on the `rolling` branch that that branch is deprecated.
It's just a quick change to the markdown.
> doc(readme): deprecation warning on `rolling` branch

- lua/lvim/core/autocmds.lua
Removes autocommand enabling `spell` and `wrap` in markdown and gitcommit
fixes #3455
> fix(autocmds): remove spell autocmd

- lua/lvim/core/nvimtree.lua
- lua/lvim/core/which-key.lua
Remove hardcode mapping on `lua/lvim/core/nvimtree.lua`. It allows uses to define there bind their bind in their own config file without being overwritten by nvimtree setup file.
PR closes #3491
> fix(nvimtree): avoid hard-coded mapping

- lua/lvim/core/bufferline.lua
Fixed spitting strack trace when unsaved buffers are attempted to close. 
fixes #(issue)
- Run command:  Try closing buffers to the left with unsaved changed and press Escape. It spits the following traceback
- Error executing Lua callback: .../.local/share/lunarvim/lvim/lua/lvim/core/bufferline.lua:197: attempt to index local 'choice' (a nil value)
stack traceback:
.../.local/share/lunarvim/lvim/lua/lvim/core/bufferline.lua:197: in function 'on_confirm'
...al/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/ui.lua:95: in function 'input'
.../.local/share/lunarvim/lvim/lua/lvim/core/bufferline.lua:194: in function 'buf_kill'
.../.local/share/lunarvim/lvim/lua/lvim/core/bufferline.lua:62: in function 'command'
...k/packer/opt/bufferline.nvim/lua/bufferline/commands.lua:61: in function …
> fix: discard invalid choice when closing buffers

- lua/lvim/core/breadcrumbs.lua
The `Markdown` entry in the list of excluded file types for the **breadcrumbs** module did nothing, as the output of `vim.bo.filetype` for MD files yields the value of `markdown`.
No tests other than the simple smoke ones were necessary.
This PR addresses the discussion in #3189.
> chore(breadcrumbs): remove `Markdown` from excluded file types

- utils/installer/uninstall.sh
By default when we uninstall lunarvim, the uninstaller script removes user configuration,which normally located in .config/lvim/  and unlike installer script, it will not make a *.old file
This is means those configuration made by the user is completely gone, and is not reversible, if  anytime user wants to install lvim back. ( :*(  just now i lost it, glad i had a backup of system, but it was old).
This is unexpected because most package managers don't remove user configurations
So i made default behaviour to not to remove user config files, and  but added it as a  additional option for those who wanted it. @Lost Neophyte from discord proposed this idea to make it additional flag rather than (y/n) question
fixes #(issue)
- Run command `bash uninstall.sh` for not removing .config/lvim …
> fix(uninstaller): add separate flag to remove user config

- utils/installer/install.sh
During install it's unclear what the installer is asking to install - this change outputs the dependencies as part of the questions to aid the user in decision making.
```
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies: neovim, tree-sitter-cli?
[y]es or [n]o (default: no) : no
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies: pynvim?
[y]es or [n]o (default: no) : no
--------------------------------------------------------------------------------
Would you like to install LunarVim's Rust dependencies: fd::fd-find, rg::ripgrep?
[y]es or [n]o …
```
> feat(installer): describe language installation dependencies

- lua/lvim/core/alpha.lua
- lua/lvim/core/alpha/dashboard.lua
- makes the hl groups overridable
- makes opts overridable
- fixes #3400 
empty config:
```lua
lvim.builtin.alpha.dashboard.section.buttons.opts.hl = "Error"
lvim.builtin.alpha.dashboard.section.buttons.opts.hl_shortcut = "Error"
lvim.builtin.alpha.dashboard.section.footer.opts.hl = "Error"
lvim.builtin.alpha.dashboard.section.header.opts.hl = "Error"
```
setting `lvim.builtin.alpha.dashboard.opts = {autostart = false}` also works
> feat(alpha): allow configuring highlight groups

- lua/lvim/core/alpha/dashboard.lua
alpha is refreshing when opening the terminal and feedkeys put `zbzbzb` inside of it
I added `feedkeys` when making the dashboard responsive, bit it seems like a bad idea now 
after this fix the first lines of the logo will get sometimes cut off (the content is scrolled down for some reason) after resizing the application window
> fix(dashboard): remove feedkeys

- .github/ISSUE_TEMPLATE/general-issue-form.yaml
- .github/ISSUE_TEMPLATE/lsp-issue-form.yaml
Better examples of what LSP means 
from https://github.com/LunarVim/LunarVim/issues/3570#issuecomment-1336842777 (LSP issue created using the general template)
> About the issue template, I don't think it could be any clearer, it just that for a person who is not too familiar with the business like me, Tailwindcss intellisense didn't seem to have anything to do with LSP, because Tailwindcss itself is not a language, so yeah, everyday you learn a new thing, thanks in advanced for the quick support. Besides, adding a few examples to the issue template's description may help if the misunderstanding happens too often
> ci: better issue templates description

- lua/lvim/core/terminal.lua
user's config is sourced after terminal's config, which caused setting vim.opt.shell to not have any effect in the execs
fixes #3526 
1. changed lvim.builtin.terminal.shell
2. `<M-1>`
> fix(terminal): use user's shell in execs

- .github/workflows/plugins.yml
Currently, the `plugins version bump` github workflow is running and failing on forks and sending emails to the fork owner every 15 mins.
Added a check to only run the CI for the repo owned by lunarvim
fixes #(issue)
Ran the workflow on my fork and it was skipped.
- Check logs
- ...
> ci: restrict scheduled workflows to lunarvim

- lua/lvim/core/theme.lua
only call theme.setup if the theme is selected, fixes issues with vimscript colorschemes
> fix: only call theme's setup if it's selected

- lua/lvim/core/cmp.lua
User can use a `on_config_done` property in nvim-cmp config. It allow user to hook on the plugin and make additionnal configuration after the plugin is setup.
1. See that completion shows up when writing a commit for exemple
2. Add 
```lua
lvim.builtin.cmp.on_config_done = function(cmp)
cmp.setup.filetype("gitcommit", {
enabled = false,
})
end
```
In the nvim config file
4. Reload LunarVim
5. Commit something in a repo and see that completion doesn't open
Signed-off-by: Mathieu Cartaud <dev@mcartaud.com>
> feat(cmp): add on_config_done callback

- snapshots/default.json
current commit sha of tokyonight is invalid, it causes ci to fail (also packer on first installs) 
https://github.com/folke/tokyonight.nvim/commit/0f7b6a5 says `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository`
> fix(snapshots): correct tokyonight commit sha

- lua/lvim/core/which-key.lua
When toggling the dap UI via `<leader>dU` the dap UI never re-adjusts based on window size.  I tend to resize my window, especially when doing things like debugging.  
I've [seen in other dotfile examples](https://github.com/rcarriga/dotfiles/blob/master/.config/nvim/lua/config/dap.lua#L38), people pass in `{reset = true}` to the dap toggle.  I want to propose it as a reasonable default behavior.  
Re-opened the dapui after resizing the window several times to ensure it was picking up the new behavior.
> feat(dap): update dap ui to resize when toggled

- lua/lvim/utils/functions.lua
fixes #(issue)
- Check logs
- ...
> feat: don't prompt smart quit when buffer open in another window

- lua/lvim/core/autocmds.lua
adds all lua files in the config dir to the reload on save autocmd pattern
adds symlinked directories to the pattern (for things like stow)
save a lua file in the config
> feat(reload): add all conf files to aupat

- lua/lvim/core/treesitter.lua
treesitter indentation for cpp is broken. to reproduce:
1.  ```cpp
while()<CR>{
```
2.  ```cpp
while()
{ // the brace isn't moved back as it should be (that's what happens with `:TSBufDisable indent`)
```
fixes #3685
> fix(ts): disable indent for c and cpp

- utils/installer/install.sh
ignores xdg desktop error `xdg-desktop-menu: No writable system menu directory found`
fixes `cp: cannot stat '/root/.config/lvim/*': No such file or directory`
fixes  #3684
> fix: bash installer errors

- lua/lvim/plugins.lua
We already have the configuration for cmdline completions (disabled by default). But the plugin has to be installed as a user plugin after enabling it.
With this commit setting `lvim.builtin.cmp.cmdline.enable = true` will also enable the `cmp-cmdline` plugin.
> feat: cmdline config option enables cmp-cmdline plugin

- lua/lvim/config/init.lua
copy the win config if os is windows
> fix(config): copy the correct example config

- lua/lvim/core/breadcrumbs.lua
- lua/lvim/core/lir.lua
we were requiring `nvim-web-devicons` in a couple places without checking if it's available or if icons are enabled
Fixes #3640
1. `lvim.use_icons = false`
2. `:PackerSync`
3. no more errors in lir and breadcrumbs
> fix(icons): make devicons optional

- lua/lvim/core/lir.lua
fixes #(issue)
- Check logs
- ...
> fix(lir): nil check

- lua/lvim/core/breadcrumbs.lua
To reproduce the issue:
1. Open a new tab
2. Switch back to an existing tab
3. Tab count (right side of the breadcrumbs) will show the old tab count for a brief moment.
As a fix, add TabEnter as an additional event for refresh autocmd.
> fix(breadcrumbs): refresh on TabEnter

- lua/lvim/plugins.lua
- snapshots/default.json
`kyazdani42/nvim-web-devicons` is renamed to its org: https://github.com/nvim-tree/nvim-web-devicons. Also, update the plugin to its latest commit.
- Updated the plugin myself
- Check with additional new feature to set default icons:
```lua
local ok, devicons = pcall(require, "nvim-web-devicons")
if ok then devicons.set_default_icon("", "#6d8086") end -- this func is not available in the previous commit, only the latest
```
- Works!
> chore(devicons): rename devicons owner & update

- lua/lvim/core/indentlines.lua
the current context is using the default middle line, and other lines use our left aligned one, which should not be the case
> fix(indentlines): set indent_char to LineLeft

- utils/installer/install.sh
> fix(installer): only install treesitter-cli if it's missing

- lua/lvim/plugin-loader.lua
sync_core_plugins cleaned lazy.nvim, after which requiring it was impossible so it couldn't install itself , this pr fixes it
> fix(plugin-loader): don't clean lazy.nvim in sync_core_plugins

- lua/lvim/plugin-loader.lua
fixes #3744 
require("lazy").sync cleaned all plugins, instead of just updating which caused treesitter parsers to be deleted on update
> fix(plugin-loader): don't clean plugins on LvimUpdate

- lua/lvim/core/log.lua
- snapshots/default.json
Refactor structlog usage for future 0.2 release
- Add a flag for disabling vim.notify logging as notification (to discuss)
- Run lvim
- Log something
- Check that it is logged into all sinks
https://github.com/Tastyep/structlog.nvim/pull/6
> refactor(logger): adapt to new changes upstream

- lua/lvim/config/settings.lua
Add .cr as a crystal filetype
Locally in my config.lua
> feat: Add crystal filetype

- lua/lvim/core/autopairs.lua
Existing autopairs rules should be opt-in instead of as a default.
> fix!: disable strange autopairs rules

- lua/lvim/utils/git.lua
It's useful to know if the user edited lvim core files, this pr adds this info to :LvimVersion
> feat: include git status in LvimVersion

- lua/lvim/core/alpha.lua
- lua/lvim/core/alpha/dashboard.lua
- lua/lvim/core/autocmds.lua
Added option to modify the autocommand that declares \<ESC\> as :qa when in filetype=alpha 
Added default as true to alpha.lua's main config, to not have any change to the current settings. 
Added "q to exit" to the alpha (dashboard mode) prompt list to make the q to :qa\<CR\> remap apparent.
- Tested with and without newly added setting `lvim.builtin.alpha.esc_to_quit = true/false` to only change the action if setting is added to personal config.
> feat(alpha): add quit button to dashboard

- lua/lvim/core/treesitter.lua
it's fixed now
Reverts LunarVim/LunarVim#3687
> feat(ts): enable indent for c and cpp

- lua/lvim/core/which-key.lua
_set `<leader>sl` to `:Telescope resume`_ 
---
it's a useful bind
> feat(which-key): keybind for `:Telescope resume`

- utils/installer/config.example.lua
- utils/installer/config_win.example.lua
parsers without a strict filetype, e.g. "comment", are not handled when `auto_install = true`
> docs(ts): add hint about `ensure_installed`

- snapshots/default.json
latest version of alpha breaks if you open a file first and then open the dashboard 
https://github.com/goolord/alpha-nvim/issues/178
> fix(alpha): rollback to older commit

- lua/lvim/lsp/templates.lua
for filetypes like yaml.ansible [nvim will load yaml.lua and ansible.lua](https://github.com/neovim/neovim/blob/e5d8220179f932ab9c9ef59996cab357a25eaaf8/runtime/ftplugin.vim#L28-L34) form ftplugin, not yaml.ansible.lua
> fix(lsp): template generation for filetypes with dots

- lua/lvim/core/terminal.lua
- lua/lvim/plugins.lua
Set keybinds in `init`
Load by any of them
> perf(toggleterm): on-demand lazy load

- lua/lvim/core/autopairs.lua
- lua/lvim/core/treesitter.lua
- lua/lvim/plugins.lua
Override deprecated API from `nvim-treesitter` as a workaround for https://github.com/LunarVim/LunarVim/pull/3836#issuecomment-1427613551
not sure how to trigger the error in the first place..
> fix(cmp): handle deprecated tree-sitter api

- lua/lvim/core/terminal.lua
I have an issue on Windows when my shell settings like `vim.opt.shell` or `lvim.builtin.terminal.shell` has no effect with `open_mapping` key.
Tested on other OSes as well.
- Setting `vim.opt.shell = "pwsh"` or `lvim.builtin.terminal.shell = "pwsh"`
- See that the shell change when pressing with `open_mapping` key like `<C-\>`
> fix(terminal): don't set  the shell by default

- lua/lvim/plugin-loader.lua
- lua/lvim/utils/hooks.lua
Calling `lazy.cache.enable()` in `plugin_loader.init()` doesn't work properly, it is before calling lazy setup and then the lazy setup calls `cache.enable` again on it's own.
Instead only override the path and let lazy do the rest. (already enabled in default lazy config)
Also remove the `pcall`, this is an internal variable and we would wanna know if it breaks in the future.
`reset_cache` is also removed as looks like that's not necessary.
> fix: lazy cache

- lua/lvim/icons.lua
Replaces the old Material Design `nf-mdi-orbit` icon with the new one `nf-md-orbit`.
The old one is deprecated since [Nerd Fonts](https://www.nerdfonts.com/cheat-sheet) v2.3, and will be removed in v3.
1. Edit `lua/lvim/core/lualine/components.lua`
2. Check the statusline:
- https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3 (see _Material Design Icons_)
- ryanoasis/nerd-fonts#1097
- ryanoasis/nerd-fonts#773
> chore: replace deprecated MDI Orbit icon

- lua/lvim/config/init.lua
before this pr the error message after loading invalid config disappeared after loading the theme and it was easily missed
> fix(config-loader): defer invalid configuration warning

- lua/lvim/core/telescope/custom-finders.lua
`_close` in `telescope.actions` is deprecated, telescope docs says to use `close` instead
> chore(custom-finders): solve deprecation warning

- lua/lvim/lsp/config.lua
This PR corrects the capitalization of the g goto shortcut in the keybindings, which was previously inconsistent with the corresponding actions. Specifically, gd (go to definition) should be lowercase, while gD (go to Declaration) should be uppercase. This update ensures that the keybindings are more intuitive and consistent with their associated actions.
- gd: go definition
- gD: go Declaration
- `g` shows the goto dashboard, the capitalized D should be mapped to Declaration instead of definition.
> fix(lsp): incorrect `g` goto capitalization

- lua/lvim/core/cmp.lua
Sets cmp.confirm_opts.behavior to replace when entry is from copilot
fixes #3343
Idea stolen from Lazyvim's fix for the same issue: https://github.com/LazyVim/LazyVim/discussions/387#discussioncomment-5207870
> fix: copilot indent reset (#3343)

- lua/lvim/core/dap.lua
`vim.g.border_chars` is not defined.
> fix(dap): invalid border value

- lua/lvim/core/nvimtree.lua
Prevents overwrite of `nvim-tree.update_focused_file.ignore_list` configuration.
Fixes #3985
- Create a configuration with an ignore_list for nvim-tree. That list should be respected after the fix is applied.
- Specifically I use a plugin called DiffView, and every time I execute `DiffviewOpen` when nvim-tree is open, I get a nasty error taking up my whole screen. With the following line in my `config.lua`, it is supposed to prevent the error from appearing: `lvim.builtin.nvimtree.setup.update_focused_file.ignore_list = { 'DiffViewFiles' }`. However, without this fix the error still appears.
> fix(nvimtree): don't overwrite update_focused_file.ignore_list

- lua/lvim/plugins.lua
- snapshots/default.json
According to https://github.com/nvim-lua/plenary.nvim/pull/209 , `nvim-lua/popup.nvim` is deprecated and was fully merged into `plenary.nvim`.   
`popup.nvim` is originally installed as a dependency of `telescope.nvim` but it is nolonger required, see https://github.com/nvim-telescope/telescope.nvim#required-dependencies
I've removed `popup.nvim` from the plugin list.
> chore(plugins): remove `popup.nvim` as it is deprecated

- lua/lvim/core/mason.lua
This PR adds the `on_config_done` option to `lvim.builtin.mason`. This behaves like `on_config_done` for other plugins, such as `lvim.builtin.nvimtree.on_config_done`. That is, if a function is assigned to `on_config_done`, it will be called at the end of the `lvim.core.mason.setup()` with an argument of the loaded `mason` module.
This enables users to define setup logic in `config.lua` using the correctly set up `mason` module. 
For example, `require("mason-registry").get_installed_packages()` does not work as expected before `mason` is set up.
- Assign a function to `lvim.builtin.mason.on_config_done`,  and check if the `mason` module has been setup properly when that function is called.
> feat(mason): add on_config_done option to lvim.builtin.mason

- utils/installer/install.ps1
On Windows 10 the installation of LunarVim using the powershell script is failing on my machine with the following error:
```
$LV_BRANCH='release-1.2/neovim-0.8'; Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression
88\                                                   88\
88 |                                                  \__|
88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
88 |\888888  |88 |  88 |\888888$ |88 |        \$  / …
```
> fix(installer): validation step was failing on windows

- lua/lvim/core/illuminate.lua
- lua/lvim/core/indentlines.lua
- lua/lvim/core/lir.lua
- lua/lvim/core/mason.lua
When no package loaded by `require_safe` , it signals no error, which results `local status_ok, xxx = pcall(reload, xxx)`  receives a wrong `status_ok` when `xxx` module not found.
fixes #(issue)
#4024 #4037
> fix: use `require` instead of `reload` in pcalls 

- lua/lvim/lsp/config.lua
Avoid viewing duplicate diagnostic codes since they are now already shown by default since https://github.com/neovim/neovim/pull/21130/commits/c2d7b22646ec383da69b850f80dce3fa9f816e41
- view a diagnostic in a hover window with `gl`
- check that the codes aren't duped compared to before
> fix(lsp): diagnostic codes already show by default

- lua/lvim/core/commands.lua
This MR updates the `documentation_url`, which was pointing to a nonexisting webpage. Running `<space> L d` on the `master` branch currently results in the following page being opened:
- Run `<space> L d` after applying the fix onto a local installation
- Verified that an existing documentation webpage is opened (I've chosen the [begginer's guide](https://www.lunarvim.org/docs/beginners-guide))
> fix(user_command): update url in `LvimDocs` command

- lua/lvim/core/nvimtree.lua
Due to #4054, there was a change to `nvim-tree` custom keymappings to suppress the deprecation warning. These changes override the keymaps outside of the tree causing error when pressing `h,l,o`.
- Open buffer with `lvim`
- Press `h,l,o` inside buffer won't log error of invalid window id from `nvim-tree`
> fix(nvim-tree): use local buffer keymaps

- utils/installer/config.example.lua
- utils/installer/config_win.example.lua
Update broken links in example configs
I guess  example configs is little bit out-of-date and required update.
especially this section (link isn't replaced yet):
https://github.com/letavocado/LunarVim/blob/21080bf6a23c220b78a0d766a3b418770352e460/utils/installer/config.example.lua#L67-L75
```lua
-- -- you can set a custom on_attach function that will be used for all the language servers
-- -- See <https://github.com/neovim/nvim-lspconfig#keybindings-and-completion>
-- lvim.lsp.on_attach_callback = function(client, bufnr)
--   local function buf_set_option(...)
--     vim.api.nvim_buf_set_option(bufnr, ...)
--   end
--   --Enable completion triggered by <c-x><c-o>
--   buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")
-- end
```
> docs: update broken links in example configs

- lua/lvim/plugins.lua
sometimes mason wasn't loaded properly and automatic installation of lsp servers failed
> fix(lsp): lazy load mason on FileOpened

- init.lua
- lua/lvim/plugin-loader.lua
before: 
```sh
~/.config/lvim
/usr/share/nvim/site
~/.local/share/lunarvim/lvim
plugins # should be before `/usr/share/nvim/site`
plugins/after
~/.local/share/lunarvim/site/after
~/.config/lvimd/after
```
after:
```sh 
~/.config/lvim
~/.local/share/lunarvim/lvim
plugins
/usr/share/nvim/...
plugins/after
~/.local/share/lunarvim/site/after
~/.config/lvim/after
```
fixes #3723  #3941
`:set rtp?`
> fix: correct runtimepath order

- lua/lvim/core/lualine/components.lua
* fix(lualine): use get_active_clients instead of deprecated function
`vim.lsp.get_active_clients()` accepts a table to filter returned
clients by id, bufnr and name. In this case when want to get clients for
current buffer, if bufnr is not given then it defaults to current
buffer, so need to pass anything here.
See `help vim.lsp.buf_get_clients()`
* refactor(lualine): simplify LSP component
`vim.lsp.get_active_clients` always returns a table, if that table is
empty, there's no clients attached, hence return appropriate message. No
need to use `next()`
Remove all the complicated logic with the `msg` parameter, no argument
is passed in any of the places that component is used, no need to have it.
> fix(lualine): use get_active_clients instead of deprecated function

- .github/ISSUE_TEMPLATE/general-issue-form.yaml
- .github/ISSUE_TEMPLATE/lsp-issue-form.yaml
- .github/workflows/install.yaml
- lua/lvim/bootstrap.lua
- lua/lvim/core/breadcrumbs.lua
- lua/lvim/utils/hooks.lua
- utils/installer/install.sh
Using #3111 as reference for things to change
The stable checks won't pass until v0.9 is released
> feat: lock new installations to nvim 0.9+

- lua/lvim/utils/git.lua
- utils/installer/install.sh
A full clone of this repository is not efficient (due to Repository size).
The [--depth](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt) option tells Git to only download  commits up to a certain depth, which in this case is 1 commit. It also implies `--single-branch` flag automatically, thus ensuring that only one branch (and not multiple branches) will be downloaded.".
```bash
docker run -w /tmp -it --rm alpine:edge sh -uelic 'addgroup -S lunaruser && adduser -S lunaruser -G lunaruser --shell /bin/sh && apk add yarn git python3 cargo neovim ripgrep alpine-sdk bash --update && SCRIPT_URL='https://raw.githubusercontent.com/uid54289/LunarVim/142ee5e0e0322c84e3219fe7c4d6430eb0866d72/utils/installer/install.sh' LV_BRANCH='release-1.3/neovim-0.9' su -c "bash …
```
> perf(`utils/installer`): speed up lvim installation

- lua/lvim/core/lualine/components.lua
To purpose of this change is to make code more redeable by making `unique_client_names` a string with the unique names instead of a table and later on calling `table.concat`. Then use `string.format` instead of string concatenation with `..`
> refactor(lualine): use `string.format` to return unique names

- lua/lvim/lsp/init.lua
Added rounded borders to `:LspInfo` window to make LunarVim experience more cohesive.
`:LspInfo`
> feat(plugin): add rounded borders to :LspInfo window

- lua/lvim/config/_deprecated.lua
the old deprecation message confused some users
before: 
after:
fixes  #4150
> feat: add example to the packer deprecation message

- utils/installer/config_win.example.lua
On Windows, an initial launch of LunarVim will see [telescope-fzf-native.nvim](https://github.com/nvim-telescope/telescope-fzf-native.nvim) fail to build (when it tries to run make) with the following message:
>"Failed to spawn process pwsh.exe -NoLogo { ... }"
The issue is the following line in config_win.example.lua (used to generate config.lua):
```lua
vim.opt.shell = "pwsh.exe -NoLogo"
```
Neovim seems to treat " -NoLogo" as if it's part of the executable name rather than an argument. Changing this to the following fixes the issue:
```lua
vim.opt.shell = "pwsh.exe"
```
The "-NoLogo argument" is already specified in vim.opt.shellcmdflag below this line.
Installed LunarVim from scratch with the alteration above. telescope-fzf-native.nvim now correctly installs.
> fix(win): remove '-NoLogo' from vim.opt.shell

- lua/lvim/lsp/templates.lua
`lsp.installer.setup.ensure_installed` takes priority over `lvim.lsp.automatic_configuration.skipped_servers` causes users cannot skip the default template generations. So if they want to customize their server options they need to skip the entire filetype instead (it's not expected). 
This makes sure the server always be skipped if it's in `skipped_server` list.
> fix(lsp): skip auto config server even if it's ensure installed

- lua/lvim/lsp/init.lua
This fix the wrong behavior of handlers when using with `Noice`, for example.
[Related issue](https://www.reddit.com/r/lunarvim/comments/14iuwi2/issues_using_noice_and_lunarvim/)
> fix(lsp): remove redundant handlers setting

- lua/lvim/lsp/init.lua
The string matching fails when `vim.env.VIMRUNTIME` contains a hyphen.
For example:
`/opt/homebrew/Cellar/neovim/HEAD-e8b3ed7/share/nvim/runtime`
> fix(lsp): restore float border

- lua/lvim/config/_deprecated.lua
> fix(deprecation): only deprecate `tag == "*"` in lvim.plugins

- lua/lvim/core/autocmds.lua
- tests/specs/lsp_spec.lua
Another step towards eliminating flakiness in the CI.
Fixes https://github.com/LunarVim/LunarVim/actions/runs/5989427656/job/16245599387?pr=4341
https://github.com/LunarVim/LunarVim/actions/runs/5989460159/job/16245668584?pr=4341
> test: trigger loading event manually for mason

- lua/lvim/lsp/manager.lua
Lsp manager has been move to separate module in 
https://github.com/neovim/nvim-lspconfig/commit/204f08ea407e4b3b7ad272287e1821f47e52d4b3
> fix(lsp): adapt recent changes in `nvim-lspconfig`

- lua/lvim/lsp/config.lua
Mason recently added `biome` server in https://github.com/williamboman/mason-lspconfig.nvim/commit/1e10ef512d8f7038bfbb651c894dfc8ae2521b57 causes automation tests to fail.
> chore(lsp): add `biome` to `skipped_servers` list

- lua/lvim/lsp/config.lua
Another server from Mason need to be skipped since https://github.com/williamboman/mason-lspconfig.nvim/commit/047438fceff58b26520e3a6487724fad9536f158
> chore(lsp): add `mdx_analyzer` to `skipped_server` list

- lua/lvim/core/treesitter.lua
- lua/lvim/plugins.lua
- snapshots/default.json
This PR fixes a deprecation warning from the `JoosepAlviste/nvim-ts-context-commentstring` plugin.
This has been done following the migration steps mentioned in https://github.com/JoosepAlviste/nvim-ts-context-commentstring/issues/82#issuecomment-1817659634.
_The changes are internal to the setup function, and no further action is required from the user._
_All the options under `lvim.builtin.treesitter.context_commentstring`  will be directly passed to `require('ts_context_commentstring').setup()`_
~~With these changes, we're removing the possibility of customizing the plugin using the `lvim.builtin.treesitter` table. So users won't be able to add more languages to the table for example (but I don't know if that's something users usually do). So yes, in theory this is a breaking change.~~ …
> fix: handle context-commentstring setup

- lua/lvim/core/terminal.lua
The cmdline covers the bottom line of the Lazygit window. Increasing the zindex of the Lazygit window makes the bottom line show.
Fixes #4541 
Opened Lazygit using <leader>gg and bottom line appeared.
> fix(terminal): show lazygit bottom line

- lua/lvim/core/log.lua
- lua/lvim/plugins.lua
- handle the change in https://github.com/LunarVim/bigfile.nvim/issues/12 by avoiding the default setup function
- add `nvim-treesitter/nvim-treesitter` as a dependency just to make sure it's loaded anyway
> fix(plugins): call bigfile setup correctly
