LunarVim/LunarVim

README.md

it might save some time for people who will decide to setup nvm node_host_prog

fix path to the neovim node executable

---

plug-config/fzf.vim

`fzf#vim#grep` wasn't invoked correctly :)

Fix setup for Rg

---

plug-config/fzf.vim

standart way following man pages

change --info-inline to --inline-info.

---

keys/mappings.vim

users can now move a single line or an entire block of text / code
while in visual mode
simply select what you need moved and then use
shift + k to move the selection up
shift + j to move the selection down

feat: can move line selection

---

themes/airline.vim

Cut airline show_tab_type command redundancy

---

init.vim
keys/which-key.vim
plug-config/vim-commentary.vim

enable support for multi line comment

Add multi line comment

---

utils/install.sh

Needed these 2 packages for things to install via the install script

This will help macOS install not fail

---

utils/install.sh
utils/vscode_config/keybindings.json
utils/vscode_config/settings.json

Using using the script in the description, Pynvim install crashes on the default python config. 
Adding a simple `--user` flag fixes it.
`Add --user flag`

Fix Pynvim crashing on OSX

---

keys/which-key.vim

fix for:
CocSearch not working #96

add missing colon makes CocSearch working with which-key

---

lua/lsp/init.lua
lua/lsp/virtual_text.lua
vimscript/nv-whichkey/init.vim

I added a keybind to toggle virtual text in my own config. Feel free to use this PR or take any part you like :)

command and keybind to toggle lsp virtual text

---

README.md

To support Windows system clipboard in neovim on WSL2

Add clipboard support guide for WSL2

---

utils/installer/install.sh

added install tree-sitter-cli

---

lua/lsp/clangd.lua

Adding a PR to support LspInstall clangd - https://github.com/kabouzeid/nvim-lspinstall/pull/15

[LSP] clangd - Support LspInstall clangd.

---

lua/lsp/lua-ls.lua

Fix for the popup with max file preload size is to low, i dig into the code of sumneko and you need to add maxPreload = 10000 to workspace and the number is in kb

Fix for the popup with max preload size is low

---

init.lua
lua/lsp/latex-ls.lua

Basic LaTeX support via LSP (installs TexLab)

[LSP] latex - Add support for latex via LspInstall

---

init.lua
lua/nv-dadbod/init.lua
lua/nv-doge/init.lua
lua/nv-globals.lua
lua/plugins.lua
vimscript/nv-whichkey/init.vim

1. Add Documentation Generator
DoGe is a (Do)cumentation (Ge)nerator which will generate a proper documentation skeleton based on certain expressions (mainly functions). Simply put your cursor on a function, press Leader + *, jump quickly through TODO items using <Tab> and <S-Tab> to quickly add descriptions and go on coding!
2. Integrate dadbod (Database) with which key (fix) + extend config

Documentation generator

---

init.lua
lua/lsp/svelte-ls.lua

Add basic svelte lsp config to support LspInstall

Add svelte lsp config for LspInstall

---

init.lua
lua/lsp/tailwindcss-ls.lua
lua/nv-globals.lua

Add tailwindcss lsp support. My first ever PR and lua edits. Maybe someone can do better. But it works for me.
Tested on next-js dummy project with tailwindcss support added.

Add tailwindcss lsp support

---

lua/lsp/js-ts-ls.lua

It was showing this error, but my tsconfig have the configuration to avoid this error properly, so with this change It's solving It.

Fix tslint is not using tsconfig.json

---

README.md

Recommend neovim-git instead of neovim-nightly-git

---

README.md

Neovim recommends using xclip over xsel: https://github.com/neovim/neovim/pull/9302

Prefer xclip over xsel

---

utils/installer/install.sh

A little change to make it work with Artix (may not be the prettiest because of my bash scripting lack of knowledge but gets the job done).
Already tested on my machine

Add compatibility with Artix Linux (Arch derivative)

---

lua/lv-autocommands/init.lua
lv-settings.lua

Uses the same pattern as the code for lua and json formatting.  Toggleable.

Add autoformatting for ruby

---

init.lua
lua/lsp/efm-general-ls.lua
lua/lsp/vue-ls.lua

Addresses  #294.  Adds vue-ls support

adds vue language server support

---

lua/lsp/efm-general-ls.lua
lua/lv-autocommands/init.lua

Provides typescript formatting. Addresses issue #307

Typescript

---

README.md

Added section for: Installing your own plugins, Using Packer, Lsp Errors

Adds sections to Readme

---

README.md

Added readme section: Colorschemes

Added readme section: Colorschemes

---

README.md

Added section: Uninstalling.  Added links to plugins

Added section: Uninstalling.  Added links to plugins

---

lua/lv-which-key/init.lua

Corrected label for whichkey action.  Changed 'File' to 'Checkout branch'

Corrected label for whichkey action.  Changed 'file' to 'Change branch'

---

lua/lv-galaxyline/init.lua

* Add missing white space on lsp information icon.

🐛  adding a missing space on galaxy line icon. [Low priority]

---

lua/lv-dashboard/init.lua
lua/lv-globals.lua
lv-settings.lua

* User can change the header and footer from lv-settings (comment by default).
* The original one are setted on lv-global

✨  Change dashboard header and footer by user

---

lua/keymappings.lua

I changed the Window Resizing Keymappings from vimscript to lua as the rest of the configuration.

Changed Window resizing to lua

---

init.lua
lua/lsp/java-ls.lua
lua/lsp/ruby-ls.lua
lua/lv-autocommands/init.lua
lua/lv-dashboard/init.lua
lua/lv-globals.lua
vimscript/lv-vscode/init.vim

This makes the configuration files work if neovim's config path is different from `~/.config/nvim`.

Support different config paths

---

ftplugin/css.vim
ftplugin/html.vim
ftplugin/javascript.vim
ftplugin/javascriptreact.vim
ftplugin/yaml.vim

:art: Update ftplugin

---

lua/lsp/tailwindcss-ls.lua

The tailwindcss LSP Server got some changes. This PR is a configuration update in response to those changes

tailwindcss LSP fix

---

lua/lsp/tailwindcss-ls.lua

latest nvim-lspconfig has all the necessary config for tailwindcss included.

Simplify tailwindcss-ls config

---

README.md

Documentation: Add sections 'Troubleshooting installation problems', 'Community links'.  Modify section for clarity 'Install your own plugins'

Documentation: Add sections 'Troubleshooting installation problems',

---

lua/lv-dashboard/init.lua

`lv-settings.lua` has been deprecated, use `lv-config.lua` instead.

Fix settings inside dashboard

---

lua/default-config.lua
lua/settings.lua
utils/installer/lv-config.example.lua

Option for transparent background #615

feat(615): transparent background option

---

lua/lv-which-key/init.lua

[WHICH-KEY] Add SymbolsOutline mapping.

---

utils/installer/install.sh

install.sh had the old name of the project, just changed it.

fix(typo): nvcode -> LunarVim

---

ftplugin/c.lua
lua/default-config.lua
utils/installer/lv-config.example.lua

I always have to manually add code, this would be better if this gets merge, though by default `save on format` and `clangd` both are `false`.

added Clangd format_on_save

---

lua/lv-dashboard/init.lua

[DASHBOARD] Fix Telescope config files lazy-load issue.

---

lua/keymappings.lua

Matches behaviour in vscode.
Moves current line up or down, or a selection up and down.

[KEYBINDINGS] Add Alt-jk etc for move line up/down.

---

.github/ISSUE_TEMPLATE/lsp-issue-form.yaml

Follow up of [618](https://github.com/ChristianChiarulli/LunarVim/pull/618)
Tell me if I forgot anything.

Define a form for LSP issues

---

lua/keymappings.lua

As seen on ThePrimeagen
This one is awesome.

[KEYBINDINGS] Navigate quick-fix list with [q and ]q

---

lua/default-config.lua
lua/lsp/init.lua
lua/lv-which-key/init.lua

Add borders to lsp popups

---

lua/lv-dial/init.lua

Add True/False to dial

---

lua/lv-which-key/init.lua

Adds packer keybindings to whichkey

Adds: packer keybindings

---

README.md

Just added my potato machine testimonial, also added my name on it, you can just remove it if you don't se fit for the readme.

Testimonials

---

init.lua
lua/plugins.lua

Vimtex wasn't loading the config `lua/lv-vimtex/init.lua `. I'm not sure if this is the best way to do this but it does work.

lv-vimtex exists but wasn't called, no config was called.

---

.github/ISSUE_TEMPLATE/feature-form.yaml

Follow up of [626](https://github.com/ChristianChiarulli/LunarVim/pull/626)
Tell me what you think.

Define a form for Feature request issues

---

lua/keymappings.lua

fix resizing keybindings for mac

---

lua/keymappings.lua

Simply converted the keymappings to lua.

Terminal window keymappings from vimscript to lua

---

lua/lv-treesitter/init.lua

fixed treesitter textobject issue

---

lua/lv-galaxyline/init.lua

Fixes #732 
@ChristianChiarulli  did you have something like this in mind?

show virtualenv inside galaxyline

---

lua/keymappings.lua

Fix terminal window navigation keymaps

---

lua/lv-telescope/init.lua

Fix issue with deprecated config value in telescope. Ref: telescope.changelog-839.

Replace deprecated value in  lv-telescope/init.lua

---

ftplugin/rust.lua
lua/default-config.lua

- User config option to change Rust inline hint/param prefixes
- Ordered the language list alphabetically.

User config option to change Rust inline hint/param prefixes

---

lua/lv-which-key/init.lua

More New User Friendly Way to save and quit!

added quit and save for which key

---

init.lua
lua/settings.lua

call colorschemes only after they get installed

---

init.lua
lua/keymappings.lua
lua/lsp/angular-ls.lua
lua/lsp/emmet-ls.lua
lua/lsp/init.lua
lua/lsp/svelte-ls.lua
lua/lsp/tailwindcss-ls.lua
lua/lsp/ts-fmt-lint.lua
lua/lv-telescope/init.lua
lua/lv-which-key/init.lua
lua/settings.lua

Fixed formatting issues according to `stylua`

fix styling issues

---

lua/plugins.lua

Fix telescope-project not loading in dashboard

---

ftplugin/euphoria3.lua
ftplugin/java.lua
ftplugin/python.lua
ftplugin/rust.lua
init.lua
lua/default-config.lua
lua/keymappings.lua
lua/lsp/angular-ls.lua
lua/lsp/init.lua
lua/lsp/svelte-ls.lua
lua/lsp/tailwindcss-ls.lua
lua/lv-gitsigns/config.lua
lua/lv-treesitter/init.lua
lua/lv-utils/init.lua
lua/plugins.lua
utils/installer/lv-config.example-no-ts.lua
utils/installer/lv-config.example.lua

`TODO` looks extra nice with `:` besides it

avoiding OCD attack

---

lua/lv-which-key/config.lua

There is still Neoformat in the whichkey bindings so i updated it to use formatter.nvim

change Neoformat to FormatWrite in whichkey bindings

---

lua/lv-which-key/config.lua
lua/lv-which-key/init.lua

Hope this is okay. 
I struggled with having to edit the `nvim_set_keymap` statements to be able to override the keys in my config file. Works okay on my mac :) I also added a map for visual keybindings

Refactor whichkey config to make all keys overridable in user config

---

lua/lv-which-key/config.lua

Add search for Commands and Keymaps.

[WHICH-KEY] Add search for key-maps and commands.

---

lua/default-config.lua

Fixes #866 
- Open a `lua` file
- Run command `<leader>lf`
- File should be correctly formatted

Stylua formatter issues fixed

---

.github/pull_request_template.md

[Doc] Minimize the pull request template

---

lua/default-config.lua

if you open a file from `telescope`, you won't have the `file not found issue` with `prettier` formatter
Partially fixes #871 
- run `:nvim`
- open a file from telescope using `<leader>f`
- run `<leader>lf` to format

Partially fixes the prettier issue

---

README.md

We should have clearly defined goals for the project. 
And possibly a roadmap.

Clearly defined project goals

---

lua/keymappings.lua

Define a table of mappings like whichkey does, and implement a function for registering them.
This is just a readability improvement, nothing changes apart from the style.

Define keymappings using a mapping table

---

utils/installer/lv-config.example-no-ts.lua
utils/installer/lv-config.example.lua

Currently installer doesn't work
- Run LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/rolling/utils/installer/install.sh)
- ...

indent_line no more

---

init.lua

I think it's confused to see just "something is wrong with your lv-config", people need to know what's wrong so that they can fix it.

Improve error message in lv-config file

---

ftplugin/vue.lua
ftplugin/yaml.lua
ftplugin/zig.lua
ftplugin/zsh.lua
lua/lang/vue.lua
lua/lang/yaml.lua
lua/lang/zig.lua
lua/lang/zsh.lua

Reformat for the following languages:
- vue
- yaml
- zig
- zsh

More language reformat

---

.github/workflows/format.yaml
.github/workflows/install.yaml

We should have some sort of testing, to make sure nothing breaks LunarVim, this is just an attempt to do so,
I'm open to suggestions
@ChristianChiarulli  @rebuilt  @rafamadriz

Github workflows

---

lua/default-config.lua

Add sidescrolloff to default-config

[DEFAULT-CONFIG] Add sidescrolloff

---

ftdetect/fish.lua
ftplugin/fish.lua
lua/lang/fish.lua

this PR would add basic files for Fish.

[LANG] add basic files for Fish

---

lua/settings.lua

Fixed #911

---

lua/core/linter.lua
lua/core/which-key.lua
lua/default-config.lua
lua/lang/clang.lua
lua/lang/go.lua
lua/lang/html.lua
lua/lang/lua.lua
lua/lang/python.lua
lua/lang/ruby.lua
lua/lang/sh.lua
lua/lang/tex.lua
lua/lang/vim.lua
lua/plugins.lua
utils/installer/lv-config.example-no-ts.lua
utils/installer/lv-config.example.lua

Add [nvim-lint](https://github.com/mfussenegger/nvim-lint) dependency and configurations for the [supported](https://github.com/mfussenegger/nvim-lint#available-linters) linters.
While still in early development, the work looks promising and extensible (I might try to add clang-tidy).
Fixes #797 
Open a file and save.
I've tested all languages except HTML and Ruby, so if someone can take care of it and confirm it works, that would be great :+1: 
Also I removed some of the efm configurations since they seemed redundant with the work done by the formatter and linter plugins, if someone can double-check that it would be nice too.

[Feature] add linter support

---

lua/lang/clang.lua
lua/lang/dart.lua
lua/lang/elixir.lua
lua/lang/go.lua
lua/lang/json.lua
lua/lang/lua.lua
lua/lang/php.lua
lua/lang/python.lua
lua/lang/ruby.lua
lua/lang/rust.lua
lua/lang/sh.lua
lua/lang/terraform.lua
lua/lang/yaml.lua

I tried to be smart :facepalm:  and used some weird logic in the formatter `stdin`
there is absolutely no reason for that :sweat_smile:

Explicit stdin for formatters

---

.gitignore

Fixes #(issue)
- Check logs
- ...
Added some common temporal and backup file extensions to .gitignore file.

Feacure: add temporal and backup files to gitignore.

---

lua/lang/ruby.lua

Added Ruby debugging support
to make it work you need to install the following:
```bash
gem install readapt ruby-debug-ide
```
and obviously you need LSP and dap
```vim
:LspInstall ruby
:DIInstall ruby_vsc_dbg
```

Ruby debugging support

---

CONTRIBUTING.md
lua/core/nvimtree.lua
lua/default-config.lua
utils/installer/lv-config.example-no-ts.lua
utils/installer/lv-config.example.lua

Refactor nvimtree to be configurable
lv-config.lua
```
O.plugin.nvimtree.side = "left"
O.plugin.nvimtree.show_icons.git = 0
```

[Refactor] nvimtree to be configurable

---

README.md
utils/installer/lv-config.example-no-ts.lua
utils/installer/lv-config.example.lua

Updated Readme to match current state of the project

Readme Update

---

lua/core/nvimtree.lua

Fixes nvimtree failing during clean install

fixing broken nvimtree

---

utils/installer/install.sh

removed ranger and ueberzug from the install.sh as it not used anymore by lunarvim

remove ranger and ueberzug

---

README.md
lua/lv-utils/init.lua

This PR will let users inspect all LV settings.
Fixes #944 
run the following and the inspect `~/.config/nvim/lv-settings.lua`:
```bash
cd ~/.config/nvim
nvim --headless +'lua require("lv-utils").generate_settings()' +qa && sort -o lv-settings.lua{,}
```

[Feature] Allow users to inspect all settings inside LV

---

lua/core/autopairs.lua
lua/core/formatter.lua
lua/core/linter.lua
lua/lsp/init.lua
lua/lv-utils/init.lua

See the title.
`luacheck *.lua lua/`

[Bugfix]Fix reports from luacheck

---

.github/workflows/format.yaml
.github/workflows/lint.yaml

This provides workflows for linting and checking the format of shell files.
Additionally, I added a job for running luacheck on lua files.
Fixes #(issue)
See GitHub actions on my [fork](https://github.com/Tastyep/LunarVim/actions)

[Feature] Add shell workflows

---

utils/installer/install.sh

[Bugfix] Replace which with command -v

---

.github/workflows/install.yaml
utils/installer/install.sh

Fixed a couple of bugs in the installer script, also fixed the testing process

Enable testing again

---

.github/workflows/install.yaml

now that we are using PPA, we don't need to install build depndencies

we no longer require linux dependencies

---

README.md
init.lua
lua/core/autocmds.lua
lua/core/commands.lua
lua/core/which-key.lua
lua/keymappings.lua
lua/lsp/init.lua
lua/utils/init.lua
utils/installer/lv-config.example-no-ts.lua
utils/installer/lv-config.example.lua

[PR-1025](https://github.com/ChristianChiarulli/LunarVim/pull/1025)
The change is much smaller now.

[Refactor] remove lv prefix

---

lua/default-config.lua

Provide correct spelling for latex linter

correct spelling (chktex)

---

utils/desktop/lvim.desktop
utils/installer/install.sh
utils/installer/uninstall.sh

This PR will add desktop file for lunarvim

[General] Create lvim.desktop

---

utils/vscode_config/settings.json

If you try to use this configuration with **VSCode** as a templete it will not work with the new version of **lunarVim**

[Bugfix] Update settings.json to work to new version

---

README.md
utils/installer/lv-config.example.lua

Provide some which-key mappings samples

---

lua/default-config.lua

Fixes csharp issues, according to [this](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#omnisharp)
```bash
cd /tmp
dotnet new webapi --no-https -o LspTest
cd LspTest
lvim Program.cs
```

[Bugfix] Fix omnisharp not attaching

---

lua/keymappings.lua

Fix typo in insert mode keybindings.
Fixes #(issue)
- Check logs
- ...

Fix typo in insert mode keybindings

---

.github/workflows/install.yaml

if the installation is not finished in 4 mins, it means the LV install is broken and jobs are stalling

[Bugfix] Set 4 min timeout for installation

---

lua/lsp/keybinds.lua

Fixes #(issue)
- Check logs
- ...

fix: change peekDefinition method location

---

lua/core/galaxyline.lua

Fix the galaxyline null pointer issue

---

utils/docker/Dockerfile
utils/docker/script.sh

This is a simple LunarVim docker image based on the python official image. I am installing all Lunar dependencies as well as neovim.

Simple LunarVim docker image

---

lua/core/galaxyline.lua
lua/lsp/init.lua

fix luacheck issues

---

lua/lsp/null-ls.lua

fix eslint_d issue

---

lua/lsp/null-ls.lua

Fixes #(issue)
- Check logs
- ...

why is eslint_d so bad

---

lua/lsp/null-ls.lua

Clean-up null-ls handling for node modules
Still works with local and global prettier/eslint

refactor null-ls

---

utils/installer/install.sh
utils/installer/uninstall.sh

Adds Termux support for lunarvim
Fixes #1201 
Tested on my phone & wsl ubuntu 20.04 LTS
Test Commands: 
- `LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/rynpix/lunarvim/rolling/utils/installer/uninstall.sh)`
- `LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/rynpix/lunarvim/rolling/utils/installer/install.sh)`
```
module 'toggleterm' not found:^Ino field package.preload['toggleterm']^Ino file './toggleterm.lua'^Ino file '/usr/share/luajit-2.1.0-beta3/toggleterm.lua'^Ino file '/usr/local/share/lua/5.1/toggleterm.lua'^Ino file '/usr/local/share/lua/5.1/toggleterm/init.lua'^Ino file '/usr/share/lua/5.1/toggleterm.lua'^Ino file '/usr/share/lua/5.1/toggleterm/init.lua'^Ino file '/home/rayane/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/toggleterm. …
```

[Feature]: Termux Support

---

lua/core/compe.lua

fix compe tab completion issue

---

ftplugin/toml.lua
lua/lsp/null-ls.lua
utils/lush-template/lua/lush_theme/lush_template.lua

Fixes #(issue)
- Check logs
- ...

fix formatting and linting

---

utils/installer/install.sh

Fixes #(issue)
- Check logs
- ...

shfmt correct fix

---

lua/default-config.lua

Reverts LunarVim/LunarVim#1232

Revert "Fix  solargraph root not found issue"

---

lua/lsp/null-ls.lua

Stop registering duplicate null-ls providers
Run this command before and after this fix
`:lua print(vim.inspect(require("lsp.null-ls").requested_providers))`

stop registering duplicate null-ls providers

---

lua/default-config.lua

Fixes #(issue)
- Check logs
- ...

fix formating :cry:

---

lua/core/dap.lua

Fixes #(issue)
- Check logs
- ...

dap.stop is deprecated, use dap.close instead

---

.github/workflows/install.yaml
README.md
ftplugin/elixir.lua
ftplugin/euphoria3.lua
lua/core/dashboard.lua
lua/lsp/peek.lua
lua/utils/init.lua
utils/installer/install_stylua.sh

[Doc]: Fix most typos

---

lua/core/compe.lua

Fixes #(issue)
- Check logs
- ...

fix formatting for compe

---

lua/core/info.lua

Fix window borders for lunarvim info

---

lua/plugins.lua

Fixes #(issue)
- Check logs
- ...

pin astronauta till we figure out the root cause

---

lua/lsp/null-ls.lua

cc: @Tastyep 
sorry man, i know i was not supposed to touch this file 😢

remove the violent message for provider not found

---

lua/core/info.lua

Make LunarVim Info UI more compact.
- Run command `:LvimInfo` on LS activated filetype buffer

[Refactor] LunarVim Info UI

---

lua/core/info.lua

fix nill issues in LunarVim info when there are no active LS or the lang is not in `default_config.lua`

Fix lunarvim info nil issue

---

lua/lsp/init.lua

fixes the nill value issue while opening langs without any lsp provider

Fix nil exception for langs without providers

---

lua/core/autocmds.lua

Title
After typing `git commit`

[Feature]: Add spell checking to git commit filetype

---

lua/plugin-loader.lua

Telescope: round
Lunarvim: round
Packer: not round?
why?
Fixes (my sanity)
I did packer sync then all of sudden, I got to experience rounded borders in its full glory.

[Refactor]: Use rounded borders for packer

---

.github/workflows/format.yaml
lua/lsp/null-ls.lua
utils/bin/jdtls
utils/installer/install.sh
utils/installer/install_stylua.sh
utils/installer/uninstall.sh

Use Google's style guide for shell scripts. 
See: https://google.github.io/styleguide/shellguide.html

Fix formatting according to style-guide

---

.github/workflows/lint.yaml
.pre-commit-config.yaml
CONTRIBUTING.md
utils/bin/jdtls

Add pre-commit hook for linting and formatting that can be version controlled to make contributors' lives a bit easier :)
Powered by: https://pre-commit.com/
```shell
pip install --user pre-commit
cd /path/to/repo
pre-commit install
```
it should not let you commit something with a linter/formatter violation.

feat: Add pre-commit hook for linting and formatting

---

lua/default-config.lua

Fixes #1305
opened a `.pp` file and the language server was working

Support for puppet using lspinstall

---

lua/default-config.lua

Clojure_lsp doesn't require `--stdio` flag
Fixes #1328

Fix clojure language server not starting up

---

ftplugin/fortran.lua
lua/default-config.lua
lua/plugins.lua

Add LSP support for Fortran filetype.
Fixes #1334 
- Open any `*.f90/.f95` file.
- Check logs: `LspInfo` attached `fortls`

[Feature]: LSP Fortran

---

.github/workflows/install.yaml
README.md
utils/bin/lvim
utils/installer/install.sh

- Provide an install script that is more coherent and doesn't require root privileges. Instead it will prompt the user to install any missing requirements with a hint about the possible command.
- Add built-in support for backing up any existing lunarvim folders.
- Add support for cloning from a fork `LV_REMOTE=..`
- Add support for overriding all the destination folders `$LUNARVIM_RUNTIME_DIR`, `$LUNARVIM_CONFIG_DIR`, `$INSTALL_PREFIX`
- Add support for updating automatically if it was already installed and there are no conflicts (--ff-only)
```shell
wget https://raw.githubusercontent.com/kylo252/LunarVim/installer_v2/utils/installer/install.sh
LVBRANCH=installer_v2 LV_REMOTE="kylo252/lunarvim.git" INSTALL_PREFIX=/tmp/t1 LUNARVIM_CONFIG_DIR=/tmp/t1 LUNARVIM_RUNTIME_DIR=/tmp/t2 bash …
```

[Refactor] Installer v2 with support for backup

---

lua/core/lualine/components.lua
lua/core/lualine/init.lua
lua/core/lualine/styles.lua
lua/core/lualine/utils.lua

- Accept custom theme
- Enable lualine for file without filetype
- Configureable LunarVim's component's color and condition
- Rename LunarVim's 'vi_mode' component to 'mode'
config.lua
```lua
local components = require "core.lualine.components"
lvim.builtin.lualine.sections.lualine_a = { "mode" }  -- use lualine's component, not LunarVim's
lvim.builtin.lualine.sections.lualine_c = { components.filename, components.diff }
lvim.builtin.lualine.sections.lualine_y = { components.progress }
```
config.lua
```lua
local gruvbox_dark = require "lualine.themes.gruvbox_dark"
gruvbox_dark.insert.b = { fg = gruvbox_dark.insert.a.bg, gui = "bold" }
gruvbox_dark.visual.b = { fg = gruvbox_dark.visual.a.bg, gui = "bold" }
gruvbox_dark.replace.b = { fg = gruvbox_dark.replace.a.bg, gui = "bold" } …
```

[Feature] enhance lualine config

---

ftplugin/html.lua
ftplugin/javascriptreact.lua
ftplugin/svelte.lua
ftplugin/typescriptreact.lua
ftplugin/vue.lua
lua/config/defaults.lua
lua/lsp/init.lua

Setup tailwindcss language server

---

utils/installer/install.sh

Copy command is different in mac and linux

Fix the installer copy command

---

utils/installer/install.sh

Fixes #(issue)
- Check logs
- ...

fix the installer issue in master

---

lua/config/defaults.lua

In order to get better vuejs support with autoimport and stuff
open a sample vue support

[Feature] Better vue support

---

lua/lsp/null-ls/formatters.lua
lua/lsp/null-ls/linters.lua

Fix the string concat in logging

---

lua/core/which-key.lua

[Bugfix] Revert back buffer bindings

---

ftdetect/bicep.lua
ftplugin/bicep.lua
lua/config/defaults.lua

Added config to support bicep language server.
lspinstall PR is https://github.com/kabouzeid/nvim-lspinstall/pull/155
Fixes #(issue)
- Run command `:LspInstall bicep` using the branch or update if the above PR has been merged
- Opened a bicep file

[Feature]: Add bicep language server

---

lua/lsp/handlers.lua
lua/lsp/init.lua

Changing diagnostics messages would cause some weird issues regarding code actions
here is the result

use a separate func instead of replacing the diagnostics messages

---

utils/installer/install.sh

Changed check to install in the install script. I think "check" can be confused with just looking at the installed packages, rather than actually installing them. I think yay asks if you want to check something when you install some packages, and in those cases its just reviewing the code, so I think the word "install" is clearer. Although there might be some better word like "add"

[Doc] Update install.sh

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md

fix: Fix matrix links

---

utils/installer/config.example.lua

Fixes #(issue)
- Check logs
- ...

Fix a small typo in config.example.lua

---

lua/plugins.lua

there was a couple of bug fixes in the past day, but i' not merging this until @ChristianChiarulli  has signed on it
cause he is the one who pinned it in the first place

Unpin gitsigns to use the latest bugfix commits on their repo

---

.github/workflows/format.yaml
.github/workflows/install.yaml
.github/workflows/lint.yaml
.luacheckrc
.pre-commit-config.yaml
Makefile
tests/bootstrap_spec.lua
utils/bin/test_runner.sh

A first attempt at trying some generic unit-tests. Helps towards #1015.
TODO: 
[ ] being able to parse the output of `checkhealth`
[ ] being able to see the status of Packer commands
[ ] fix installing TreeSitter grammar on the CI
`make test`

[Feature]: Add some very basic unit-tests

---

lua/impatient.lua

- Add support for running impatient on 32bit systems
- Add a setup function for impatient with basic options
Runs fine on a RPi 4

refactor: add 32bit support for impatient

---

init.lua
lua/impatient.lua

- Add a setup function for impatient with basic options
Runs fine on @kylo252's RPi 4

refactor: add explicit setup for impatient

---

.github/workflows/install.yaml
utils/bin/lvim
utils/bin/test_runner.sh
utils/installer/install-neovim-from-release
utils/installer/install.sh

- Make Packer installation path more robust
- Remove the need to use hombrew for sha256sum
Should pass the CI tests

refactor(ci): better path handling

---

lua/bootstrap.lua
lua/plugin-loader.lua

Fixes wrong install path for packer

fix: use correct install path for packer

---

lua/core/lualine/components.lua
lua/core/lualine/styles.lua
lua/plugins.lua

Update lualine configurations according to https://github.com/shadmansaleh/lualine.nvim/pull/24/

[bugfix] Update lualine according to the breaking changes

---

.luacheckrc
lua/bootstrap.lua
lua/core/dashboard.lua
lua/core/info.lua
lua/interface/text.lua

- Add LunarVim's latest version tag to dashboard
- Refactor some VimL to Lua
Displays version based on,
``` bash
git describe --tag
```

[Feature] Add lunarvim latest release tag to dashboard

---

lua/lsp/null-ls/services.lua

add support for local stylelint as a css linter

[Feature] add support for local stylelint

---

ftdetect/json.lua
lua/config/defaults.lua

Fixes #1534 
- `lvim tsconfig.json`
- `:set ft?` outputs jsonc

[Feature]: add basic `JSONC` support

---

lua/impatient.lua
utils/installer/install.sh

Remove any remaining cache files on new installs.
Fixes #1590, #1555

fix: remove outdated cache files on install

---

lua/lsp/handlers.lua

[Bugfix] instead of wrapping the `gl` diagnostics, split them

---

lua/core/nvimtree.lua

Update nvim-tree configurations based on the changes in  https://github.com/kyazdani42/nvim-tree.lua/commit/a864b80bafeba6ea17d1a55e4c6f5e73f189f6bb

update nvim-tree based on the refactor

---

lua/core/nvimtree.lua

bcz of https://github.com/kyazdani42/nvim-tree.lua/commit/1edebb789415e2c63db4ffc4d2ea1149bccbe865

lsp_diagnostics is part of the nvim-tree setup now

---

lua/core/nvimtree.lua

migrate nvim-tree to setup syntax episode 4 :cry:

---

lua/core/nvimtree.lua
utils/installer/config.example-no-ts.lua
utils/installer/config.example.lua

Fixes #(issue)
- Check logs
- ...

fix small bugs in nvim-tree

---

.github/workflows/commitlint.config.js
.github/workflows/commitlint.yml
.pre-commit-config.yaml
CONTRIBUTING.md
utils/ci/run_commitlint.sh

Add commitlint CI for more meaningful and clear commit message
commit messages with
- proper/improper `commit type`
- optional `commit scope` in lower/other cases
- `header length` under/over 72 characters
- `body/footer length` under/over 100 characters per line
- `starting word of summary` in lower/other cases

feat: add commitlint CI

---

utils/installer/install.sh

fix(installer): add missing update call

---

README.md
utils/installer/install.sh

Fixed some spelling mistakes and LunarVim inconsistencies.
No testing since only documentation and string output was changed.

Spelling fixes and LunarVim name consistency

---

lua/lsp/init.lua

Restore the ability to override a server's formatting ability by explicitly setting `lvim.lang.foo.formatters = {...}`
Add this to your `config.lua`
```lua
lvim.lang.javascript.formatters = { { exe = "prettier" } }
```
Now `tsserver` should no longer be prompted to format any js file.

fix: restore the ability to override formatting

---

lua/core/autocmds.lua

Fixes #(issue)
- Check logs
- ...

feat: q quits lsp-installer

---

lua/lsp/providers/yamlls.lua

feat: better kubernetes support

---

lua/lsp/providers/jsonls.lua

because of the previous PR, the NlspConfig completion didn't work

fix: bring back NlspConfig completion

---

.github/workflows/install.yaml
init.lua
lua/lvim/bootstrap.lua
lua/lvim/config/init.lua
lua/lvim/core/commands.lua
lua/lvim/core/which-key.lua
lua/lvim/plugin-loader.lua
lua/lvim/utils/hooks.lua
tests/bootstrap_spec.lua

- better error handling for packer
- use packer in protected mode

feat: better error handling for packer

---

utils/installer/uninstall.sh

Update the uninstallation script and add the ability to remove all backups as well.

fix: update the uninstallation script

---

lua/lvim/core/which-key.lua
lua/lvim/lsp/config.lua
tests/lsp_spec.lua

- fix(ci): blacklist `sorbet` since it's a dupe for `ruby`
- chore: fix ci failures due to newer stylua version

fix(ci): blacklist 'sorbet'

---

lua/lvim/config/init.lua
lua/lvim/keymappings.lua

fix(keymap): unset on reload, load correct order, add unset default

---

lua/lvim/core/autocmds.lua

fix(windows): autocmd requires forward slashes

---

lua/lvim/lsp/null-ls/formatters.lua
lua/lvim/lsp/null-ls/linters.lua

The `is_registered` function now does the validation per method.
Fixes #1966

fix(null-ls): allow the same linter and formatter

---

utils/installer/uninstall.sh

A simple, basic uninstall message

feat: add some messages in uninstall.sh

---

lua/lvim/lsp/manager.lua

Check if the manager `autocomd` has already been configured, since some servers can take a while to initialize.
This helps guarding against a data-race condition where a server can get configured twice, which seems to occur only when attaching to single-files.
Fixes #2012
- Add a duplicate setup call to `pyright`
```lua
-- add this to ~/.config/lvim/after/ftplugin/python.lua
require("lvim.lsp.manager").setup "pyright"
require("lvim.lsp.manager").setup "pyright"
```
- Make sure to start in _single-file-mode_
```shell
touch test.py
lvim test.py
```
- For good-measure, try adding a filetype plugin to trigger packer as well
```lua
{ "Vimjas/vim-python-pep8-indent", ft = "python" }
```

fix(lsp): prevent repeated setup call

---

lua/lvim/config/init.lua
lua/lvim/lsp/utils.lua
lua/lvim/plugin-loader.lua
lua/lvim/utils/hooks.lua

- feat: invoke template re-generation on `LvimReload`
- fix: use the `on_complete` callback which ensures a more consistent experience especially for `nvim-webdev-icons`
- feat: faster git fetch command for packer. Partially fixes #2052
Snappier `LvimReload` including correct loading of dev-icons!

feat: multiple enhancements to lvim-reload

---

utils/installer/install.sh

Remove the old installation files if `LvimUpdate` fails and start with a fresh clone instead.

fix(installer): better handling of existing files

---

utils/installer/install.sh

feat(installer): nicer rsync output

---

utils/installer/install.sh

Today if you have a problem installing the nodejs dependencies for a given package ("npm" or "yarn"), the installer simply quits before trying the other ones. This PR guarantees that all nodejs package managers have failed before quitting.
Fixes #2112 
1. no need to execute the entire script, you can change the last line
```bash
install_nodejs_deps   # just call the function we want
```
2. now set npm/yarn prefix to some nonsense.
```console
$ yarn config set prefix "/blah/blah"
$ yarn global bin
/blah/blah/bin
$ bash install.sh
[ERROR] Unable to install using [yarn] without administrative privileges.
Installing node modules with npm..
All NodeJS dependencies are successfully installed
```

fix(installer): more robust yarn validation

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-form.yaml
.github/ISSUE_TEMPLATE/general-issue-form.yaml
.github/ISSUE_TEMPLATE/lsp-issue-form.yaml

- chore: update feature-request template
- chore: update discord's invitation link
- chore: update the issue templates

chore: update github's templates

---

README.md
lua/lvim/core/log.lua
lua/lvim/core/notify.lua
lua/lvim/plugins.lua
utils/installer/config.example.lua

lazy-load `notify`'s configuration and allow for full configuration including transparent mode.
Fixes #1821
Here's my attempt
https://user-images.githubusercontent.com/59826753/138561290-b18683e7-2f73-494d-8a91-a63ac92e3650.mp4

feat: lazyload notify's configuration

---

.luacheckrc
Makefile
lua/lvim/bootstrap.lua
lua/lvim/config/init.lua
lua/lvim/core/dashboard.lua
lua/lvim/lsp/init.lua
lua/lvim/lsp/peek.lua
lua/lvim/utils/git.lua
tests/minimal_lsp.lua

- refactor: add validate_nvim_version at the beginning of bootstrap
- refactor: more robust git module

refactor(bootstrap): more robust git module

---

lua/lvim/core/gitsigns.lua

default use rounded border for gitsigns.

fix(gitsigns): rounded border

---

lua/lvim/plugins.lua

Temporary solution for which-key, until that patch is merged.
Fixes #2139

fix(which-key): temporary solution for which-key

---

lua/lvim/core/info.lua
lua/lvim/interface/popup.lua
lua/lvim/lsp/utils.lua

- feat(info): display overriden servers for the current filetype
- feat(info): display all active servers, not just for the matching current filetype
- fix(popup): initalize bufnr and win_id

feat(info): display overridden servers for filetype

---

tests/minimal_lsp.lua

Update the `minimal_lsp.lua` to include the latest changes from nvim-lsp-installer
```console
nvim -u tests/minimal_lsp.lua
```

chore(tests): use cmd_env in minimal_lsp.lua

---

lua/lvim/lsp/templates.lua
lua/lvim/plugin-loader.lua
lua/lvim/utils/hooks.lua

Fixes an issue where the hook is deleting `packer-compiled.lua` during installation.

fix(install): avoid data-races for `on_packer_complete`

---

lua/lvim/plugins.lua

No need to use the other branch anymore

fix(which-key): the PR has been merged to the original repo

---

lua/lvim/core/nvimtree.lua

- override nvim_tree.view.close() directly instead of
defining an autocmd
- convert the callbacks to local since they're not used globally
- disable git ignore settings by default
- add new available settings

refactor(nvim-tree): cleanup and update settings

---

.github/ISSUE_TEMPLATE/general-issue-form.yaml
.github/ISSUE_TEMPLATE/lsp-issue-form.yaml
README.md
lua/lvim/bootstrap.lua
utils/installer/install.sh

Require https://github.com/neovim/neovim/releases/tag/v0.6.1

chore(installer): require neovim 0.6.1+

---

lua/lvim/core/nvimtree.lua

Remove old code related to barbar from nvim-tree

refactor(nvim-tree): remove unused code

---

utils/installer/config.example.lua

Typescript and typescript react needs to be added separately
Fixes #(issue)
- Check logs
- ...

Add tsx to treesitter ensure_installed list

---

lua/lvim/core/commands.lua

Update require for bufferline module.
Related to #2267

fix: correct a path to bufferline module

---

.github/workflows/format.yaml
.github/workflows/install.yaml
.github/workflows/lint.yaml
lua/lvim/core/telescope.lua
utils/bin/lvim.ps1
utils/installer/config_win.example.lua
utils/installer/install.ps1
utils/installer/install.sh
utils/installer/uninstall.ps1
utils/installer/uninstall.sh

- feat(windows): add custom config_win.example.lua
- ci(windows): first attempt at a workflow
Fixes #1672, #1804, #1823, #1902, #2309

feat(windows): add custom config_win.example.lua

---

utils/installer/install.ps1

fix(windows): use correct validation for the alias

---

Makefile
lua/lvim/plugin-loader.lua
lua/lvim/plugins.lua
lua/lvim/utils/git.lua
lua/lvim/utils/hooks.lua
snapshots/default.json
tests/lvim/helpers.lua
tests/minimal_init.lua
tests/specs/lsp_spec.lua
tests/specs/plugins_load_spec.lua
utils/ci/generate_new_lockfile.lua
utils/ci/generate_new_lockfile.sh

Replace/integrate the current workflow for pinning plugins with the new snapshot implementation, `:h packer.snapshot()`. 
_Note: The snapshot file is in `json` (even though the documentation states that they're in `lua`)._
Fixes #2343
Related #2085
1. add a default snapshot, `snapshots/default.json`, to hold the the commits of all the core plugins
2. `LvimSyncCorePlugins` now uses `:PackerSnapshotRollback`
3. reduce errors caused by breaking changes in user plugins since they're not handled anymore with `packer.sync()`
4. `PackerSync` will now ignore all the core plugins which are already handled with snapshots, this makes it signficantly faster to finish.
5. allow "unlocking" all the core plugins, by setting an environment variable `$LVIM_DEV_MODE`, e.g. can be defined in …

feat(plugins): add support for packer snapshots

---

lua/lvim/plugin-loader.lua

fix(theme): make sure the new theme is fully loaded

---

.github/workflows/plugins.yml
utils/ci/generate_new_lockfile.sh

Creates a pull request with an updated `snapshots/default.json` on a fixed schedule.
I think we need this to be on rolling first,

ci: test automated gh action

---

.github/workflows/plugins.yml

see: https://github.com/LunarVim/LunarVim/runs/5696642217

ci: fix workflow inputs

---

lua/lvim/plugins.lua

Credit goes to [danielo515](https://github.com/danielo515)

fix(luasnip): make sure all snippets are loaded

---

snapshots/default.json

fix(cmp): update nvim-cmp to the latest version

---

lua/lvim/core/cmp.lua

fix(cmp): bring back default keybindings

---

lua/lvim/core/nvimtree.lua

make sure nvim_tree.on_config_done is consistent with the rest
Fixes #2508

fix(nvimtree): make sure on_config_done is using the correct require

---

lua/lvim/core/nvimtree.lua
snapshots/default.json

It fixes a couple of warnings and issues that people are getting lately

fix(nvimtree): add latest changes from nvimtree

---

lua/lvim/plugins.lua
snapshots/default.json

Since the original one has not been updated in a while, use this branch temporarily

feat(lua-dev): use the newer lua-dev branch till folke comes back

---

lua/lvim/lsp/init.lua
lua/lvim/lsp/utils.lua

what the title says
Fixes #2574

fix(autocmds): make sure we are using codelens correctly

---

lua/lvim/core/nvimtree.lua
snapshots/default.json
utils/installer/config.example.lua
utils/installer/config_win.example.lua

Fixes #2665 #2673
credit goes to [gnmearacaun](https://github.com/gnmearacaun)

fix(nvimtree): update nvim-tree setup

---

lua/lvim/core/nvimtree.lua
lua/lvim/core/telescope.lua
utils/installer/install.sh

credit goes to
@cladera
@wren
@crystal-trd

feat: fix a couple of issues

---

utils/ci/verify_plugins.sh

Use full path to `./utils/ci/verify_plugins.lua`
fixes #2753

fix(installer): use full path to verify_plugins.lua

---

.github/workflows/install.yaml

- update runners versions
- include separate jobs to test compatibility with neovim-nightly
- run installer from the new remote that triggered the action as opposed to
using the `--local` flag, (this avoids issues such as #2753)
fixes #2348

ci: update runners to include nightly neovim

---

.github/workflows/install.yaml
lua/lvim/core/log.lua
lua/lvim/utils/git.lua
utils/installer/install-neovim-from-release
utils/installer/install.sh

fix(installer): always check for shallow clones
fixes #2729

fix(installer): always use check shallow clones

---

utils/installer/install.sh

I found a small typo in install.sh and fixed it

fix: typo in utils/installer/install.sh

---

lua/lvim/lsp/manager.lua

- fix(lsp): return the actual resolved mason-config
- chore: fix typos
fixes #2888
open some perl file and make sure that `perlnavigator` installs and launches correctly
```sh
lvim neovim/scripts/movedocs.pl
```

fix(lsp): return the actual resolved mason-config

---

README.md

Updated readability of the README.md file

docs: fix some typos and enhance readability

---

utils/installer/config.example.lua
utils/installer/config_win.example.lua

Removed references to the deprecated `lvim.lsp.automatic_servers_installation` in template files. Updated said references with `lvim.installer.setup.automatic_servers_installation`.

docs: fix automatic_servers_installation example

---

lua/lvim/core/bufferline.lua
lua/lvim/lsp/providers/sumneko_lua.lua
snapshots/default.json
utils/ci/verify_plugins.lua

- fix(bufferline): handle deprecated options
- chore: bump plugins version
fixes #2993, #3002, #2941, #3003

fix(plugins): handle deprecated options

---

lua/lvim/core/builtins/init.lua
lua/lvim/core/lir.lua
lua/lvim/plugins.lua

- feat: add lir.nvim as a minimal alternative to nvimtree
- only allow setting up lir if `lvim.builtin.nvimtree.active=false`
```lua
lvim.builtin.nvimtree.active = false
lvim.builtin.lir.active = true
```
seems to work fine with `:edit .`

feat: add lir.nvim

---

README.md
lua/lvim/config/defaults.lua
lua/lvim/core/breadcrumbs.lua
lua/lvim/core/builtins/init.lua
lua/lvim/core/illuminate.lua
lua/lvim/core/theme.lua
lua/lvim/lsp/config.lua
lua/lvim/lsp/handlers.lua
lua/lvim/lsp/init.lua
lua/lvim/lsp/utils.lua
lua/lvim/plugins.lua
snapshots/default.json
utils/ci/verify_plugins.lua
utils/installer/config.example.lua
utils/installer/config_win.example.lua

Fix: make sure latest plugins are customizable

---

utils/installer/install.sh

Change-Id: Idbfcb8be24b7b17c2680b6ab0b5c9ee6e807c2fd
Move `-` inside the square brackets, so both version (with or without) is correct.
- Run `install.sh -h`

fix(installer): small fix in help message of install.sh

---

lua/lvim/core/alpha/dashboard.lua

fixes #(issue)
- Check logs
- ...

fix: more consistent dashboard description

---

lua/lvim/core/alpha/dashboard.lua

fix(dashboard): add missing space

---

tests/minimal_lsp.lua

fixes #(issue)
- Check logs
- ...

fix: update minimal_lsp.lua

---

lua/lvim/lsp/config.lua

This will make easier for future people to find the right place to put the debug flag.
Nope

chore(lsp): give null-ls setup default values

---

lua/lvim/bootstrap.lua
lua/lvim/core/illuminate.lua
lua/lvim/core/notify.lua
lua/lvim/lsp/utils.lua
lua/lvim/utils/hooks.lua
tests/specs/plugins_load_spec.lua

- Rename variable with typo correction
- Fix typos in error/info messages
- Fix typos in docs/comments

Fix: correct typos

---

lua/lvim/core/cmp.lua
lua/lvim/plugins.lua

Adding buffer cmp for search, and path for command mode.
Also modified bindings so that they work correctly.

feat: buffer cmp for search, and path for command mode

---

utils/installer/uninstall.sh

Removing desktop file + icons in uninstall script

feat(uninstaller): desktop entry

---

.luacheckrc
.luarc.json
lua/lvim/impatient.lua
lua/lvim/impatient/profile.lua
lua/lvim/utils/hooks.lua

Applied changes:
- additional entries to `std_dirs`
- formatting with stylua

feat: latest impatient updates from upstream

---

lua/lvim/core/alpha.lua

May some people(me), not need the `alpha` plugin, when set `alpha.active` to false, will throw error messages.
- Check logs
- ...
---
plus one question here, when to merge the rolling to master? The last merge is a month ago. 🤔

fix(alpha): check alpha module

---

utils/installer/install.sh
utils/installer/uninstall.sh

fix: don't install desktop file w/o xdg-desktop-menu

---

lua/lvim/lsp/init.lua
snapshots/default.json

more info -> https://github.com/hrsh7th/cmp-nvim-lsp/commit/389f06d3101fb412db64cb49ca4f22a67882e469

fix(nvim-cmp-lsp): update_capabilities has been deprecated

---

lua/lvim/plugins.lua

this may increase little performance.
- Check logs
- ...

perf(plugins): move assert `vim.env.LVIM_DEV_MODE` logic

---

CONTRIBUTING.md

update contirbuting readme with new url for install docs
fixes #3255
- Click the link.

docs: Update contributing readme with new url for install docs.

---

README.md

Removed and reorganized a few images from the `README` like Chris had described.
Issue raised on stream and contributes toward simplifying the readme (#3256)
- Used a markdown previewer locally 
- Verified the result on the fork on GitHub
Then opened this PR :sunglasses:

docs: remove and reorganize images

---

lua/lvim/bootstrap.lua
lua/lvim/lsp/config.lua
tests/minimal_init.lua
utils/ci/run_test.sh

refactor: clean up test env paths

---

snapshots/default.json

New commits in navic fix escaping of some characters
fixes #3305
moved cursor into this elixir function
```elixir
def foo(_, %{args: args}, %{context: context}) do
IO.inspect(args)
end
```

chore(plugins): bump plugins version

---

lua/lvim/lsp/manager.lua

fix(lsp) launch servers in path as well

---

lua/lvim/plugin-loader.lua
lua/lvim/utils/hooks.lua

fix(config): stop reloading the colorscheme to avoid triggering a
warning caused by a bug in nvim-tree
> nvim-tree.lua/lua/nvim-tree/view.lua:442: Invalid window id
fix(packer): run packer recompile on cache_reset
fix(packer): actually restrict sync core plugins
saving `config.lua` shouldn't cause any more errors

fix(config): more comprehensive cache reset

---

.github/workflows/commitlint.yml

ci: test commitlint on pr title

---

lua/lvim/bootstrap.lua
lua/lvim/core/mason.lua

fixes the issue with early launching of servers installed by mason
```lua
-- in config.lua
print(vim.env.PATH)
```

fix(config): use a minimal bootstrap for mason

---

lua/lvim/lsp/providers/sumneko_lua.lua

fix(lsp): disable annoying popup for sumneko-lua

---

utils/docker/Dockerfile.remote

https://github.com/LunarVim/lunarvim.org/pull/288#issuecomment-1320282331

chore: update docker branch to latest release for "Try it first"

---

utils/installer/uninstall.sh

in pr #3508, i have given wrong description for --remove-config flag in help menu fixing it
`Remove old backup folders as well` changed to ` Remove user config files  as well` 
fixes #(issue)

fix(uninstaller): correct a sentence in help

---

.github/pull_request_template.md

Template update
it's this PR https://github.com/LunarVim/LunarVim/pull/3510
I broke it so I fixed my mistake here

docs: github pull request template update

---

lua/lvim/core/breadcrumbs.lua

fixes #(issue)
- Check logs
- ...

fix(breadcrumbs): `E36 Not enough space` when using dap-ui `Eval`

---

lua/lvim/core/bufferline.lua

fixes: https://discord.com/channels/701530051140780102/863625428559986699/1046346894785380432

fix(bufkill): wait for user's input

---

lua/lvim/config/init.lua
lua/lvim/core/indentlines.lua
lua/lvim/core/treesitter.lua
lua/lvim/plugins.lua
snapshots/default.json

disables navic and lsp in big files. disables syntax earlier to make loading of big files faster
fixes #3393
opened these files:
[25MB json](https://github.com/json-iterator/test-data/blob/master/large-file.json)
[180MB josn](https://github.com/zemirco/sf-city-lots-json/blob/master/citylots.json)

perf: handle big files better

---

.github/ISSUE_TEMPLATE/general-issue-form.yaml
.github/ISSUE_TEMPLATE/lsp-issue-form.yaml

- updated troubleshooting link
- added closed issues to the existing issues link
- added a tip on how to copy LvimVersion
- removed LSP support information from the general template

ci: update issue templates

---

lua/lvim/core/alpha.lua

fix: startify theme button bugfix

---

lua/lvim/core/which-key.lua

A lot of people is concerned when they save a file and they don't want auto-format to be applied to it. This adds a nice which key mapping to do that.
This is a command I execute often, there is nothing fancy about it

feat(wich-key): binding to save without formatting

---

utils/installer/config.example.lua
utils/installer/config_win.example.lua

Fixes a small typo in the example configs that did not match the documentation/command flags.
- Uncomment formatters block in the example config
- Line width is not set to 100.
- Apply fix
- Line width is set to 100.
Note: This is a remake of #3607 as I am not well versed enough in git to fix the rebasing issues in that PR manually. @LostNeophyte

fix(config): fix typo in example configs

---

lua/lvim/lsp/config.lua

now you'll be able to focus the float by pressing `gl` again

feat(lsp): focusable line diagnostics

---

lua/lvim/keymappings.lua

feat(keybindings): operator pending mode

---

lua/lvim/core/which-key.lua

Added more which-key mappings for more of Lazy's functions, like cleaning, profiling etc to make it easier for the end-user to discover these.

feat(lazy): add keymappings for profile, log, and debug

---

lua/lvim/plugins.lua
snapshots/default.json

Switch from the one in Chris's account.

refactor: use lir fork in the org

---

lua/lvim/core/lir.lua
lua/lvim/plugins.lua
snapshots/default.json

Highlight dirs is merged upstream

refactor: move to upstream lir

---

lua/lvim/core/dap.lua

fixes #(issue)
- Check logs
- ...

feat(dap-ui): update setup table

---

lua/lvim/core/indentlines.lua

fixes #(issue)
- Check logs
- ...

fix(indentlines): typo

---

lua/lvim/lsp/init.lua

fix(lsp): don't remove mason-lspconfig's hook

---

lua/lvim/core/log.lua

fixes https://github.com/LunarVim/LunarVim/pull/3695#issuecomment-1397417684
> I had to go into ~/.local/share/lunarvim/site/pack/lazy/opt/structlog.nvim and force checkout 45b26a2 after this was merged to have lvim not complain about this.

fix(logger): fix errors with older structlog versions

---

lua/lvim/lsp/config.lua

Fixes DiagnosticSignInfo not showing.

fix: diagnostic sign info not showing

---

lua/lvim/core/nvimtree.lua

fixes #(issue)
- Check logs
- ...

fix: remove deprecated nvim-tree options

---

lua/lvim/plugin-loader.lua

--filter was added in git 2.27.0

fix(plugin-loader): support older git versions

---

lua/lvim/lsp/init.lua
lua/lvim/plugins.lua

fixes 
(https://discord.com/channels/701530051140780102/704077577920446636/1072386753798864957)

fix(lsp): lazy loading

---

lua/lvim/lsp/config.lua

it's holding back plugins-version-bump

chore(lsp): add unocss to skipped_list

---

utils/installer/install.ps1

fixes #3480 and also check the powershell version since Invoke-Expression ignores `#Requires`

fix: win installer syntax error

---

lua/lvim/lsp/providers/lua_ls.lua
tests/minimal_lsp.lua

The lua lsp is renamed to `lua_ls`.

fix(lsp): lua lsp renamed

---

lua/lvim/core/autocmds.lua

feat(autocmds): add `NvimTreeNormalNC` to transparent mode

---

.github/workflows/close-inactive-bot.yml

we have a few issues where we go and remove the stale label manually every time the bot adds it

ci(stale): adjust exemptions

---

lua/lvim/core/which-key.lua

fix(which-key): typo

---

lua/lvim/lsp/providers/yamlls.lua

https://github.com/b0o/SchemaStore.nvim/issues/3 get merged.

feat(lang): yaml use schemastore

---

.github/ISSUE_TEMPLATE/general-issue-form.yaml

Request the user to provide the terminal name for more effortless issue resolve

ci(issue_template): require additional terminal information

---

lua/lvim/core/which-key.lua

This allows stuff like this and more
[Screencast from 2023-04-11 05-00-43.webm](https://user-images.githubusercontent.com/22427111/231053195-f89b5467-3f1f-46e1-810c-6bff876e970e.webm)

feat(keybindings): add code action to visual mode

---

lua/lvim/plugin-loader.lua

fix(bootstrap): delay lsp setup until LazyDone

---

lua/lvim/core/autocmds.lua

fix: make FileOpened autocmd work with quickfix

---

lua/lvim/lsp/providers/tailwindcss.lua

fixes #(issue)
- Check logs
- ...

feat(tailwind): add .ts options to tailwind.config root_pattern

---

lua/lvim/lsp/providers/lua_ls.lua

this will stop the server from prompting the user about updating the work environment
fixes #4049

fix(lsp): add luv library by default to lua_ls

---

lua/lvim/core/treesitter.lua

This will fix inline syntax bug in issue #4109 
added dependencies to the ensure_installed config
fixes #4109
the solution was found in the process of debugging the problem; the maintainer added the good first issue tag to
the issue after a solution was found. 
- Check logs
- ...

fix(treesitter): add a few parsers to `ensure_installed`

---

.github/workflows/plugins.yml

removes the lazy.nvim lockfile

fix(ci): remove config in plugin bump ci

---

snapshots/default.json

fixes https://github.com/LunarVim/LunarVim/issues/4166

fix: bump devicons version

---

lua/lvim/lsp/config.lua

fixes #(issue)
- Check logs
- ...

chore: add `solidity_ls_nomicfoundation` to skipped_servers

---

lua/lvim/core/bufferline.lua

fixes https://github.com/LunarVim/LunarVim/issues/4172, https://github.com/LunarVim/LunarVim/discussions/4059

feat!: use prompts similar to `:confirm` in buf_kill

---

utils/installer/config.example.lua
utils/installer/config_win.example.lua

feat: add starter.lvim link to config.example.lua

---

lua/lvim/lsp/config.lua

fixes #(issue)
- Check logs
- ...

chore: add `custom_elements_ls` to skipped_servers

---

lua/lvim/plugins.lua

Hi, I just noticed it and created a pull request. I hope it's fine.

fix(typo): `form` to `from`

---

lua/lvim/plugins.lua

the repo was moved
fixes #4317

chore(plugins): change `nvim-tree.lua` repo to `nvim-tree` org

---

tests/lvim/helpers.lua
tests/specs/bootstrap_spec.lua
tests/specs/config_loader_spec.lua
tests/specs/lsp_spec.lua

fixes CI issues and improves readability by skipping some expected warning messages.
_tested in #4315_

test: adapt recent changes in neovim and plenary

---

.github/ISSUE_TEMPLATE/general-issue-form.yaml
.github/ISSUE_TEMPLATE/lsp-issue-form.yaml
.github/workflows/install.yaml
lua/lvim/lsp/utils.lua
tests/specs/bootstrap_spec.lua
tests/specs/config_loader_spec.lua
tests/specs/lsp_spec.lua
tests/specs/plugins_load_spec.lua

This should hopefully fix (all) flakiness in the CI :smile:
- test: run busted in sync mode
- ci: update stable release version
- fix(mason): use recommended steps for sources sync
https://github.com/LunarVim/LunarVim/actions/runs/5989391463/job/16245523661?pr=4341

test: run busted in sync mode

---

lua/lvim/core/nvimtree.lua
snapshots/default.json

- chore: bump plugins version
- fix(plugin): remove deprecated nvim-tree option

chore: bump plugins version

---

lua/lvim/core/bufferline.lua
lua/lvim/core/nvimtree.lua
lua/lvim/lsp/utils.lua
snapshots/default.json

- update nvim-tree
- update lualine
- update bufferline 
Note: if you're on nightly, make sure to update to latest since you might get an error with `vim.tbl_islist` otherwise.
Note2: updated the autocmd for `codelens.refresh()` and it seemed to be fine both on v0.9.5 and nightly.

chore: update ui plugins

---

lua/lvim/core/autopairs.lua
lua/lvim/core/terminal.lua
lua/lvim/core/which-key.lua
snapshots/default.json

Updated:
- telescope
- plenary
- gitsigns
- illuminate
- cmp
- toggleterm
- autopairs
Skipped:
- ts-comment-string (tracked in #4451)
- indent-blankline (tracked in #4427)
- LuaSnip (seems tricky to ensure a clean update, see
https://github.com/L3MON4D3/LuaSnip/issues/1071)

chore: update utils plugins
